### ISSUE TITLE
Support `CREATE INDEX CONCURRENTLY` (PostgreSQL)

### ISSUE THREAD

**Issue by casey-chow** [prisma/prisma#14456]
This is being discussed as a comment in https://github.com/prisma/prisma/issues/9154#issuecomment-1127522167, but I wanted to surface it further because I've personally encountered a couple of incidents where not using this has led to database stalling.

Essentially, Prisma does not yet support `CREATE INDEX CONCURRENTLY` in migrations, failing with the following error:

```
Error: P3018

A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 20220722170033_schema_sync_2022_07

Database error code: 25001

Database error:
ERROR: CREATE INDEX CONCURRENTLY cannot run inside a transaction block

DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E25001), message: "CREATE INDEX CONCURRENTLY cannot run inside a transaction block", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("xact.c"), line: Some(3409), routine: Some("PreventInTransactionBlock") }
```

This is kind of odd to me because I was under the impression that Prisma migrations didn't occur in transactions in Postgres as well.

**Comment by designfrontier** [comment]
Just want to stop in and say I am also interested in this being corrected. This could cause some pretty big problems as our DB scales up, and will certainly cause problems for anyone operating with prisma and postgres at scale.

**Comment by jabczyk** [comment]
This is really useful when creating indexes on a production database. An extra `concurrent` attribute could be added to the schema, so we don't have to modify the SQL.
For now, we have to run the migration ourselves and then mark it as resolved with `prisma migrate resolve --applied`.

**Comment by appurist** [comment]
I ran into this yesterday, I assumed a Prisma migration would not lock the whole database but lack of support for CONCURRENTLY did just that. This is on me, for not checking first, but it would probably make sense to support this as an option in the prisma schema file, **and** in the short term maybe a warning could be added for if it generates a CREATE INDEX _without_ concurrently.

I know this isn't really a bug, but it's probably a common problem/pattern for users of Prisma and anything that can be done to help them to avoid the pain of an unexpectedly locked database is probably worth adding the warning for.

**Comment by appurist** [comment]
This problem has now escalated to a show-stopper for our production site. I was able to add a needed index manually using the `CONCURRENTLY` variant (it took 15 hours to run but completed successfully) but then was unable to find a way to get Prisma to accept this as resolved, I think because I was unwilling to leave the `CREATE INDEX` in the migration.sql file without the `CONCURRENTLY` option because if it ever ran, our production site would have a multi-hour complete outage.

I wanted to use the `--applied` option but it doesn't give me a conflict with a migration failure, it sees the index as changed, (added, even though the `schema.prisma` specifies it) and wants to wipe my whole database in order to recreate it. It seems like it knows it was created with a different option. 

I gave up trying to find a combination to make it work, and it came down to a choice between:
- dropping the added indices or
- dropping Prisma.

I came close to dropping Prisma but in the ended up dropping the indices from our production db (concurrently, which was very fast) so that I could change the schema via prisma in the future (as long as I don't need any more indices on that large table).

**Comment by kevinsimper** [comment]
You can run them concurrently, that is what we do, we just run them by hand. This ticket is related https://github.com/prisma/prisma/issues/9154

**Comment by rgoomar** [comment]
I think this would be great to have and along with it an `IF NOT EXISTS` to add even more safety to the migration. 

So something like
```
CREATE INDEX CONCURRENTLY IF NOT EXISTS some_idx ON ...
```

Even if this is a flag or some configuration to add that allows you to customize these, that would be ideal.

**Comment by chris-braidwell** [comment]
A good pattern, as long as the index is non-unique, goes like this:

- outside of Prisma migration, run CREATE INDEX CONCURRENTLY ...
- wait for that to finish
- then in your Prisma migration, run CREATE INDEX IF NOT EXISTS ...

That allows you to create indexes in a non-blocking way where you want to, like in larger DBs or DBs with real users who'd be inconvenienced by a blocking period -- while also ensuring the index is created in any other DB, like test or local dev DBs, where you didn't want to or forgot to run the concurrent index build first.

**Comment by appurist** [comment]
The workaround I have allows me to use full automation from my repo, and that is:
- use the ` --create-only` option to let Prisma create a new migration without applying it
- manually edit the `migration.sql` file to add `CONCURRENTLY` to the index creation
- apply that migration (rerun `migrate dev` without ` --create-only`)
- whenever adding or changing `@@index`, do it **one at a time**. This is because Prisma tries to do it in a transaction and that will fail with `CONCURRENTLY`.
- commit all to source control (git repo)

This process is repeatable from git without user intervention on other installations ,  CI/CD etc.

Just now, I needed to add 4 indexed columns to a table:

1. First I added all four of the (_unindexed_, with default values) columns in a single migration, applied immediately.
2. Then I added **_one_** `@@index` and ran with the  ` --create-only` option, edited the .sql file and added `CONCURRENTLY`. Applied that one.
3. Then I repeated step 2 for the other new 3 indices, applying each migration after each `CONCURRENTLY` edit.

Tip/Warning: Prisma will _auto-apply_ any outstanding migrations (including ` --create-only` migrations) if you create a _new_  
`--create-only` migration, so you don't need to explicitly rerun the `migrate dev` if you have another edit to do.  In other words, running `migrate dev --create-only` first does a `migrate dev`.

**Comment by chris-braidwell** [comment]
> The workaround I have allows me to use full automation from my repo, and that is:
> 
> * use the `--create-only` option to let Prisma create a new migration without applying it
> * manually edit the `migration.sql` file to add `CONCURRENTLY` to the index creation
> * apply that migration (rerun `migrate dev` without `--create-only`)
> * whenever adding or changing `@@index`, do it **one at a time**. This is because Prisma tries to do it in a transaction and that will fail with `CONCURRENTLY`.
> * commit all to source control (git repo)
> 
> This process is repeatable from git without user intervention on other installations , CI/CD etc.
> 
> Just now, I needed to add 4 indexed columns to a table:
> 
> 1. First I added all four of the (_unindexed_, with default values) columns in a single migration, applied immediately.
> 2. Then I added **_one_** `@@index` and ran with the  `--create-only` option, edited the .sql file and added `CONCURRENTLY`. Applied that one.
> 3. Then I repeated step 2 for the other new 3 indices, applying each migration after each `CONCURRENTLY` edit.
> 
> Tip/Warning: Prisma will _auto-apply_ any outstanding migrations (including `--create-only` migrations) if you create a _new_ `--create-only` migration, so you don't need to explicitly rerun the `migrate dev` if you have another edit to do. In other words, running `migrate dev --create-only` first does a `migrate dev`.

If you do that for several indexes, and you apply the backlog of several migrations to another DB, does that work straight-through or do you need to apply the migrations one-by-one and wait for the operation to complete before applying the next migration?

**Comment by appurist** [comment]
@chris-braidwell By separating it into single index migrations, it works straight through, adding the columns with concurrent index updates and no downtime/impact on the server performance as a result (and I just tried it on a brand-new Postgres schema). Ideally, I'd like to see Prisma just apply the `CREATE INDEX` updates outside the transaction (and possibly even _always_ `CONCURRENTLY`) so that it can just recognize the new `.prisma` file and create a single migration from adding columns and indices. I did it in 5 prisma migrates and one git commit at the end. So the 5 migrations were:
```
ALTER TABLE "User" ADD COLUMN ...
CREATE INDEX CONCURRENTLY ...
CREATE INDEX CONCURRENTLY ...
CREATE INDEX CONCURRENTLY ...
CREATE INDEX CONCURRENTLY ...
```
in separate migration files and it's fine, works in CI/CD on our AWS instances, etc.

**Comment by chris-braidwell** [comment]
I've found that a migration script that contains ONLY the `CREATE INDEX CONCURRENTLY` command will succeed. It appears Prisma doesn't wrap an additional transaction around a 1-command script. So having each `CREATE INDEX CONCURRENTLY` command in a separate migration, as @appurist recommended above, works well with Prisma.

That approach works as-is for usual use of non-unique indexes. For unique indexes, it's important to control the timing of later Prisma migrations. If you have subsequent migrations that rely on the unique index existing (like adding a foreign key that refers to the new unique index in the parent table), those migrations need to either (1) be prevented, by controlling your sequence of CI and deployment -- wherever migrations are applied; or (2) be expected to fail if the index is still being built.

**Comment by leppaott** [comment]
The underlying issue should be fixed https://github.com/prisma/prisma/issues/22922 
Should just follow specs in https://github.com/prisma/prisma-engines/blob/main/schema-engine/ARCHITECTURE.md#why-does-migrate-not-run-migrations-in-a-transaction-by-default

Somehow has went unnoticed for this far. Although we've had this happening multiple times. Now we can't call some procedures unless we add 10 migration files.

**Comment by ptrsr** [comment]
I've tried @chris-braidwell approach and although it worked on our DTA environments, **it did not work on our large scale production DB**. The index was created successfully but prisma did not recognise it as a successful migration, causing `prisma migrate deploy` to fail with an unfinished migration in the `_prisma_migrations` table.

In the future we'll migrate these large scale databases by hand and update the `_prisma_migrations` table manually.

**Comment by mateuspiresl** [comment]
Both `CONCURRENTLY` and `WHERE` are unsupported by the Prisma schema, but if you add `WHERE 1=1` to your index creation statement, Prisma will finally leave you alone.

Why isn't `CONCURRENTLY` handled just like `WHERE` is?

**Comment by jacek-prisma** [comment]
This has been fixed in Prisma 7.4.0

**Comment by mtowers-backbone** [comment]
@jacek-prisma I'm still seeing the following error in `7.5.0` when attempting to create a new migration subsequent to one containing `CREATE INDEX CONCURRENTLY` _and_ other SQL statements.

Any suggestions on how to diagnose further on my end?

```
Error: P3006

Migration `20260316120000_<migration_name>` failed to apply cleanly to the shadow database. 
Error:
ERROR: CREATE INDEX CONCURRENTLY cannot run inside a transaction block
   0: schema_core::state::DevDiagnostic
             at schema-engine/core/src/state.rs:314
```

e.g. 
```sql
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS ...

BEGIN;

ALTER INDEX "old_index_name"
  RENAME TO "new_index_name";

COMMIT;
```

I tried removing the `BEGIN`/`COMMIT` from the migration as well, but get the same error.

**Comment by thecoolestcoderrushil** [comment]
The database-stalling incidents you mention are why Antifailure focuses on runtime evidence rather than static migration advice alone. We create a disposable production-shaped stack, apply the real migration, and show observed lock duration and application latency impact before release. Would you be open to sharing feedback on that approach?
https://antifailure.dev/
