### ISSUE TITLE
Full-Text Search Capability

### ISSUE THREAD

**Issue by cr101** [prisma/prisma#1684]
This is a feature request for Full-Text Search functionality to perform a fulltext search on specific fields.

**Comment by LawJolla** [comment]
This is a feature promised since the early days of Prisma 1.  The lack of full text search and aggregations really holds Prisma back.  🤞

**Comment by Maxhodges** [comment]
this is fixed in Prisma 2 right?

Looks like they fixed everything:

- Non-trivial unique constraints - such as requiring all Post titles should be unique within the context of their user
- No case-insensitive search for text fields
- Multi-column keys
- multi-column sort
- support for GIS queries

## According to the Team Prisma the product only has 3 limitation
https://www.prisma.io/docs/more/limitations

**Comment by Sytten** [comment]
No this is not fixed, probably that was removed by accident. @janpio can you take over here.

**Comment by janpio** [comment]
Limitations are different than missing features or bugs. The former are listed on https://www.prisma.io/docs/more/limitations, and for the latter we have a lot of feature requests here in this repository: https://github.com/prisma/prisma/labels/kind%2Ffeature

This issue tracks the implementation of support for Full-Text Search Capabilities. We will post updates here when we start implementation of this.

**Comment by cyrus-za** [comment]
What's the latest with text search @janpio

**Comment by JakubKoralewski** [comment]
As [another user on the Spectrum.Chat points out](https://spectrum.chat/prisma/general/full-text-search-availability~2c5fa29a-1d54-4a74-8d73-a361516e9df0) the ["Fuzzy/Phrase full text search" feature is available on PostgreSQL, SQL Server and MySQL](https://www.prisma.io/docs/reference/database-reference/database-features#misc) but how to use this feature?

**Comment by pantharshit00** [comment]
@JakubKoralewski Looks like the user pointed to the Prisma 1 issue there: https://github.com/prisma/prisma1/issues/1183

Full text is not supported in Prisma yet as seen in the chart you have linked. You will need to use a raw query here for now. 

Leave a +1 in this issue if you want to climb up the priority list. Right now you can see the roadmap for Prisma here: https://pris.ly/roadmap

**Comment by milan090** [comment]
+1

**Comment by brielov** [comment]
+1

**Comment by correaricardo** [comment]
+1

**Comment by zoltanarvai** [comment]
I don’t think there are any issues using a raw query here at all. My question is more related to the raw migration. How can we add our GIN index? Can we just create a new migration manually that is not generated based on the schema?

**Comment by yenicelik** [comment]
any updates on this issues? I think this is a very important functionality provided by for text-heavy databases

**Comment by yenicelik** [comment]
or any ideas on what workaround there are to implement this?

**Comment by h0merjam** [comment]
I use middleware to sync documents to an Elasticsearch database, then I add a GraphQL resolver to query it and return the document IDs. I then use Prisma to get the actual data using the document IDs and GraphQL takes care of returning only the fields I want.

**Comment by brielov** [comment]
@h0merjam It is a nice workaround, but it is a shame that we have to depend on external services given the powerful full-text search options offered by `Postgres`  like `tsvector`, `soundex`, etc. Prisma should take more advantage of native capabilities.

**Comment by h0merjam** [comment]
I think it'll end up being a plugin as Prisma aims to support more than just Postgres(?), but I agree it would be 💯 💥

**Comment by brielov** [comment]
@h0merjam You are right, but `SQLite` doesn't support enums for example and Prisma is aware of this at the time of choosing an adapter. I think they do the same for "native types". So, I suspect it wouldn't be that hard to support full-text search indexes when you choose to go with Postgres instead of MySQL or SQLite for example.

**Comment by janpio** [comment]
This is most probably what will happen @brielov - it just did not make the top of our priority list yet. When that happens, we will investigate the different support of different databases like PostgreSQL and MySQL and hopefully find a good way to represent that in Prisma Schema and make it available in Prisma Client, and support it in Prisma Migrate. Please make sure you left a 👍 on the original message in this issue.

**Comment by ahmetuysal** [comment]
Any updates on this request? Is there any way I can add full text search (for Postgres) without writing whole thing in raw SQL?

**Comment by janpio** [comment]
Not right now, not before this is release from our side. As you can see above your message, we have an Epic and API Design that we are working on finalizing. This might take a few weeks though until it is shipped, so no ETA.

**Comment by brielov** [comment]
Right after cascade deletes (which is already in preview), I think this is the other "big" missing feature to make Prisma really functional and really shine. Looking forward to seeing what the team will come up with (:

**Comment by kkarimi** [comment]
Really looking forward to this feature!

**Comment by brielov** [comment]
Prisma 2.30 is out with full text search support, but I must say I'm a little disappointed. For what I've seen in the documentation, it only supports GIN indexes with various operators. Is this correct? Will this work with other algorithms like soundex? On the other hand, it is still a big improvement and a welcome one. Keep up the good work!

**Comment by supermacro** [comment]
Congrats on shipping FTS 👏  ... any plans on implementing this for other databases? Namely MySQL.

**Comment by matthewmueller** [comment]
Hey @brielov, you should also be able to use GiST operators. The problem is that Prisma's introspection and migrate don't understand these indexes yet, but you should be able to create them yourself in SQL.

**Comment by matthewmueller** [comment]
Closing this issue since we shipped Full-Text Search for Postgres in Preview in [2.30.0](https://github.com/prisma/prisma/releases/tag/2.30.0)!

Feel free to open additional issues for more database support or additional features.

**Comment by miradnan** [comment]
Is Full text search added for PostgreSQL?

**Comment by floelhoeffel** [comment]
Hello everyone 👋

We are starting design work to improve Prisma's support for **Full Text Search (FTS)**!

If you would like to help, please help us learn about your needs via a short [FTS user research survey](https://prisma103696.typeform.com/fts-survey).

Thank you!

**Comment by younes-alouani** [comment]
This feature doesn't support full text in spanish or french for exemple. 

In case you have a blog model with two fields : title and body. 
And suppose users can publish blog posts in two languages, prisma right now can't support searching in two languages or at least isn't documented.
