### ISSUE TITLE
Running `prisma migrate dev` against a Supabase database times out (without the existence of a pre-existing explicit shadow database)

### ISSUE THREAD

**Issue by zachtil** [prisma/prisma#17160]
### Bug description

When you first run `migrate dev` against a brand new Supabase database to start the migration history, the command times out after exactly 120 seconds and shows this timeout error.

```
Error: db error: ERROR: canceling statement due to statement timeout
   0: migration_core::state::DevDiagnostic
             at migration-engine/core/src/state.rs:264
```

After a few trials and errors, the issue gets resolved when you create another brand new Supabase database which you can designate as the shadow database in:
* `.env` with `SHADOW_DATABASE_URL` 
* `schema.prisma` with `shadowDatabaseUrl = env("SHADOW_DATABASE_URL")`

If you run `migrate dev` after this, the command completes successfully. Here is an example output:

```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "postgres", schema "public" at "db.[hostname-code].supabase.co:5432"

Applying migration `20230105193806_init`

The following migration(s) have been created and applied from new schema changes:

migrations/
  └─ 20230105193806_init/
    └─ migration.sql

Your database is now in sync with your schema.

✔ Generated Prisma Client (4.8.0 | library) to ./node_modules/@prisma/client in 383ms
```

In this case, it seems to remain unclear why the first migration to Supabase times out but having a better error message might help users understand what they need to do next.

### How to reproduce

1. Create a free Supabase database and copy its Nodejs connection string.
2. Use `try-prisma` to set up the `typescript/rest-nestjs` template in a folder on your local file system.
3. Paste the Nodejs Supabase db connection string in a new `.env` file. (The template does not have one by default).
4. Install `dotenv` with `npm install dotenv`.
5. Add `env("DATABASE_URL")` to the `schema.prisma` file and change `provider` to `postgresql`.
6. Run `npx prisma migrate dev --name init`.

**Result**

After exactly 2 minutes, the command times out with the following error:

```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "postgres", schema "public" at "db.[hostname-code].supabase.co:5432"

Error: db error: ERROR: canceling statement due to statement timeout
   0: migration_core::state::DevDiagnostic
             at migration-engine/core/src/state.rs:264
```

### Expected behavior

Running `migrate dev` should complete successfully, like so:

```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "postgres", schema "public" at "db.[hostname-code].supabase.co:5432"

Applying migration `20230105193806_init`

The following migration(s) have been created and applied from new schema changes:

migrations/
  └─ 20230105193806_init/
    └─ migration.sql

Your database is now in sync with your schema.

✔ Generated Prisma Client (4.8.0 | library) to ./node_modules/@prisma/client in 383ms
```

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider          = "postgresql"
  url               = env("DATABASE_URL")
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  title     String
  content   String?
  published Boolean  @default(false)
  viewCount Int      @default(0)
  author    User?    @relation(fields: [authorId], references: [id])
  authorId  Int?
}

```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: macOS
- Database: Supabase
- Node.js version: v16.15.0

### Prisma Version

```
prisma                  : 4.8.0
@prisma/client          : 4.8.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine d6e67a83f971b175a593ccc12e15c4a757f93ffe (at ../node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli d6e67a83f971b175a593ccc12e15c4a757f93ffe (at ../node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core d6e67a83f971b175a593ccc12e15c4a757f93ffe (at ../node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt d6e67a83f971b175a593ccc12e15c4a757f93ffe (at ../node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.8.0-61.d6e67a83f971b175a593ccc12e15c4a757f93ffe
Default Engines Hash    : d6e67a83f971b175a593ccc12e15c4a757f93ffe
Studio                  : 0.479.0
```

**Comment by vovaklimov** [comment]
Yep, same issue for me

**Comment by ChrisGambrell** [comment]
Experiencing the same issue as well

**Comment by dthx2710** [comment]
same here

**Comment by vinayraghu** [comment]
Ran into the same issue today

**Comment by janpio** [comment]
DEBUG=* output with a defined `shadowDatabaseUrl` to a database that does not exist yet:
```
PS C:\Users\Jan\Documents\throwaway\supabaseRepro> $env:DEBUG="*"
PS C:\Users\Jan\Documents\throwaway\supabaseRepro> npx prisma migrate dev
  prisma:engines  binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
  prisma:loadEnv  project root found at C:\Users\Jan\Documents\throwaway\supabaseRepro\package.json +0ms
  prisma:tryLoadEnv  Environment variables loaded from C:\Users\Jan\Documents\throwaway\supabaseRepro\.env +0ms
  prisma:getConfig  Using getConfig Wasm +0ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +2ms
  prisma:loadEnv  project root found at C:\Users\Jan\Documents\throwaway\supabaseRepro\package.json +7ms
  prisma:tryLoadEnv  Environment variables loaded from C:\Users\Jan\Documents\throwaway\supabaseRepro\.env +6ms
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
  prisma:getConfig  Using getConfig Wasm +5ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +3ms
Datasource "db": PostgreSQL database "postgres_shadow3", schema "public" at "db.hbxzsouosfcintorgwve.supabase.co:5432"

  prisma:getDMMF  Using CLI Query Engine (Node-API Library) at: C:\Users\Jan\Documents\throwaway\supabaseRepro\node_modules\@prisma\engines\query_engine-windows.dll.node +0ms
  prisma:getDMMF  Loaded Node-API Library +4ms
  prisma:getDMMF  unserialized dmmf result ready +1ms
  prisma:getDMMF  dmmf retrieved without errors in getDmmfNodeAPI +0ms
  prisma:getConfig  Using getConfig Wasm +12ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +4ms
  prisma:getConfig  Using getConfig Wasm +2ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +3ms
PostgreSQL database postgres_shadow3 created at db.hbxzsouosfcintorgwve.supabase.co:5432

  prisma:migrateEngine:rpc  starting migration engine with binary: C:\Users\Jan\Documents\throwaway\supabaseRepro\node_modules\@prisma\engines\migration-engine-windows.exe +0ms
  prisma:migrateEngine:rpc  SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"devDiagnostic","params":{"migrationsDirectoryPath":"C:\\Users\\Jan\\Documents\\throwaway\\supabaseRepro\\prisma\\migrations"}} +4ms   
  prisma:migrateEngine:stderr  {"timestamp":"2023-01-13T18:00:30.244048Z","level":"INFO","fields":{"message":"Starting migration engine RPC server","git_hash":"d6e67a83f971b175a593ccc12e15c4a757f93ffe"},"target":"migration_engine"} +0ms
  prisma:migrateEngine:rpc  {
  jsonrpc: '2.0',
  error: {
    code: 4466,
    message: 'An error happened. Check the data field for details.',
    data: {
      is_panic: false,
      message: 'db error: ERROR: canceling statement due to statement timeout\n' +
        '   0: migration_core::state::DevDiagnostic\n' +
        '             at migration-engine\\core\\src\\state.rs:264',
      backtrace: null
    }
  },
  id: 1
} +2m
Error: Error: db error: ERROR: canceling statement due to statement timeout
   0: migration_core::state::DevDiagnostic
             at migration-engine\core\src\state.rs:264

    at Object.<anonymous> (C:\Users\Jan\Documents\throwaway\supabaseRepro\node_modules\prisma\build\index.js:93745:25)
    at MigrateEngine.handleResponse (C:\Users\Jan\Documents\throwaway\supabaseRepro\node_modules\prisma\build\index.js:93596:36)
    at LineStream3.<anonymous> (C:\Users\Jan\Documents\throwaway\supabaseRepro\node_modules\prisma\build\index.js:93695:16)
    at LineStream3.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at LineStream3._pushBuffer (C:\Users\Jan\Documents\throwaway\supabaseRepro\node_modules\prisma\build\index.js:93473:17)
    at LineStream3._transform (C:\Users\Jan\Documents\throwaway\supabaseRepro\node_modules\prisma\build\index.js:93467:8)
    at Transform._write (node:internal/streams/transform:175:8)
```

And same with no `shadowDatabaseUrl` (so Migrate tries to create the database itself under the hood):

```
PS C:\Users\Jan\Documents\throwaway\supabaseRepro> npx prisma migrate dev
  prisma:engines  binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
  prisma:loadEnv  project root found at C:\Users\Jan\Documents\throwaway\supabaseRepro\package.json +0ms
  prisma:tryLoadEnv  Environment variables loaded from C:\Users\Jan\Documents\throwaway\supabaseRepro\.env +0ms
  prisma:getConfig  Using getConfig Wasm +0ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +4ms
  prisma:loadEnv  project root found at C:\Users\Jan\Documents\throwaway\supabaseRepro\package.json +11ms
  prisma:tryLoadEnv  Environment variables loaded from C:\Users\Jan\Documents\throwaway\supabaseRepro\.env +10ms
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
  prisma:getConfig  Using getConfig Wasm +5ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +1ms
Datasource "db": PostgreSQL database "postgres", schema "public" at "db.hbxzsouosfcintorgwve.supabase.co:5432"

  prisma:getDMMF  Using CLI Query Engine (Node-API Library) at: C:\Users\Jan\Documents\throwaway\supabaseRepro\node_modules\@prisma\engines\query_engine-windows.dll.node +0ms
  prisma:getDMMF  Loaded Node-API Library +5ms
  prisma:getDMMF  unserialized dmmf result ready +2ms
  prisma:getDMMF  dmmf retrieved without errors in getDmmfNodeAPI +0ms
  prisma:getConfig  Using getConfig Wasm +14ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +3ms
  prisma:getConfig  Using getConfig Wasm +1ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +2ms
  prisma:migrateEngine:rpc  starting migration engine with binary: C:\Users\Jan\Documents\throwaway\supabaseRepro\node_modules\@prisma\engines\migration-engine-windows.exe +0ms
  prisma:migrateEngine:rpc  SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"devDiagnostic","params":{"migrationsDirectoryPath":"C:\\Users\\Jan\\Documents\\throwaway\\supabaseRepro\\prisma\\migrations"}} +6ms
  prisma:migrateEngine:stderr  {"timestamp":"2023-01-13T18:04:00.9045162Z","level":"INFO","fields":{"message":"Starting migration engine RPC server","git_hash":"d6e67a83f971b175a593ccc12e15c4a757f93ffe"},"target":"migration_engine"} +0ms
  prisma:migrateEngine:rpc  {
  jsonrpc: '2.0',
  error: {
    code: 4466,
    message: 'An error happened. Check the data field for details.',
    data: {
      is_panic: false,
      message: 'db error: ERROR: canceling statement due to statement timeout\n' +
        '   0: migration_core::state::DevDiagnostic\n' +
        '             at migration-engine\\core\\src\\state.rs:264',
      backtrace: null
    }
  },
  id: 1
} +2m
Error: Error: db error: ERROR: canceling statement due to statement timeout
   0: migration_core::state::DevDiagnostic
             at migration-engine\core\src\state.rs:264

    at Object.<anonymous> (C:\Users\Jan\Documents\throwaway\supabaseRepro\node_modules\prisma\build\index.js:93745:25)
    at MigrateEngine.handleResponse (C:\Users\Jan\Documents\throwaway\supabaseRepro\node_modules\prisma\build\index.js:93596:36)
    at LineStream3.<anonymous> (C:\Users\Jan\Documents\throwaway\supabaseRepro\node_modules\prisma\build\index.js:93695:16)
    at LineStream3.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at LineStream3._pushBuffer (C:\Users\Jan\Documents\throwaway\supabaseRepro\node_modules\prisma\build\index.js:93473:17)
    at LineStream3._transform (C:\Users\Jan\Documents\throwaway\supabaseRepro\node_modules\prisma\build\index.js:93467:8)
    at Transform._write (node:internal/streams/transform:175:8)
```

**Comment by janpio** [comment]
Related issues: https://github.com/prisma/prisma/issues/16853

**Comment by janpio** [comment]
Definitely reproducible right now:
```
PS C:\Users\Jan\Documents\throwaway\supabaseRepro> npx prisma migrate dev
  prisma:engines  binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
  prisma:loadEnv  project root found at C:\Users\Jan\Documents\throwaway\supabaseRepro\package.json +0ms
  prisma:tryLoadEnv  Environment variables loaded from C:\Users\Jan\Documents\throwaway\supabaseRepro\.env +0ms
  prisma:getConfig  Using getConfig Wasm +0ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +2ms
  prisma:loadEnv  project root found at C:\Users\Jan\Documents\throwaway\supabaseRepro\package.json +11ms
  prisma:tryLoadEnv  Environment variables loaded from C:\Users\Jan\Documents\throwaway\supabaseRepro\.env +9ms
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
  prisma:getConfig  Using getConfig Wasm +5ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +1ms
Datasource "db": PostgreSQL database "postgres", schema "public" at "db.hbxzsouosfcintorgwve.supabase.co:5432"

  prisma:getDMMF  Using CLI Query Engine (Node-API Library) at: C:\Users\Jan\Documents\throwaway\supabaseRepro\node_modules\@prisma\engines\query_engine-windows.dll.node +0ms
  prisma:getDMMF  Loaded Node-API Library +5ms
  prisma:getDMMF  unserialized dmmf result ready +1ms
  prisma:getDMMF  dmmf retrieved without errors in getDmmfNodeAPI +0ms
  prisma:getConfig  Using getConfig Wasm +11ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +5ms
  prisma:getConfig  Using getConfig Wasm +1ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +3ms
  prisma:migrateEngine:rpc  starting migration engine with binary: C:\Users\Jan\Documents\throwaway\supabaseRepro\node_modules\@prisma\engines\migration-engine-windows.exe +0ms
  prisma:migrateEngine:rpc  SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"devDiagnostic","params":{"migrationsDirectoryPath":"C:\\Users\\Jan\\Documents\\throwaway\\supabaseRepro\\prisma\\migrations"}} +121ms
  prisma:migrateEngine:stderr  {"timestamp":"2023-01-13T19:07:44.7209842Z","level":"INFO","fields":{"message":"Starting migration engine RPC server","git_hash":"d6e67a83f971b175a593ccc12e15c4a757f93ffe"},"target":"migration_engine"} +0ms
  prisma:migrateEngine:rpc  {
  jsonrpc: '2.0',
  error: {
    code: 4466,
    message: 'An error happened. Check the data field for details.',
    data: {
      is_panic: false,
      message: 'db error: ERROR: canceling statement due to statement timeout\n' +
        '   0: migration_core::state::DevDiagnostic\n' +
        '             at migration-engine\\core\\src\\state.rs:264',
      backtrace: null
    }
  },
  id: 1
} +2m
Error: Error: db error: ERROR: canceling statement due to statement timeout
   0: migration_core::state::DevDiagnostic
             at migration-engine\core\src\state.rs:264

    at Object.<anonymous> (C:\Users\Jan\Documents\throwaway\supabaseRepro\node_modules\prisma\build\index.js:93745:25)
    at MigrateEngine.handleResponse (C:\Users\Jan\Documents\throwaway\supabaseRepro\node_modules\prisma\build\index.js:93596:36)
    at LineStream3.<anonymous> (C:\Users\Jan\Documents\throwaway\supabaseRepro\node_modules\prisma\build\index.js:93695:16)
    at LineStream3.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at LineStream3._pushBuffer (C:\Users\Jan\Documents\throwaway\supabaseRepro\node_modules\prisma\build\index.js:93473:17)
    at LineStream3._transform (C:\Users\Jan\Documents\throwaway\supabaseRepro\node_modules\prisma\build\index.js:93467:8)
    at Transform._write (node:internal/streams/transform:175:8)
```

And with a manually create shadow database:
```
PS C:\Users\Jan\Documents\throwaway\supabaseRepro> npx prisma migrate dev
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": PostgreSQL database "postgres", schema "public" at "db.tzbdgkomzvaycrawvppb.supabase.co:5432"

√ Enter a name for the new migration: ... init
Applying migration `20230113193822_init`

The following migration(s) have been created and applied from new schema changes:

migrations/
  └─ 20230113193822_init/
    └─ migration.sql

Your database is now in sync with your schema.

✔ Generated Prisma Client (4.8.1 | library) to .\node_modules\@prisma\client in 66ms
```

**Comment by janpio** [comment]
This also seems to happen when one manually tries do `DROP DATABASE` with any PostgreSQL Client on a Supabase database you created manually, so this might indeed be a problem triggered when the shadow database is tried to be dropped. I am in communication with Supabase about this now.

**Comment by janpio** [comment]
Hey everyone, we are investigating this together with Supabase. Here is our public issue for this: https://github.com/supabase/supabase/issues/11691

As long as the problem persists, you can indeed manually `CREATE DATABASE` a database in your existing project or create another free project and get its database - and then use that as an explicitly configured `shadowDatabaseUrl` in your Prisma schema file. Then all command should work successfully and as intended.

**Comment by janpio** [comment]
Problem confirmed by Supabase now: https://github.com/supabase/supabase/issues/11691#issuecomment-1398193618

Until this is figured out, please keep using the workaround of using a `shadowDatabaseUrl` with a separate project's database or one that you created manually with `CREATE DATABASE`.

**Comment by Jolg42** [comment]
And now fixed by Supabase:

              Hello everybody - we've released [pg_net 0.7](https://github.com/supabase/pg_net/releases/tag/v0.7) to the Supabase platform, which fixes this issue.

This is now available for any new project, or to any project that is paused and then unpaused.
As for existing projects which can't afford to be paused, or cannot be paused, we're working on our strategy to update them in the weeks to come - will update here when we roll this out.

_Originally posted by @pcnc in https://github.com/supabase/supabase/issues/11691#issuecomment-1404638760_

**Comment by samuel-antwi** [comment]
I am having issue when I run prisma migrate dev. This is my schema.prisma 

<img width="551" alt="schema" src="https://user-images.githubusercontent.com/29069653/216611712-64ea043e-add7-4ce1-86e9-db6ebf9da827.png">

When I run the migrate command, I get this error: 
Error: P3016

The fallback method for database resets failed, meaning Migrate could not clean up the database entirely. Original error: 
db error: ERROR: cannot drop table auth.users because other objects depend on it
DETAIL: constraint buckets_owner_fkey on table storage.buckets depends on table auth.users
constraint objects_owner_fkey on table storage.objects depends on table auth.users
HINT: Use DROP ... CASCADE to drop the dependent objects too.
   0: sql_migration_connector::best_effort_reset
           with namespaces=Some(Namespaces("public", ["auth"]))
             at migration-engine/connectors/sql-migration-connector/src/lib.rs:333
   1: migration_core::state::DevDiagnostic
             at migration-engine/core/src/state.rs:269

To be honest, I am new to subbase and Prisma so I think there is something I am not doing right. Does anyone have any idea what is going on here? I am stuck on this for a long time and I will appreciate any help to move forward.

**Comment by janpio** [comment]
Can you please open a new issue about this @samuel-antwi ? I don't think you are doing anything wrong, this is just an unexpected side effect of `multiSchema` that we need to undertand and fix. Thanks. And also thanks for your comment!

**Comment by BrennerSpear** [comment]
Should this documentation here be updated? My understanding is we no longer need a shadow database, correct?
https://supabase.com/docs/guides/integrations/prisma#configuring-the-project-to-use-postgresql

**Comment by samuel-antwi** [comment]
I tried without shadow database and it didn't work. I'm talking about just few weeks ago. Unless there has been some recent updates that I'm not aware of.

**Comment by janpio** [comment]
Supabase fixed the problem a bit more than a week ago. The shadow database is still needed and used, but it is created behind the scenes. You do _not_ need to set a `shadowDatabaseUrl` any more.

As there has been no update on https://github.com/supabase/supabase/issues/11691#issuecomment-1404638760 yet, I assume this is not rolled out to all users on their platform - so we are keeping this issue open. Maybe they are also waiting with updating the documentation until this really has happened for all users.

**Comment by p4nthera115** [comment]
@samuel-antwi I'm having the exact same problem you are having, did you find a solution?

**Comment by samuel-antwi** [comment]
> @samuel-antwi I'm having the exact same problem you are having, did you find a solution?

Unfortunately, I haven't found any solution to this. What I am doing at the moment is creating my tables inside Supabase using the SQL editor and then running prisma.db.pull to pull it from Supabse. It is painful doing it this way and you also lose a lot of good DX Prisma gives you but I don't have a choice for now. If I don't find a solution, I will definitely drop Prisma and use the Supabase client.

**Comment by p4nthera115** [comment]
> > @samuel-antwi I'm having the exact same problem you are having, did you find a solution?
> 
> Unfortunately, I haven't found any solution to this. What I am doing at the moment is creating my tables inside Supabase using the SQL editor and then running prisma.db.pull to pull it from Supabse. It is painful doing it this way and you also lose a lot of good DX Prisma gives you but I don't have a choice for now. If I don't find a solution, I will definitely drop Prisma and use the Supabase client.

Right yes, I'm doing the same thing for now, hopefully the prisma team finds a fix soon!

**Comment by janpio** [comment]
We are not aware any problems on our side (except when using the `multiSchema` preview feature, which is tracked at https://github.com/prisma/prisma/issues/17734).

Here is an update from Supabase on their rollout of the fix:

>We've rolled out pg_net 0.7 on the 26th of January - strategy to roll this out to existing projects is still pending.
Existing projects can pause + unpause to update to the latest pg_net version; paid projects unfortunately have to create a support ticket for the time being.

https://github.com/supabase/supabase/issues/11691#issuecomment-1446303327

**Comment by owen-duncan-snobel** [comment]
I am having the same type of problems here and I am not entirely sure what to do

**Comment by janpio** [comment]
Please be more precise with "same type of problems". If you get exactly what was described in the first issue, and have an older Supabase database, my comment https://github.com/prisma/prisma/issues/17160#issuecomment-1447236440 describes exactly the ways available for you to fix this together with the people at Supabase.

**Comment by owen-duncan-snobel** [comment]
I got it working last night, I ended up doing most of what was mentioned across the various threads and comments.

I was having the same problem with supabase + auth and prisma migration

These were the main steps I followed to resolve it.


From the server root run, `npx prisma migrate dev --name init --schema ./mount/prisma/schema.prisma`

#### Recreate the prisma folder and set up the schema.prisma with multiSchema
https://supabase.com/docs/guides/integrations/prisma#resources

#### Create baseline schema
https://www.prisma.io/docs/getting-started/setup-prisma/add-to-existing-project/relational-databases/baseline-your-database-typescript-postgres

Pull in supabase schemas (I remove any of my models in the schema.prisma to start)
```npx prisma db pull --schema ./mount/prisma/schema.prisma```

Update the 2 lines in the migration.sql file, https://github.com/prisma/prisma/issues/17734#issuecomment-1452011006

Follow guide for creating migration baseline
```npx prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script > prisma/migrations/0_init/migration.sql```
```npx prisma migrate resolve --applied 0_init```

Finally run
```npx prisma migrate dev --schema ./prisma/schema.prisma```

**Comment by zachblume** [comment]
It doesn't fail anymore. Upgrade the supabase CLI and pause/unpause your production/hosted supabase servers and this issue was fixed.

Can reproduce success by:
```
brew install supabase
mkdir supabase-bug-fixed
cd supabase-bug-fixed
supabase init
supabase start
echo "a"
psql "postgresql://postgres:postgres@localhost:54322/postgres" -c "CREATE DATABASE foo;"
echo "b"
psql "postgresql://postgres:postgres@localhost:54322/postgres" -c "DROP DATABASE foo;"
echo "c"
```

npx prisma migrate dev works as well, for that underlying reason.

**Comment by levint** [comment]
Just FYI - I encounter the same issue (not using supabase). Tried with both with/without shadow url setting
![image](https://github.com/prisma/prisma/assets/1677825/09d8197d-60cf-4d50-95b0-c6a908968ec3)
^it hangs on above

**Comment by janpio** [comment]
This should not be happening any more, Supabase confirmed this should be resolved unless you are using a super old database. If so, you can update your project.

@levint Please open a new issue and provide all the information the template asks for, then we can hopefully debug this. Thanks.

**Comment by atulord** [comment]
still happening. running initial migrate and hangs after 120 seconds

**Comment by steezeburger** [comment]
Happening to me now again as well. Trying to add something to my Prisma schema and generate a migration but it hangs. Running against local supabase postgres instance
