### ISSUE TITLE
Invalid `prisma/.env` leads to confusing error message

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1739]
This `prisma/.env`:

```
# Environment variables declared in this file are automatically made available to Prisma.
# See the documentation for more detail: https://pris.ly/d/prisma-schema#using-environment-variables

# Prisma supports the native connection string format for PostgreSQL, MySQL and SQLite.
# See the documentation for all the connection string options: https://pris.ly/d/connection-strings

DATABASE_URL="mysql://root:root@localhost:3306/test_2
```

(note the missing `"` at the end)

leads to this confusing error message:

```
C:\Users\Jan\Documents\throwaway\prisma-test-utils-example>npx prisma2 introspect
Introspecting based on datasource defined in prisma\schema.prisma …
Error: Error in connector: Error querying the database: Error querying the database: The specified database url Error parsing database connection string. is invalid
```

**Comment by pantharshit00** [comment]
We need to fix this. Sounds like a easy fix so I am going to candidate this.

**Comment by mavilein** [comment]
Note: The source of this error might be in quaint.

**Comment by matthewmueller** [comment]
I think we should clean this up in Typescript. I don't think Rust needs to know anything about this.

- https://www.npmjs.com/package/dotenv#rules: It looks like they maintain quotes, we should ensure matching quotes before passing it to Rust.
- https://github.com/prisma/prisma/blob/0a829dd357b6a217fc3feae3ae9e29ecac33f779/src/packages/client/src/runtime/getPrismaClient.ts#L387

**Comment by pimeys** [comment]
Do I understand this correctly, that in the case @janpio pointed above, the URL sent to the engines is:

```
"mysql://root:root@localhost:3306/test_2
```

Meaning, the first character is `"`? I tried this with the latest Prisma, and it gives me the following error:

```
Error validating datasource `db`: The URL for datasource `db` must start with the protocol `mysql://`
```

**Comment by pantharshit00** [comment]
Indeed this has been fixed now in the latest version
![Uploading image.png…]()

**Comment by janpio** [comment]
Still not very helpful for me to figure out my `.env` is invalid - as the string I have in there also starts with the substring it complains about ;) 

What does the Engine actually see here? Does it get the `"` submitted as well as @pimeys implied? Maybe we can get rid of the quotes in the standard `.env` file completely?

**Comment by pimeys** [comment]
Now it's catched by the datamodel parser and errored out. So instead of starting with `postgresql://`, it starts with a faulty `"postgresql://` which is not recognized as a supported scheme.

**Comment by iRoachie** [comment]
@pantharshit00 Just encountered this error on a brand new project

```env
DATABASE_URL="mysql://root:password@localhost:3306/controltower"
```

This fails. but works when I remove the quotes

**Comment by pantharshit00** [comment]
@iRoachie Please open a new issue with a minimal reproduction. Then we can look into it properly and fix it :)
