### ISSUE TITLE
Prisma Engine download failure

### ISSUE THREAD

**Issue by salahawk** [prisma/prisma#17422]
### Discussed in https://github.com/prisma/prisma/discussions/17421

<div type='discussions-op-text'>

<sup>Originally posted by **salahawk** January 19, 2023</sup>
I'm now using `PostgreSQL` with `Prisma`.
I have `postgresql@14` running on my machine.
And I 've installed `prisma` in my repo.
But when I rum `npx prisma db push`. it keeps reverting while trying to download Prisma Engine.

Can anyone please help me with this?

![image](https://user-images.githubusercontent.com/99642582/213455941-66465504-3688-4d9b-80cb-898af6cdd71a.png)
![image](https://user-images.githubusercontent.com/99642582/213456283-dbdba999-4073-40a9-9dc5-f793fe816e8b.png)
</div>

**Comment by salahawk** [comment]
I did some research about this and could see so many guys facing the same issue, but could find the exact solution for my case.

I'm using Apple M1 and
- Node: v18.12.1
- Prisma : v4.9.0
- PostgreSQL : v14

**Comment by salahawk** [comment]
![image](https://user-images.githubusercontent.com/99642582/213458145-c5b89e53-0b9a-46e4-94eb-bd5d19a6d4f0.png)

I found something interesting here...
The service is not running, but I can connect to the postgres service either on terminal or using VS extension.

❓❓❓

Do you have any ideas about this?

**Comment by janpio** [comment]
What does "it keeps reverting while trying to download Prisma Engine." mean? The screenshot only shows a download in progress at 26% - no error message or what is happening after.

**Comment by salahawk** [comment]
Yes, that commands is cancelled without any messages (yet download is not completed 😞 )

**Comment by janpio** [comment]
What output do you get on `npx prisma -v`?

**Comment by salahawk** [comment]
I get the same result (just downloading...)
All prisma commands do not work, but only (downloading...) message
![image](https://user-images.githubusercontent.com/99642582/213541587-6ae4e8ae-388e-4724-acf3-327321093e34.png)

**Comment by janpio** [comment]
And with `DEBUG="*"` set in your environment?

**Comment by janpio** [comment]
With `DEBUG=*` you should be getting more useful output that can help us understand what might be going on.

**Comment by salahawk** [comment]
![image](https://user-images.githubusercontent.com/99642582/213542639-4ed5078c-a59c-4d91-a20b-ba5eba3f1502.png)
![image](https://user-images.githubusercontent.com/99642582/213542707-bd80cb6d-48a4-4731-9e7f-114ffe479897.png)

**Comment by salahawk** [comment]
![image](https://user-images.githubusercontent.com/99642582/213542959-902e42c3-7bb7-4451-9cc5-4bd851ff0ca9.png)

**Comment by janpio** [comment]
Does it maybe work with an older Prisma version, e.g. `4.8.1`?

**Comment by salahawk** [comment]
Let me try right now, just a min...

**Comment by salahawk** [comment]
![image](https://user-images.githubusercontent.com/99642582/213543847-4ab7571f-91e1-4715-97f6-eab20006be22.png)
It gives me the same result...

**Comment by janpio** [comment]
Sorry, no idea. Maybe also try another Node version, or Node manager etc.
My best bet would be maybe a anti virus or other security tool that kills the running process.

**Comment by salahawk** [comment]
Yup, thank you for your support, @janpio 
I'll keep trying on my machine with different approaches. 🙇

**Comment by johannchen2021** [comment]
I have the same issue with my VPN probably blocking the download. It initially npm installed prisma successfully, but it failed to upgrade. I tried to remove the node_modules directory and reinstall all latest packages, but no success with prisma. Any workaround? Can Prisma have the engines downloaded while running npm upgrade, instead of having the download engine in a separate step?

**Comment by janpio** [comment]
No, these are operating system and OpenSSL version dependent so we unfortunately can not rely on any existing functionality in Npm right now.

**Comment by wwayne** [comment]
I got the same issue on both my windows(WSL2 - ubuntu 18) and MacBook, this is the error logs I got with DEBUG="*"
```
DEBUG="*" npx prisma format
  prisma:engines binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
  prisma:download file /home/wayne/projects/dapi/backend/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x does not exist and must be downloaded +0ms
  prisma:download file /home/wayne/projects/dapi/backend/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x does not exist and must be downloaded +0ms
  prisma:download Downloading https://binaries.prisma.sh/all_commits/461d6a05159055555eb7dfb337c9fb271cbd4d7e/debian-openssl-1.1.x/migration-engine.gz to /home/wayne/projects/dapi/backend/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x +92ms
> Downloading Prisma engines for Node-API for debian-openssl-1.1.x [                    ] 0%  prisma:download Downloading https://binaries.prisma.sh/all_commits/461d6a05159055555eb7dfb337c9fb271cbd4d7e/debian-openssl-1.1.x/introspection-engine.gz to /home/wayne/projects/dapi/backend/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x +10ms
  prisma:download Downloading https://binaries.prisma.sh/all_commits/461d6a05159055555eb7dfb337c9fb271cbd4d7e/debian-openssl-1.1.x/prisma-fmt.gz to /home/wayne/projects/dapi/backend/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x +1ms
> Downloading Prisma engines for Node-API for debian-openssl-1.1.x [========            ] 41%%
```
I can see the download progress and suddenly it gone without any message, as same as what @salahawk reported

From the log I can see it trying to download the engines and put them into `node_modules/@prisma/engines`
So my current solution is 
1. download the engines from https://binaries.prisma.sh on my browser (find the URL in the logs above)
2. unfolder the file by `gzip -d  migration-engine.gz` for example
3. copy the file into node_modules `mv YOUR_PATH/migration-engine node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x`

**Comment by w1ldy0uth** [comment]
There's an environment variable ```PRISMA_BINARIES_MIRROR```, you may try to set a ```http://binaries.prisma.sh``` value for it, may it'll do the trick.

I had the same issue in docker container and sometimes on my local machine. In my case, the above solution is pretty unstable, because it's not working properly every time

**Comment by w1ldy0uth** [comment]
The solution offered by @wwayne is the most suitable for this bug. I had the same issue while building Docker container. To solve it, I wrote the script that downloads required engines for my platform and moves it into ```node_modules```.

Download script:
```
wget https://binaries.prisma.sh/all_commits/ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5/linux-musl/prisma-fmt.gz
gzip -d prisma-fmt.gz
mv prisma-fmt node_modules/@prisma/engines/prisma-fmt-linux-musl

wget https://binaries.prisma.sh/all_commits/ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5/linux-musl/libquery_engine.so.node.gz
gzip -d libquery_engine.so.node.gz
mv libquery_engine.so.node node_modules/@prisma/engines/libquery_engine-linux-musl.so.node

wget https://binaries.prisma.sh/all_commits/ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5/linux-musl/migration-engine.gz
gzip -d migration-engine.gz
mv migration-engine node_modules/@prisma/engines/migration-engine-linux-musl

wget https://binaries.prisma.sh/all_commits/ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5/linux-musl/introspection-engine.gz
gzip -d introspection-engine.gz
mv introspection-engine node_modules/@prisma/engines/introspection-engine-linux-musl
```

Dockerfile:
```
FROM node:18.13-alpine3.16

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /home/node/app
USER node

COPY --chown=node:node package*.json ./

ENV DEBUG="prisma,prisma:*"

RUN npm install --verbose --ignore-scripts

COPY --chown=node:node ./ .

RUN chmod 777 prisma-engine-script.sh
RUN ./prisma-engine-script.sh

ENV DATABASE_URL "postgresql://postgres:postgres@postgres:5432/postgres?schema=public"

EXPOSE 80

ENTRYPOINT ["npm", "run", "devStart"]
```

However, this solution isn't perfect because I gotta disable all pre/post-install scripts. Moreover, from time to time I get debug message ```prisma:engines file <engine_name> exists but its version is undefined and we expect ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5```.

**P.S.:** URL's from script must be selected according to your platform and openssl verison.

**Comment by jkomyno** [comment]
Hi, I'm also on a MacBook with M1 CPUs, with Node.js 18.12.1, but I can't seem to reproduce this issue.
@wwayne and @w1ldy0uth, are also trying to install Prisma while being connected to a VPN?

**Comment by w1ldy0uth** [comment]
I'm working from corporate network, that is most likely behind the firewall, so it could be the root of the problem.

**Comment by wwayne** [comment]
Hi @jkomyno, thanks for the testing. I agree it is more like a network issue and I don't think it needs any work from your side.

**one question:** is there any env variable we can use for replacing the host url of the Prisma engines?

Thanks : )

**Comment by w1ldy0uth** [comment]
@wwayne, according to the prisma postinstall scripts code (img below), there is an env variable for that. Another question, **which URL** should be placed inside it?


![prisma binaries](https://user-images.githubusercontent.com/30418335/215713567-36d277d1-d34c-4444-89d7-41adcd11d5c5.png)

**Comment by crazydevlegend** [comment]
Hey, guys. for me, it was `node_module` version-related issue.
I downgraded Prisma from `^4.9.0` to `^4.5.0` and it works fine.
I'm not sure why this happens (maybe not cause of network issue) - I'd love to have the right reason from the development/maintenance team.

**Comment by salahawk** [comment]
Wow, great. thanks guys @crazydevlegend  @wwayne @w1ldy0uth 
Your approaches all helped me resolve my issue.

- either downloading Prisma engine separately
- or downgrading Prisma version

Thanks for your support
🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️

**Comment by bluiska** [comment]
Has this been resolved? I can't use any version above 4.5.0 as that will get stuck on the downloading and just exit the command like described above.

**Comment by crypmario** [comment]
> Has this been resolved? I can't use any version above 4.5.0 as that will get stuck on the downloading and just exit the command like described above.

yes, v4.5.0+ doesn't work on my end... that's why i use 4.5.0...
does this help you?

**Comment by janpio** [comment]
We are not aware of any problems. Please open a new issue or discussion and provide all the information the template asks for so we can look into this. Thanks.

**Comment by w1ldy0uth** [comment]
Yeah, as for my problem, it has resolved with time without any other involvements. We removed script for downloading prisma engines as well. Preinstall hooks are now working correctly for each build stage after updating prisma to v.4.10.0

**Comment by hengkydev** [comment]
So I tried to all of the solutions above and its not working
I resolve this by disable ip v6 preferences somehow when try to download binary it keep requesting to ip v6 until wget choose to use ip v4 and its worked
![image](https://github.com/prisma/prisma/assets/17931528/75464cd4-d63a-41d3-b5bb-eae5839f5d5e)

so I decided to disable my ip v4 preference on my linux machine on 
1. `sudo nano /etc/gai.conf`
2. uncomment `precedence ::ffff:0:0/96  100` 
3. try to generate prisma again and its work 

and now is downloading perfectly ✨

**Comment by ChristianVaughn** [comment]
Why was this marked as closed? Seems the issue is still happening. Im on prisma 5.7.0, and this error seems to be happening. 

```
user$ bunx prisma migrate dev --name test
  prisma:engines  binaries to download libquery-engine, schema-engine +0ms
  prisma:get-platform  Found distro info:
{
  "targetDistro": "debian",
  "familyDistro": "debian",
  "originalDistro": "ubuntu"
} +0ms
  prisma:get-platform  Trying platform-specific paths for "debian" (and "ubuntu") +0ms
  prisma:get-platform  Found libssl.so file using platform-specific paths: libssl.so.3 +11ms
  prisma:get-platform  The parsed libssl version is: 3.0.x +0ms
  prisma:get-platform  Found distro info:
{
  "targetDistro": "debian",
  "familyDistro": "debian",
  "originalDistro": "ubuntu"
} +1ms
  prisma:get-platform  Trying platform-specific paths for "debian" (and "ubuntu") +0ms
  prisma:get-platform  Found libssl.so file using platform-specific paths: libssl.so.3 +0ms
  prisma:get-platform  The parsed libssl version is: 3.0.x +0ms
  prisma:fetch-engine:download  file /mnt/c/Users/micro/Documents/GitHub/unggoy-api/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node does not exist and must be downloaded +0ms
  prisma:fetch-engine:download  file /mnt/c/Users/micro/Documents/GitHub/unggoy-api/node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x does not exist and must be downloaded +0ms
  prisma:fetch-engine:download  https://binaries.prisma.sh/all_commits/79fb5193cf0a8fdbef536e4b4a159cad677ab1b9/debian-openssl-3.0.x/libquery_engine.so.node.gz will be downloaded to /mnt/c/Users/micro/Documents/GitHub/unggoy-api/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node +0ms
  prisma:fetch-engine:download  https://binaries.prisma.sh/all_commits/79fb5193cf0a8fdbef536e4b4a159cad677ab1b9/debian-openssl-3.0.x/schema-engine.gz will be downloaded to /mnt/c/Users/micro/Documents/GitHub/unggoy-api/node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x +2ms
  prisma:fetch-engine:download  Downloading https://binaries.prisma.sh/all_commits/79fb5193cf0a8fdbef536e4b4a159cad677ab1b9/debian-openssl-3.0.x/libquery_engine.so.node.gz to /mnt/c/Users/micro/Documents/GitHub/unggoy-api/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node ... +2ms
> Downloading Prisma engines for Node-API for debian-openssl-3.0.x [                    ] 0%  prisma:fetch-engine:download  Downloading https://binaries.prisma.sh/all_commits/79fb5193cf0a8fdbef536e4b4a159cad677ab1b9/debian-openssl-3.0.x/schema-engine.gz to /mnt/c/Users/micro/Documents/GitHub/unggoy-api/node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x ... +4ms
> Downloading Prisma engines for Node-API for debian-openssl-3.0.x [============        ] 62%user$ echo $?
0
```
