### ISSUE TITLE
Getting error on deeper includes

### ISSUE THREAD

**Issue by malekjaroslav** [prisma/prisma#1785]
I am getting this error on Preview 23 that worked on Preview 21
Error:
```
Expected at most 1 item for 'timetable', got 2
```

Query:
```
  const data = await prisma.passenger.findMany({
    include: {
      booking: {
        include: {
          timetable: true
        }
      }
    }
  });
```

**Comment by luhagel** [comment]
Might help while reproducing, this error and another one complaining about a missing FROM caause seem to happen once the includes get nested. So
```ts
...,
include: { posts: true },
```
works fine,, whereas 
```ts
...,
include: { posts: { include: { tags: true } } } },
```
will crash reliably

**Comment by narciero** [comment]
`+1` I am also seeing the `missing FROM-clause` error when trying to include a field that is part of a M-N relation. It was working fine in preview022

**Comment by pantharshit00** [comment]
@malekjaroslav I was unable to reproduce this. I used Preview 24 Maybe it is reproducible with the data that you have in your database. Can share a SQL dump of your database? If you like we can sign an NDA if you are not comfortable sharing it here.

If someone else can provide a more minimal reproduction, it would be quite helpful.

**Comment by malekjaroslav** [comment]
@pantharshit00 Here is the dump. It still happens even on Preview 24. After you import the tables, call this query: [dump-issue-1785.gz](https://github.com/prisma/prisma2/files/4332362/dump-issue-1785.gz)

```
 const passenger = await prisma.passenger.findMany({
            where: {
                booking: {
                    bookingStatusLogs: {
                        some: {
                            status: "CONFIRMED"
                        }
                    },
                    timetable: {
                        id: "ck7r8b65w0023llb31i581ncg"
                    }
                }
            },
            include: {
                booking: {
                    include: {
                        timetable: true
                    }
                },
                passengerStatusLogs: {
                    orderBy: {
                        createdAt: "desc"
                    },
                    first: 1
                }
            }
        })
```

**Comment by RussMax783** [comment]
I'm having the issue too that came up after an upgrade, and was able to narrow down at least what is causing this issue. The stripped down version of my relational model:

```
model TimeEntry {
  id            String     @default(cuid()) @id
  trip          Trip
  startTime     DateTime
  updatedAt     DateTime   @updatedAt
  createdAt     DateTime   @default(now())
  ...Other Fields
}

model Trip {
  id              String     @default(cuid()) @id
  route           Route
  name            String
  ...Other Fields
}

model Route {
  id           String       @default(cuid()) @id
  trips        Trip[]
  name         String
  ...Other Fields
}
```

A Route can have a bunch of Trips, where in this case a truck driver creates a time Entry that links to a Trip which would have info such as where they started, ended, times, etc. The query I make is: 

```
const data = await db.timeEntry.findMany({
  where: {
    // some where clause
  },
  include: {
    trip: {
      include: {
        route: true,
      },
    },
  },
})
```

The problem lies in if I get multiple TimeEntries that have the same trip. It will error when it then tries to get the routes because it is the same Route. So if i just `{include: { trip: true} }` all is well. Or if I happen to call a data set where the TimeEntires are all different Trips, it works. (which would be why an empty data set would be successful) Now i'm not sure if the `createdAt` or `updatedAt` or `startTime` fields come into play. I was able to narrow down the query by filtering and shrinking the startTime interval until i got a small enough dataset to visually parse through and see what was going on. 

I hope thats helpful and not super confusing. Its hard to explain just over text. 

happy to clarify anything if needed.

**Comment by malekjaroslav** [comment]
@pantharshit00 Do you have some update on this? It is quite a big issue. Thanks!

**Comment by pimeys** [comment]
Can confirm this breaks.

**Comment by pantharshit00** [comment]
Smaller client call to reproduce this:
```
  const data = await prisma.passenger.findMany({
    include: {
      booking: {
        include: {
          timetable: true
        }
      }
    }
  });


```

Data used from the dump above

**Comment by tomitrescak** [comment]
> `+1` I am also seeing the `missing FROM-clause` error when trying to include a field that is part of a M-N relation. It was working fine in preview022

Same here, anything after 21 breaks.

**Comment by tomitrescak** [comment]
Guys, have you found any workarounds? The new release from today has so many new cool things I could use but I’m already stuck at v21 with 5 versions behind. Thanks!

**Comment by malekjaroslav** [comment]
@tomitrescak There is no good workaround other than making multiple queries or using raw method.

**Comment by dpetrick** [comment]
Latest alpha should contain a fix for the issue. Please verify that it works for you.

**Comment by c316** [comment]
I just tried ```2.0.0-alpha.1013``` and I'm still getting this same error when running Prisma studio. 

Here is what I get

```
Error in request:  {
  telemetry: true,
  message: '\n' +
    'Invalid `prisma.activity.findMany()` invocation:\n' +
    '\n' +
    "Expected at most 1 item for 'branch', got 58",
  stack: 'Error: \n' +
    'Invalid `prisma.activity.findMany()` invocation:\n' +
    '\n' +
    "Expected at most 1 item for 'branch', got 58\n" +
    '    at PrismaClientFetcher.request (/Users/josh/.cache/prisma/studio/Users-josh-Dev-prisma-examples-javascript-rest-nextjs/runtime/index.js:1:51485)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:93:5)',
  isPanic: undefined,
  code: undefined
} {
  query: 'prisma.activity.findMany({\n' +
    '  first: 100,\n' +
    '  select: {\n' +
    '    branch: true,\n' +
    '  }\n' +
    '})'
}
```

Here is the relevant schema section
```
model Activity {
  branch Branch? @relation("ActivityBranch", references: [id])
  id String @default(cuid()) @id
}
model Branch {
  activity Activity[] @relation("ActivityBranch")
  id String @default(cuid()) @id
}
```

**Comment by pimeys** [comment]
You miss the scalar field of the relation and the field definition. The validator merged today will not pass your datamodel anymore.

**Comment by c316** [comment]
Ok, I made that change, but now ```prisma migrate``` wants to drop tables that have data. I'm just starting to try to migrate from Prisma 1.

**Comment by pimeys** [comment]
Maybe introspect the database with the beta1 or the latest alpha. Migrate is still experimental.

**Comment by c316** [comment]
@pimeys Thank you.  That got me a bit further, I will now have to wait for this issue before proceeding. 
https://github.com/prisma/prisma/issues/1996

**Comment by RussMax783** [comment]
FWIW I was able to get up and running with 2.0.0-beta.1 and still have the same issue. `Expected at most 1 item for 'route', got 11`

**Comment by malekjaroslav** [comment]
> FWIW I was able to get up and running with 2.0.0-beta.1 and still have the same issue. `Expected at most 1 item for 'route', got 11`

@RussMax783 the fix was merged in alpha after beta1 release, not in the beta release

**Comment by RussMax783** [comment]
Ah, Should have checked that. I just installed @latest. Anyways, installed the alpha and ran a couple queries that I knew would break and they now work!  Nice work!!

**Comment by homerjam** [comment]
I think I still have this issue using beta.2. Was the fix included?

```js
    let user = await ctx.prisma.auth0User
      .findOne({
        where: { auth0Id: auth0Id },
      })
      .user();
```

```graphql
model User {
  id         String      @default(cuid()) @id
  auth0Users Auth0User[] @relation(references: [id])
  email      String      @unique
  username   String      @unique
  name       String
}

model Auth0User {
  id      String @default(cuid()) @id
  auth0Id String @unique
  user    User   @relation(fields: [userId], references: [id])
  userId  String @map("user")
}
```

Problem seems to be with the secondary/sub query:

```sql
SELECT "public"."User"."id", "public"."User"."email", "public"."User"."username", "public"."User"."name" FROM "public"."User" WHERE () IN (($1)) OFFSET $2
```

Specifically `WHERE ()` should have a field I think?

**Comment by pantharshit00** [comment]
You datamodel is invalid, `auth0Users` field should not provide any relation sirective as it is virtual. Here is the correct model:
```
model User {
  id         String      @default(cuid()) @id
  auth0Users Auth0User[]
  email      String      @unique
  username   String      @unique
  name       String
}

model Auth0User {
  id      String @default(cuid()) @id
  auth0Id String @unique
  user    User   @relation(fields: [userId], references: [id])
  userId  String @map("user")
}
```

Current alpha will give you a validation error for this.
