### ISSUE TITLE
Prisma Memory Leak when using in NestJS app, reported by Jest

### ISSUE THREAD

**Issue by adrian-goe** [prisma/prisma#17925]
### Bug description

In our (closed source) project, we added a lot of test for a new feature. That resulted in memory problems in our ci.

We found, that Prisma is might be one of the problems.
I created a minimal reproduction https://github.com/adrian-goe/prisma-nestjs-memory-leak-repoduction

There is one test without using prisma [app.controller.spec.ts](https://github.com/adrian-goe/prisma-nestjs-memory-leak-repoduction/blob/2912484c9c9cce9dfd8c916be5975bfe1fa204c6/apps/prisma-memeory-leak/src/app/app.controller.spec.ts)
and one using prisma [app-prisma.controller.spec.ts](https://github.com/adrian-goe/prisma-nestjs-memory-leak-repoduction/blob/2912484c9c9cce9dfd8c916be5975bfe1fa204c6/apps/prisma-memeory-leak/src/app/app-prisma.controller.spec.ts)

running both test with `node --expose-gc` and `jest --detectLeaks` results in jest finding memory leaks in the test with prisma.

It might be possible, that this leaks also happens while running the application, but I didn't test that.

It could be possible, that this is a nestJs problem as well, but we ware only be able to reproduce this with Prisma, but no other dependency or module.

### How to reproduce

https://github.com/adrian-goe/prisma-nestjs-memory-leak-repoduction

### Prisma information

see https://github.com/adrian-goe/prisma-nestjs-memory-leak-repoduction

### Environment & setup

- OS: [macOS, Windows, Debian] might be more
- Database: [PostgreSQL] only tested with postgres
- Node.js version: v16.18.0

### Prisma Version

```
prisma                  : 4.10.1
@prisma/client          : 4.10.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine aead147aa326ccb985dcfed5b065b4fdabd44b19 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli aead147aa326ccb985dcfed5b065b4fdabd44b19 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.10.1-1.80b351cc7c06d352abe81be19b8a89e9c6b7c110
Default Engines Hash    : aead147aa326ccb985dcfed5b065b4fdabd44b19
Studio                  : 0.481.0
```

In our internal project, this was also an issue with Prisma 4.1.1

**Comment by SevInf** [comment]
Hi @adrian-goe. One problem I find with you reproduction - I don't see `prisma.$disconnect` call. This is necessary for prisma to clean up all associated resources. Ensure it is gets called after every test suite where prisma is used.  

Second problem: when node run with `--expose-gc` Jest has a known [memory leak](https://github.com/facebook/jest/issues/7874). This is not prisma-specific problem. Couple of workarounds are suggested in that thread. Most reliable seems to be adding `--no-compilation-cache` option to` node`.

**Comment by adrian-goe** [comment]
@SevInf oh i forgot the app.close call in the test. I will add that alter. But in our production code we have this in every that case.

The jest problem you mentioned, wouldn't this also affect the other test as well?

**Comment by adrian-goe** [comment]
@SevInf also, i have a prisma Service class. This is provided in the module that extends the OnApplicationShutdown hook from nestjs, so it should correctly shut down, when nestJs shuts down.
Might not be the case in my reproductio, since i forgot the explicit app.close() call.

**Comment by SevInf** [comment]
@adrian-goe `PrismaService` class in your reproduction does not call `$disconnect` either. I am not NestJS expert by any means, but I am pretty sure it does not know anything about Prisma and won't call it automatically for you. If that's not the case in your production app and `$disconnect` is called there, please, update the reproduction to reflect that. Also, try `--no-compilation-cache` flag to test for Jest leak as well. I, unfortunately, can't tell if it should happen with the other test. We've seen quite a dramatic memory usage spike in our own test suite when `--expose-gc` is used, however. We could not reproduce it outside of Jest sandbox so we have all reason to believe that the issue I've linked is the reason.

**Comment by adrian-goe** [comment]
@SevInf I added the `--no-compilation-cache` flag, the issue remains.

I also added the `app.close()`in the after all block. Also, I added console.logs to the `onApplicationShutdown` method, in my prisma service. This method is called. Since my service `extends` the PrismaClient class, the `await this.$disconnect();` should disconnect prisma correctly, as you mentioned.

**Comment by janpio** [comment]
So I can confirm that the reproduction outputs the following message:

```
gitpod /workspace/prisma-nestjs-memory-leak-repoduction (main) $ npm run test:leak

> prisma-memory-leak@0.0.0 test:leak
> node --expose-gc ./node_modules/.bin/jest --config=apps/prisma-memeory-leak/jest.config.ts --verbose --no-compilation-cache --detectLeaks --runTestsByPath ./apps/prisma-memeory-leak/src/app/app-prisma.controller.spec.ts

  console.log
    before prisma close

      at Proxy.<anonymous> (src/app/prisma/prisma.service.ts:6:13)

  console.log
    after prisma close

      at Proxy.<anonymous> (src/app/prisma/prisma.service.ts:8:13)

 FAIL   prisma-memeory-leak  apps/prisma-memeory-leak/src/app/app-prisma.controller.spec.ts
  ● Test suite failed to run

    EXPERIMENTAL FEATURE!
    Your test suite is leaking memory. Please ensure all references are cleaned.

    There is a number of things that can leak memory:
      - Async operations that have not finished (e.g. fs.readFile).
      - Timers not properly mocked (e.g. setInterval, setTimeout).
      - Keeping references to the global scope.

      at onResult (../../node_modules/@jest/core/build/TestScheduler.js:190:18)
      at ../../node_modules/@jest/core/build/TestScheduler.js:316:17
      at ../../node_modules/emittery/index.js:260:13
          at Array.map (<anonymous>)
      at Emittery.emit (../../node_modules/emittery/index.js:258:23)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.355 s
Ran all test suites within paths "./apps/prisma-memeory-leak/src/app/app-prisma.controller.spec.ts".
Segmentation fault
```

I also sent a PR to make the reproduction actually work out of the box.

**Comment by Durisvk** [comment]
Hey guys I'm currently debugging a memory-leak on our production app (which is not using NestJS but a similar approach of extending `PrismaClient` + `typedi` package).

I've noticed from your reproduction that if I print out `heapUsed` before the query and after the query on the latest version of prisma it's really leaking by fraction of a megabyte.

However if I downgrade to prisma@3.0.2 the memory goes down after the query (the test still fails because there might be some open handles or some other stuff).

<img width="472" alt="image" src="https://user-images.githubusercontent.com/8467003/234337904-1daafdaf-8304-4d0d-b100-3b2a06236033.png">


To reproduce follow the steps in [README.md](https://github.com/adrian-goe/prisma-nestjs-memory-leak-repoduction/blob/main/README.md) and adjust the file `apps/prisma-memeory-leak/src/app/app-prisma.controller.spec.ts` to the following:

```ts
import { Test, TestingModule } from '@nestjs/testing';
import { AppController } from './app.controller';
import { PrismaModule } from './prisma/prisma.module';
import { AppPrismaController } from './app-prisma.controller';
import { AppPrismaService } from './app-prisma.service';

describe('AppPrismaController', () => {
  let app: TestingModule;

  beforeAll(async () => {
    app = await Test.createTestingModule({
      imports: [PrismaModule],
      controllers: [AppPrismaController],
      providers: [AppPrismaService],
    }).compile();
  });

  afterAll(async () => {
    await app.close();
  });
  describe('getData', () => {
    it('should return "Welcome to prisma-memeory-leak!"', async () => {
      const appController = app.get<AppPrismaController>(AppPrismaController);

      console.log(
        `before querying ${
          Math.round((process.memoryUsage().heapUsed / 1024 / 1024) * 100) / 100
        } MB`
      );
      expect(await appController.getData()).toEqual({
        message: 'Welcome to prisma-memeory-leak!',
      });

      console.log(
        `after querying ${
          Math.round((process.memoryUsage().heapUsed / 1024 / 1024) * 100) / 100
        } MB`
      );
    });
  });
});
```

Then run the following commands:

```
npm i --save prisma@3.1.1 @prisma/client@3.1.1
npx prisma generate
```

see the memory increase:
```
before querying 203.91 MB
after querying 206.72 MB
```


then downgrade to prisma@3.0.2:
```
npm i --save prisma@3.0.2 @prisma/client@3.0.2
npx prisma generate
```

and run the tests again:
```
before querying 212.83 MB
after querying 202.25 MB
```

The changelog between 3.0.2 and 3.1.1 versions can be found here: https://github.com/prisma/prisma/releases/tag/3.1.1

**Comment by Durisvk** [comment]
> So I can confirm that the reproduction outputs the following message:
> 
> ```
> gitpod /workspace/prisma-nestjs-memory-leak-repoduction (main) $ npm run test:leak
> 
> > prisma-memory-leak@0.0.0 test:leak
> > node --expose-gc ./node_modules/.bin/jest --config=apps/prisma-memeory-leak/jest.config.ts --verbose --no-compilation-cache --detectLeaks --runTestsByPath ./apps/prisma-memeory-leak/src/app/app-prisma.controller.spec.ts
> 
>   console.log
>     before prisma close
> 
>       at Proxy.<anonymous> (src/app/prisma/prisma.service.ts:6:13)
> 
>   console.log
>     after prisma close
> 
>       at Proxy.<anonymous> (src/app/prisma/prisma.service.ts:8:13)
> 
>  FAIL   prisma-memeory-leak  apps/prisma-memeory-leak/src/app/app-prisma.controller.spec.ts
>   ● Test suite failed to run
> 
>     EXPERIMENTAL FEATURE!
>     Your test suite is leaking memory. Please ensure all references are cleaned.
> 
>     There is a number of things that can leak memory:
>       - Async operations that have not finished (e.g. fs.readFile).
>       - Timers not properly mocked (e.g. setInterval, setTimeout).
>       - Keeping references to the global scope.
> 
>       at onResult (../../node_modules/@jest/core/build/TestScheduler.js:190:18)
>       at ../../node_modules/@jest/core/build/TestScheduler.js:316:17
>       at ../../node_modules/emittery/index.js:260:13
>           at Array.map (<anonymous>)
>       at Emittery.emit (../../node_modules/emittery/index.js:258:23)
> 
> Test Suites: 1 failed, 1 total
> Tests:       0 total
> Snapshots:   0 total
> Time:        2.355 s
> Ran all test suites within paths "./apps/prisma-memeory-leak/src/app/app-prisma.controller.spec.ts".
> Segmentation fault
> ```
> 
> I also sent a PR to make the reproduction actually work out of the box: [adrian-goe/prisma-nestjs-memory-leak-repoduction#1](https://github.com/adrian-goe/prisma-nestjs-memory-leak-repoduction/pull/1)
> 
> Note: Even though this is now on `confirmed`, it does not mean there has to be a problem at Prisma. We will keep investigating that.

I've created a new issue where there's a reproduction with no other dependency but Prisma.
- https://github.com/prisma/prisma/issues/18934

Technically I cannot call it a memory leak but I am for sure calling it a memory mismanagement.

My feeling is that the following commit is causing it: https://github.com/prisma/prisma/commit/f395abad8eb85739a1df35071caa9e5050993696 but that's just a feeling since I know the prisma infrastructure is super complex and I'm not a Rust developer.

I hope it helps in your investigation.

**Comment by masterkain** [comment]
I kinda believe this might be related to the effects cascade I'm observing in https://github.com/vercel/next.js/issues/49623

**Comment by xlmnxp** [comment]
we face same issue with Prisma and nestjs, even calling prisma.collection.delete catch memory leak and invalid pointers etc...

**Comment by xlmnxp** [comment]
@adrian-goe I notice both of us use arm64
Is it related to that bug?

**Comment by xlmnxp** [comment]
> @xlmnxp since this is also a problem in our CI, that don't use arm64, it is probably not related to this.

Hmm, we have same issue,
it was working fine, but I don't know what break

**Comment by xlmnxp** [comment]
@adrian-goe I find something wired that if the issue happen once, then I cannot start nestjs and got one of the following

```
malloc(): unaligned tcache chunk detected
malloc(): unaligned fastbin chunk detected
malloc_consolidate(): unaligned fastbin chunk detected
free(): double free detected in tcache 2
```

**Comment by xlmnxp** [comment]
I think related to https://github.com/prisma/prisma/issues/18510

**Comment by Nickersoft** [comment]
Has anyone come across a workaround for this? I'm noticing a very slow memory leak in my production server that causes a crash after 1-2 weeks. In my local debugging Prisma seems to come up pretty often in my heap dumps.

**Comment by eJayYoung** [comment]
Same problem
We're also seeing a slow rss increase in a long days by prometheus, the maximum difference between **Shallow Size**and **Retained Size** in heapdump snapshot point to `node_modules/@prisma/client/runtime/library.js`

and I found there is a WeakRef in [LibraryEngine.ts](https://github.com/prisma/prisma/blob/99a96e884e3cfc799583e1bc7487f79753355d62/packages/client/src/runtime/core/engines/library/LibraryEngine.ts#L242)

I'm not sure if it is this WeakRef cause the memory leak.

**Comment by livthomas** [comment]
I can confirm there is some memory leak in the Prisma query engine. It affects all our apps which use Prisma and make a lot of DB calls regardless of whether they are read-only apps or the ones fetching external data and storing it to the DB.

I thought Prisma 5 might solve this problem but after I updated the dependencies today, I can see the issue is still there.

The memory used by our apps slowly grows day-by-day until they eventually run out of memory and their containers are restarted.

Below I show some examples what this problem looks like in both library and binary mode. In these cases, I simply hit some of our API endpoints that make really heavy DB calls so I can reproduce the issue more quickly.

# Library

When we use `library` engine type, the issue is only visible as the difference between `rss` memory usage.

You can clearly see there's no memory leak in our app or in Prisma client because the heap size remains stable.

### Before Heavy Load

```json
{
  "rss": 336392192,
  "heapTotal": 33280000,
  "heapUsed": 27778056,
  "external": 17858813,
  "arrayBuffers": 51654
}
```

### After Heavy Load

```json
{
  "rss": 571432960,
  "heapTotal": 30396416,
  "heapUsed": 26941400,
  "external": 17875669,
  "arrayBuffers": 39294
}
```

# Binary

When we use `binary` engine type, it is clearly visible that the query engine uses a lot of memory.

Used memory is shown as percentage below. But it's easy to calculate how much memory those processes use since the machine where the app runs has 1GB RAM.

I only made a single set of heavy DB calls. But I can repeat this over and over again with the very same calls and I always end up with more and more memory used by the query engine.

## After Start

After I start the application, the Node.js memory usage looks like this:

```json
{
  "rss": 154386432,
  "heapTotal": 30298112,
  "heapUsed": 26703576,
  "external": 18142813,
  "arrayBuffers": 56092
}
```

...and relevant system processes like this:

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
apps        76  7.9 15.3 21784396 161136 ?     Sl   09:03   0:05 /layers/heroku_nodejs-engine/nodejs/bin/node --inspect=127.0.0.1:9221 --heapsnapshot-signal=SIGUSR2 build/server.js
apps        88  0.6  4.7 795948 49700 ?        Sl   09:03   0:00 /workspace/node_modules/.prisma/client/query-engine-debian-openssl-1.0.x --enable-raw-queries --enable-metrics --enable-open-telemetry --port 0 --engine-protocol json
```

## After Heat Up Period

I let the application run for a while but there's nothing going on except for regular health checks (which also connect to the DB).

```json
{
  "rss": 158240768,
  "heapTotal": 31870976,
  "heapUsed": 28238904,
  "external": 18340681,
  "arrayBuffers": 65628
}
```

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
apps        76  4.1 14.7 21783536 154532 ?     Sl   09:03   0:40 /layers/heroku_nodejs-engine/nodejs/bin/node --inspect=127.0.0.1:9221 --heapsnapshot-signal=SIGUSR2 build/server.js
apps        88  2.4 14.5 798000 152492 ?       Sl   09:03   0:22 /workspace/node_modules/.prisma/client/query-engine-debian-openssl-1.0.x --enable-raw-queries --enable-metrics --enable-open-telemetry --port 0 --engine-protocol json
```

## After Heavy Load

```json
{
  "rss": 207368192,
  "heapTotal": 80367616,
  "heapUsed": 69357296,
  "external": 18272118,
  "arrayBuffers": 63632
}
```

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
apps        76  5.3 19.3 21823728 202508 ?     Sl   09:03   1:03 /layers/heroku_nodejs-engine/nodejs/bin/node --inspect=127.0.0.1:9221 --heapsnapshot-signal=SIGUSR2 build/server.js
apps        88  3.2 29.6 863536 310560 ?       Sl   09:03   0:37 /workspace/node_modules/.prisma/client/query-engine-debian-openssl-1.0.x --enable-raw-queries --enable-metrics --enable-open-telemetry --port 0 --engine-protocol json
```

## After Cool Down Period

When I wait for a while after the heavy DB calls, I can see that GC kicks in and cleans up the heap. However, the memory used by the Prisma query engine doesn't go down.

```json
{
  "rss": 158236672,
  "heapTotal": 32133120,
  "heapUsed": 27977328,
  "external": 18275459,
  "arrayBuffers": 52850
}
```

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
apps        76  5.0 14.7 21783792 154528 ?     Sl   09:03   1:05 /layers/heroku_nodejs-engine/nodejs/bin/node --inspect=127.0.0.1:9221 --heapsnapshot-signal=SIGUSR2 build/server.js
apps        88  2.9 29.6 863536 310560 ?       Sl   09:03   0:37 /workspace/node_modules/.prisma/client/query-engine-debian-openssl-1.0.x --enable-raw-queries --enable-metrics --enable-open-telemetry --port 0 --engine-protocol json
```

**Comment by calvinl** [comment]
This issue appears to be pervasive (and likely related to #17171). I am seeing both in my tests, as well as in production. I have to restart my containers every 1-2 days as it grows consistently over time. 

Is there any way to flag this bug as a priority? Seems like a pretty big problem.

**Comment by benweissmann** [comment]
We are experiencing this issue in production as well. For now, we're having to restart our containers nightly to avoid OOM errors. Similar to other users, we are able to consistently reproduce this by running queries and observe that the NodeJS heap size is stable while the process's overall memory is increasing as we run queries.

**Comment by benweissmann** [comment]
It's worth noting that the existing memory leak tests will not detect this issue because they're examining only the NodeJS heap size; it's likely that the existing test suite could be adjusted to catch this class of issue by using `process.memoryUsage().rss` to capture total memory usage, rather than `heapUsed` here: https://github.com/prisma/prisma/blob/main/packages/client/tests/memory/_utils/createMemoryTest.ts#L63

**Comment by livthomas** [comment]
Just to give you an idea what this memory leak look like in another app when we keep it running for a day:
```
apps        83  6.8 19.6 21958328 205820 ?     Sl   Jul29 142:00 /layers/heroku_nodejs-engine/nodejs/bin/node build/worker.js
apps        94 10.7 51.3 1267276 538512 ?      Sl   Jul29 223:34 /workspace/node_modules/.prisma/client/query-engine-debian-openssl-1.0.x --enable-raw-queries --enable-metrics --enable-open-telemetry --port 0 --engine-protocol json
```
This app is a job executor that works all the time without any break since there are always more jobs than it can process. And the Node.js app itself still consumes just 196 MB of RAM while Prisma query engine consumes 513 MB which is constantly growing until the container eventually runs out of memory and is restarted.

**Comment by tuwibu** [comment]
Looks like the problem is in version >=4.8.2. Try downgrade prisma@4.8.1

**Comment by whalesync-ryder** [comment]
This issue is keeping us from upgrading past 4.8, since our containers die after around a day. There's lots of features in 5.0 i'm looking on with envy until this gets resolved.

**Comment by pocesar** [comment]
same here, it's a slow memory leak, and we're restarting the containers after it crosses the 95% memory usage. it grows regardless of how much traffic the server is getting

**Comment by rickitan** [comment]
Noticing the same on my app. It's a Express + Next.js App. Memory slowly continues increasing.

Today I upgrade from  version `4` to `5.2.0` hoping it's fixed. But after finding this thread I'm not keeping my hopes up.

**Comment by janpio** [comment]
Ok, this issue is a mess with dozens of _possibly_ completely unrelated reports - and only 1 actual reproduction that can help us understand what is going on, from @adrian-goe 🙇. I'll try to untangle that a bit.

---

@livthomas, or anyone else who is using `engineType = "binary"`, please open a new issue. Your problem is not related to what the normal Prisma Query Engine might be experiencing - so it does not make sense to mix your problem with this one. I will hide your messages here to clean up the noise a bit, but please do open that new issue and share your information in there - optimally with a reproduction. We definitely want to look into that as well, but here is not the right place. Thanks.

---

For _everyone_ posting here, it would be amazing if you could edit your message and add the answers to the following questions: 
You are using the normal library engine, correct?
What Node version?
What OS?
What database and version? 
Can you reproduce the problem locally? 
Is your app running any special queries? `Promise.all`, or any other parallelism?

---

@rickitan Can you help us by providing a reproduction in any way that we can run? What "memory" exactly is increasing? RSS usage? While the app is doing what exactly?

@pocesar Can you isolate the problem into a reproduction? Sounds like you have a pretty good understanding of your situation, so that would be most helpful.

@whalesync-ryder Any other information you can provide?

@benweissmann https://github.com/prisma/prisma/pull/20861

@xlmnxp Can you provide any information that helps us reproduce and understand the problem? (We never backport any fixes, and I do not understand what most of your other messages mean. Please elaborate.)

@calvinl What helps us prioritize issues, are good reproductions and investigations. We need to be able to _see_ the problem, in as many variants as possible, to hopefully be able to to figure out what is going on. Most probably many of these reports are unrelated and caused by different things - but with only 1 reproduction we can not connect the dots.

@eJayYoung Can you elaborate what you mean with " the maximum difference between Shallow Size and Retained Size in heapdump snapshot point to node_modules/@prisma/client/runtime/library.js"?

@RisbergAdam Could you help us pinpoint it by testing these versions in between 4.3.1 and 4.12.0 to figure out where exactly it started? I suggest starting with 4.8.0, and then again in the middle depending if it is affected or not - that should lead to a result in ~3 or 4 tries. That would be super helpful. Thanks!

@Nickersoft Any additional information you can provide that helps us understand this?

@Durisvk Your observation turned out to be normal GC behavior, correct? So should I hide your messages here as they were actually not about the same problem?

**Comment by Geczy** [comment]
my production server crashes every 2 days due to a memory leak, goes over 95% then poof. i have to restart it nightly

since doing some new commits, it now shoots up from ~350mb-400mb before a restart in 2 days, to ~650mb in just a few hours (master branch) !

i can reproduce this locally every time using my unit tests, you can too if you clone & run the prisma seeder https://github.com/dotabod/backend

this is the package that crashes https://github.com/dotabod/backend/blob/master/packages/Dockerfile.dota

here's the docker compose https://github.com/dotabod/backend/blob/master/docker-compose.yml#L65

here's the prisma https://github.com/dotabod/backend/blob/master/packages/prisma/src/postgres.prisma

![CleanShot 2023-08-31 at 16 59 22@2x](https://github.com/prisma/prisma/assets/1036968/42c113f6-62e9-44ed-a0a6-4250e4f271f0)

**Comment by tchroma** [comment]
Our team ran into a similar issue with our NestJS application. 
The memory leak is very slow (about 800MB in 48 hours). 
Approximate server load information: 
- 2.5K inserts per second
- 22K selects per second 
- 2.2K deletions per second
- 280 updates per second

We tried several options to localize the memory leak. Here is the result we got. When running the application with `engineType "library"` nodeJS process keep on consume memory. When using `engineType "binary"` nodeJS application uses memory correctly but the prisma-query-engine process continues to consume memory. 
When comparing 2 different launch methods, `engineType "library"` leaks about twice as fast compared to `engineType "binary"`.
We are using prisma version 5.2.0, node v16.18.1.

OS info: Linux 5.4.179-1.el8.elrepo.x86_64 #1 SMP Thu Feb 10 10:14:12 EST 2022 x86_64 x86_64 x86_64 GNU/Linux

Memory usage:
![htop](https://github.com/prisma/prisma/assets/83174757/641d2b8c-234b-4b87-bb40-7025e5923fc9)

Prisma info:
![ver](https://github.com/prisma/prisma/assets/83174757/021d68a8-9935-407e-8427-a43b96ad759c)

**Comment by elie222** [comment]
Facing same issues on Next.js.

**Comment by tuwibu** [comment]
serious memory leak, i used prisma 4.11.0 (memory used 20GB)
downgrade prisma 4.8.1 (memory used  200mb)
![image](https://github.com/prisma/prisma/assets/89235917/71e62ed3-5f25-4e09-b4cc-b8ade8ff8d57)

**Comment by janpio** [comment]
Can you help us reproduce the problem @tuwibu? The more apps we have that are experiencing this, especially if it is somewhat simple to reproduce, the easier it will be to understand and fix this.

I assume your screenshot refers to `mem = 23.gb` for the `api` service? How long did that run to get into that state?

**Comment by tuwibu** [comment]
> Can you help us reproduce the problem @tuwibu? The more apps we have that are experiencing this, especially if it is somewhat simple to reproduce, the easier it will be to understand and fix this.
> 
> I assume your screenshot refers to `mem = 23.gb` for the `api` service? How long did that run to get into that state?

I cant reproduce problem.
My api only select random into 600k record, 500 request/s
It will consume up to 20gb of memory after 1-2 days
![image](https://github.com/prisma/prisma/assets/89235917/58fad69d-1b1a-4fbd-ad60-4dfc03f2da12)

**Comment by whalesync-ryder** [comment]
I wrote a very simple sample app and left it running over the weekend and I believe it repros the issue.
The code is here: https://github.com/whalesync-ryder/prisma-leak-demo

Here's the memory over 27 hours:
![Screen Shot 2023-09-11 at 11 58 56 AM](https://github.com/prisma/prisma/assets/93688278/765e70bc-2a52-434f-b5d7-a40fbe0cd75a)

Let me know if you have any questions, hope that helps!

**Comment by mmmeff** [comment]
In case folks missed it, this looks like its related to using Prisma on Node 16/18. Updating to Nodejs v20 fixed the memory leak for my team.

**Comment by adrian-goe** [comment]
@mmmeff I tested it with the reproduction, i posted. That did not fix it. 

Node: 20.6.1
Prisma: 5.2.0

@janpio I pushed it on a seperate branch https://github.com/adrian-goe/prisma-nestjs-memory-leak-repoduction/tree/node20

**Comment by janpio** [comment]
Thanks for anticipating my next question @adrian-goe and delivering the answer 🙇 

Can you do the same @whalesync-ryder maybe?

**Comment by janpio** [comment]
@whalesync-ryder This is what 6 hours on `Node.js 18.17.1` look like for me with your reproduction, run on GH Actions: https://github.com/janpio/prisma-leak-demo/actions/runs/6171034510/job/16748486361:

<img width="768" alt="image" src="https://github.com/prisma/prisma/assets/183673/b86b3c90-06ec-4658-997b-de0caae5c9b3">
Slight increase over time in RSS.

**Comment by whalesync-ryder** [comment]
@janpio Thanks for running it, i had a background task running this morning that found similar results. It's 10x better on node 20:

Node 16.13.0: Increases at 47. MB/hour
Node 20.6.1: Increases at 4.4 MB/hour

**Comment by janpio** [comment]
My result for 6 hours of node 16.13.0:
<img width="595" alt="image" src="https://github.com/prisma/prisma/assets/183673/286f7abb-4c93-44ce-8c04-2cbb0245f813">

**Comment by whalesync-ryder** [comment]
@janpio Very interesting! So you're not seeing any difference. Maybe I had something else going on to explain the 10x difference in leak speed between my two runs. I can't imagine what it would be.

**Comment by justinhandley** [comment]
I believe that we are also experiencing this - I can't give source code publicly, but I am happy to add a few developers to our repo for research purposes if that helps.

**Comment by janpio** [comment]
Thanks for the offer, but we have a few general apps that run out of memory with "just keep it running with normal production level traffic" - that is super hard to reproduce for us. Optimal would a minimal reproduction that _clearly_ shows how memory is leaking. The more obvious, the easier it is for us to figure out what is going on.

**Comment by r-moore** [comment]
I'm sorry I know this is not a particularly helpful comment, but we're definitely getting the same issues as described above in production too.

For now we're also restarting everything regularly with pm2.

Can't share too much other info about our setup on here, but if someone from prisma wants to reach out I can spare some time.

**Comment by pocesar** [comment]
using Prisma 5.3.1 and Node.js 20.6 decreased the amount of restarts per day to 0.25, which is a major improvement from the daily / twice restarts

**Comment by martinliptak** [comment]
I needed to run a script to import around 12 million records.

```
await db.record.findUnique({
    select: {
      id: true,
    },
    where: {
      id: key,
      updatedAt: { gte: lastModifiedDate },
    },
  })
```

Runing this query on Prisma 5.4.1 and NodeJS 18.12.0 was causing a memory leak. A simple script running only this query would consume all server memory and crash. Optimizing it with `$queryRaw` didn't help. Then I tried calling the raw query with pg 8.11.3 on Nodejs 18.12.0 and got normal memory consumption so the problem was with Prisma 5.4.1 on NodeJS 18.12.0. **I upgraded to NodeJS 20.8.0 and tested the original `findUnique` on Prisma 5.4.1 - this solved the problem.** The server is running Debian GNU/Linux 10 (buster), but the same thing was happening on Mac OS X.

<img width="1012" alt="Screenshot 2023-10-11 at 12 34 54 PM" src="https://github.com/prisma/prisma/assets/631534/004d9cf3-dd3f-4830-87d6-bef1dfa11fe5">

**Comment by Jolg42** [comment]
Hello 👋🏼 I'm working through posts here and reproductions attempts.

Note for @adrian-goe 
I tried to run your repro using a Codespace on GitHub, using the Node.js version from nvmrc https://github.com/adrian-goe/prisma-nestjs-memory-leak-repoduction/tree/node20?rgh-link-date=2023-09-13T08%3A39%3A57Z
But the "proof" which is supposed to not leak memory, is actually reporting a leak, see below 
<img width="1657" alt="Screenshot 2023-11-01 at 17 08 55" src="https://github.com/prisma/prisma/assets/1328733/f3d8f7fc-2a6e-4c8a-a1a8-44af09fc98de">

**Comment by Jolg42** [comment]
> @janpio Very interesting! So you're not seeing any difference. Maybe I had something else going on to explain the 10x difference in leak speed between my two runs. I can't imagine what it would be.

@whalesync-ryder It looks similar for my results, not much difference between different versions of Node.js
Since your last comment, do you have any update, maybe? 

Here is some fresh data below.

-------

Using a fork of (https://github.com/janpio/prisma-leak-demo)
I ran a matrix of different Node.js versions for 6 hours.

**This first run is using Prisma `5.2.0`**
https://github.com/Jolg42/prisma-leak-demo/actions/runs/6722787722 

<details>
  <summary>Here is the data from these runs, they all seem to, approximately, start at ~150 and end at ~180 after 6 hours.</summary>

- [prisma-leak-demo - Node v16.13.0](https://docs.google.com/spreadsheets/d/1RhWjam6gUispNlf67Hz0YxjdlfsC0Hz302P-BPkj6K0/edit?usp=sharing)
	![Node v16 13 0 rss (MiB), heapTotal (MiB), heapUsed (MiB), external (MiB) and arrayBuffers](https://github.com/prisma/prisma/assets/1328733/3239ce10-e3c8-4585-a10e-34ee46c91890)

- [prisma-leak-demo - Node v16.20.2](https://docs.google.com/spreadsheets/d/1-38f7KrXledaoEwxZxkaSZyMq9BW65FJn4q0pJ0zxdc/edit?usp=sharing)
	![Node v16 20 2 rss (MiB), heapTotal (MiB), heapUsed (MiB), external (MiB) and arrayBuffers](https://github.com/prisma/prisma/assets/1328733/bf05b495-b713-4daf-be95-b94e60a9fe3d)

- [prisma-leak-demo - Node v18.18.2](https://docs.google.com/spreadsheets/d/1jOSy0dHoPHOCt1DsN8sETzjJPZswULu5d4wZ34KvRZw/edit?usp=sharing)
	![Node v18 18 2 rss (MiB), heapTotal (MiB), heapUsed (MiB), external (MiB) and arrayBuffers](https://github.com/prisma/prisma/assets/1328733/53256965-b1ef-4e72-8333-e52dcfc013cf)

- [prisma-leak-demo - Node v20.9.0](https://docs.google.com/spreadsheets/d/1Q6If6zQ0r33q34GIaJQQOgEMyetzrXzHY5xgW4_adRo/edit?usp=sharing)
	![Node v20 9 0 rss (MiB), heapTotal (MiB), heapUsed (MiB), external (MiB) and arrayBuffers](https://github.com/prisma/prisma/assets/1328733/5c247d1a-863b-42bc-9ea3-f49d65fd407f)

</details>

--------

**This second run is using Prisma `5.5.2`**
https://github.com/Jolg42/prisma-leak-demo/actions/runs/6731468387

<details>
  <summary>Here is the data from these runs, they all seem to, approximately, start at ~150 and end at ~180 after 6 hours.</summary>

- [prisma-leak-demo - Node v16.13.0](https://docs.google.com/spreadsheets/d/1fEfLYDKHR-TVHkj1f9Sk3AkXd1VP4ftaF90e-tK8IGA/edit?usp=sharing)
	![Prisma 5 5 2 - Node v16 13 0 rss (MiB), heapTotal (MiB), heapUsed (MiB), external (MiB) and arrayBuffers](https://github.com/prisma/prisma/assets/1328733/b512c668-3e17-42b2-8f03-6711d82edac5)

- [prisma-leak-demo - Node v16.20.2](https://docs.google.com/spreadsheets/d/1Ew90UqU1eBfePPlmeKmacGZs3BGjBvp8NeCO--HgzCM/edit?usp=sharing)
	![Prisma 5 5 2 - Node v16 20 2 rss (MiB), heapTotal (MiB), heapUsed (MiB), external (MiB) and arrayBuffers](https://github.com/prisma/prisma/assets/1328733/311cdbb1-3967-49ce-985a-0decaa6fe610)

- [prisma-leak-demo - Node v18.18.2](https://docs.google.com/spreadsheets/d/1qy_K0ozN18xkem4MAj8Pt8BZHuPhjXot9wlYTyge7uU/edit?usp=sharing)
	![Prisma 5 5 2 - Node v18 18 2 rss (MiB), heapTotal (MiB), heapUsed (MiB), external (MiB) and arrayBuffers](https://github.com/prisma/prisma/assets/1328733/72b8695d-2f0c-4f18-90e6-b1463150cf66)

- [prisma-leak-demo - Node v20.9.0](https://docs.google.com/spreadsheets/d/1TaMHEHpiNEySzIPloxb3zPuK6N1hQ6YoG5eT4qr_Duo/edit?usp=sharing)
	![Prisma 5 5 2 - Node v20 9 0 rss (MiB), heapTotal (MiB), heapUsed (MiB), external (MiB) and arrayBuffers](https://github.com/prisma/prisma/assets/1328733/02e2581f-48b7-4370-b29d-55f8bf36d4ed)

</details>

**Comment by Jolg42** [comment]
> I wrote a very simple sample app and left it running over the weekend and I believe it repros the issue. The code is here: [whalesync-ryder/prisma-leak-demo](https://github.com/whalesync-ryder/prisma-leak-demo)
> 
> Here's the memory over 27 hours: ![Screen Shot 2023-09-11 at 11 58 56 AM](https://user-images.githubusercontent.com/93688278/267120680-765e70bc-2a52-434f-b5d7-a40fbe0cd75a.png)
> 
> Let me know if you have any questions, hope that helps! Edit: forgot to mention running on node v16.13.0. (which we need to upgrade from but you know)

@whalesync-ryder I could reproduce finally using Node.js v16, the reproduction in GitHub Actions was missing `yarn prisma db push` at first, so previous reproductions were actually not executing any queries, they were all failing because the database didn't exist.

**Did you upgrade to v18 or v20 already? This problem looks only related to Node.js v16 (which is "end of life") to me at the moment, see results:**
 
Note:
- I used `--max-old-space-size` to show how `rss` is actually reclaimed and growing `rss` is not a problem in itself, as long as it's reclaimed when there is some memory pressure.

----

## Using `nest start`

Upgrade all + Prisma 5.5.2 + --max-old-space-size=150 - Node v16.20.2
https://docs.google.com/spreadsheets/d/14-9DFfkW_DD_dAdj3WTsQ4kTm_HONd0fgE1rgUgGljo/edit?usp=sharing
🔴 There is definitely a leak here!
![prisma-leak-demo - Upgrade all + Prisma 5 5 2 + --max-old-space-size=150 - Node v16 20 2 rss (MiB), heapTotal (MiB), heapUsed (MiB), external (MiB) and arrayBuffers](https://github.com/prisma/prisma/assets/1328733/8befa433-beee-40ab-b6ba-d766c2b157c2)

Upgrade all + Prisma 5.5.2 + --max-old-space-size=150 - Node v18.18.2
Actually ran out of memory at `nest start`, see next section for results

Upgrade all + Prisma 5.5.2 + --max-old-space-size=150 - Node v20.9.0
https://docs.google.com/spreadsheets/d/1eSGaXS34aMqWJUW9r-oFjX5IU8ojQ5lAhSHHMsRJzQ4/edit?usp=sharing
![prisma-leak-demo - Upgrade all + Prisma 5 5 2 + --max-old-space-size=150 - Node v20 9 0 rss (MiB), heapTotal (MiB), heapUsed (MiB), external (MiB) and arrayBuffers](https://github.com/prisma/prisma/assets/1328733/d01ebe4c-e02e-4b11-a5b6-bd888166258d)


----

## Using `yarn run build` and then `node dist/main`
Notes: 
- `nest start` appears to consume a lot of memory when starting, so I switched to building and starting the server with Node.js instead.

Upgrade all + Prisma 5.5.2 + --max-old-space-size=150 + node dist/main - Node v16.20.2
https://docs.google.com/spreadsheets/d/1BQJLIMGl3xCQSFMNfYUgzdcAUhxaxHc8JnZqlFWJJJg/edit?usp=sharing
🔴 There is definitely a leak here!
![prisma-leak-demo - Upgrade all + Prisma 5 5 2 + --max-old-space-size=150 + node dist_main - Node v16 20 2 rss (MiB), heapTotal (MiB), heapUsed (MiB), external (MiB) and arrayBuffers](https://github.com/prisma/prisma/assets/1328733/e8f42b97-25f7-4d42-8287-bc7be23ca6fa)

Upgrade all + Prisma 5.5.2 + --max-old-space-size=150 + node dist/main - Node v18.18.2
https://docs.google.com/spreadsheets/d/1rDRyzjWi15ZC4az2-Hz0mULcskx98xfQ8ODoAYkGV7E/edit?usp=sharing
![prisma-leak-demo - Upgrade all + Prisma 5 5 2 + --max-old-space-size=150 + node dist_main - Node v18 18 2 rss (MiB), heapTotal (MiB), heapUsed (MiB), external (MiB) and arrayBuffers](https://github.com/prisma/prisma/assets/1328733/34403d54-656a-425b-aa51-e493bbba606c)

Upgrade all + Prisma 5.5.2 + --max-old-space-size=150 + node dist/main - Node v20.9.0
https://docs.google.com/spreadsheets/d/16hOzvpRsdtt3eay8xejz3ukTFByjPkm0t_6d1d_cFoY/edit?usp=sharing
![prisma-leak-demo - Upgrade all + Prisma 5 5 2 + --max-old-space-size=150 + node dist_main - Node v20 9 0 rss (MiB), heapTotal (MiB), heapUsed (MiB), external (MiB) and arrayBuffers](https://github.com/prisma/prisma/assets/1328733/bd7ffea8-bd14-4d34-83cb-1c1a0e9d7a85)

**Comment by whalesync-ryder** [comment]
I am in the process of upgrading my node right now, so i should be able to confirm pretty soon if that resolved it for me. Thanks for the info.

**Comment by tavindev** [comment]
Can confirm: Upgrading to Node v20 and Prisma v5.5.2 fixed the leak for me. Previously, memory usage would increase to 2GB within a few hours. Now, it remains at approximately 600MB over the same time span.

**Comment by whalesync-ryder** [comment]
Same here, my issues have been resolved since the node upgrade.
5.5.2 & Node 18.18.2
Thanks to whoever fixed it, accidentally or on purpose!

**Comment by r-moore** [comment]
Same - had a few weeks without issue since the upgrade, seems to be fixed!

**Comment by livthomas** [comment]
I still experience memory leaks with Prisma 5.5.2 on both Node.js 18.18.2 and 20.10.0.

**Comment by Druue** [comment]
Hey @livthomas we'll need further information to be able to help you at all.
Ideally, a minimal reproduction repro of the issue would be best (schema, js/ts code, query data). It would be greatly beneficial if you could share what exactly is going wrong, specific error messages, specific outcomes you're running into, and if possible, any graphs / data that indicate a memory leak (or high memory usage). [Here's an example](https://github.com/prisma/prisma/issues/16912#issuecomment-1854091009) of what I mean per graphs / data for profiling such issues.

**Comment by Jolg42** [comment]
Hello here, thanks for the updates! We're very happy to see that Upgrading to Node.js v18 solved the issue for you 🙌🏼 

We will now close this, here are a some notes about some things that were discussed here.

Like we found in https://github.com/prisma/prisma/issues/13575, about Jest `--detectLeaks`, it is an experimental feature, which is undocumented, and from our experience it's too often unreliable. You can see that similar results can be obtained without using Prisma.

Note that Prisma 5 got big performance improvements, like the internal protocol switch, which uses less RAM, for more details see https://www.prisma.io/blog/prisma-5-f66prwkjx72s
So we definitely recommend everyone to upgrade to Prisma 5.

The memory leak in this issue was confirmed when using Node.js v16, which is now End-Of-Life.
So we recommend everyone to upgrade to Node.js v18 or better v20, as [it is the current LTS](https://github.com/nodejs/release#release-schedule).

If you have a reproduction where a memory leak can be observed with a recent version of Prisma, please open a new issue with a reproduction, we will be happy to investigate and try to reproduce.
If it's related to using Jest, make sure to compare using Prisma and without Prisma, as the problem might be visible without using Prisma.

As a general note, when creating an issue, let us know if what you see is excessive memory usage or something that looks like a memory leak.
- In case of a memory leak, the memory usage would steadily go up when repeating the same query many times.
- In case of excessive memory usage, the memory usage would not increase over time, but only spike when the query is running. In this case, it could be that too much data is returned from the database and using a limit like `take: 10` to specify how many objects should be returned.

I hope I can create a code template in the future with some guidelines to help with identifying potential memory leaks in the future (to be done).

**Comment by GrinZero** [comment]
This seems to have some effect on me, thank you all

**Comment by Jolg42** [comment]
@GrinZero Just curious, could you give some details about what you modified, and what effect you see?

**Comment by GrinZero** [comment]
> @GrinZero只是好奇，您能否详细说明您修改的内容以及您看到的效果？

Update somethings:
- NestJs ^8 => ^10
- Prisma ^3 => ^5
- Node ^16 =>^20

I use `prom-client` and `grafana` to monitor memory. 

Before Update：
![image](https://github.com/prisma/prisma/assets/70185413/da1b3816-a011-4155-a0ed-9cc528efa91e)

After Update：
![image](https://github.com/prisma/prisma/assets/70185413/84bfa993-3cea-486c-9177-f7304baa1e24)
