### ISSUE TITLE
`parentTracer.getSpanLimits is not a function`

### ISSUE THREAD

**Issue by elledienne** [prisma/prisma#21397]
### Bug description

Upgrading to Prisma v5.4.1 caused the following error to appear

```
TypeError: parentTracer.getSpanLimits is not a function
    at new Span (/var/task/node_modules/@prisma/instrumentation/node_modules/@opentelemetry/sdk-trace-base/build/src/Span.js:59:41)
    at /var/task/node_modules/@prisma/instrumentation/dist/ActiveTracingHelper.js:59:20
    at Array.forEach (<anonymous>)
    at ActiveTracingHelper.createEngineSpan (/var/task/node_modules/@prisma/instrumentation/dist/ActiveTracingHelper.js:44:27)
    at Wi.createEngineSpan (/var/task/node_modules/@prisma/client/runtime/library.js:123:1687)
    at dr.propagateResponseExtensions (/var/task/node_modules/@prisma/client/runtime/library.js:112:4691)
    at Object.callback (/var/task/node_modules/@prisma/client/runtime/library.js:112:6604)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at dr.withRetry (/var/task/node_modules/@prisma/client/runtime/library.js:112:8713)
    at Object.singleLoader (/var/task/node_modules/@prisma/client/runtime/library.js:123:5333) {
  clientVersion: '5.4.1'
}
```

Before the upgrade, everything was running smoothly and the only change was upgrading Prisma

### How to reproduce

- Upgrade to Prisma v5.4.1 (you must have open telemetry configured too

### Prisma information

```
"@prisma/client": "^5.4.1",
"@prisma/instrumentation": "^5.4.1",
"prisma": "^5.4.1"
```

### Environment & setup

- OS: macOs
- Database: PostgreSQL
- Node.js version: 18

### Prisma Version

```
8.11.0
```

**Comment by aqrln** [comment]
I just now faced the same problem in one of my local test projects, updating all OpenTelemetry packages fixed this.

Seems like one of dependency updates in `@prisma/instrumentation` caused this. I think we should make `@opentelemetry/api` and other `peerDependencies` and not `dependencies` to prevent issues like this.

**Comment by aqrln** [comment]
@elledienne could you please post your OpenTelemetry setup code so we could reproduce? Thank you!

**Comment by aqrln** [comment]
> Could this be related to https://github.com/prisma/prisma/pull/21076?

As far as I see, that issue mentions this error specifically in the context of Datadog's `dd-trace` library, are you using it as well by any chance?

**Comment by elledienne** [comment]
@aqrln actually which version of `@opentelemetry/api` did you install to fix the issue?

**Comment by aqrln** [comment]
@elledienne 

> @aqrln actually which version of @opentelemetry/api did you install to fix the issue?

1.6.0

**Comment by elledienne** [comment]
@aqrln I think we were missing `@opentelemetry/api` from our deps - adding that fixed the issue, thank you!

**Comment by aqrln** [comment]
IMO this shouldn't be relegated to documentation but should be fixed so that the problem does not occur in the first place (or so that the package manager tells you what to install if anything needs to be installed manually, and detects conflicts). I haven't looked into it, but it sounds like we are bundling OpenTelemetry dependencies while we should probably be using peer dependencies instead.

There's another issue that I recently saw (https://github.com/prisma/prisma/issues/21473), let's use that as the main one.

**Comment by pleymor** [comment]
I still get the issue even after having installed `@opentelemetry/api`:

```json
"dependencies": {
    "other": "...",
    "@opentelemetry/api": "^1.8.0",
    "@opentelemetry/exporter-trace-otlp-http": "^0.49.1",
    "@opentelemetry/instrumentation": "^0.49.1",
    "@opentelemetry/resources": "^1.22.0",
    "@opentelemetry/sdk-trace-base": "^1.22.0",
    "@opentelemetry/sdk-trace-node": "^1.22.0",
    "@opentelemetry/semantic-conventions": "^1.22.0",
    "@prisma/client": "^5.10.2",
    "@prisma/instrumentation": "^5.10.2"
}
```

> TypeError: parentTracer.getSpanLimits is not a function
    at new Span (/Users/me/myproject/node_modules/@prisma/instrumentation/node_modules/@opentelemetry/sdk-trace-base/src/Span.ts:122:37)

**Comment by reserad** [comment]
I am also getting the same issue:

```
"dependencies": {
    "@opentelemetry/api": "^1.8.0",
    "@opentelemetry/exporter-trace-otlp-http": "^0.44.0",
    "@opentelemetry/instrumentation": "^0.44.0",
    "@opentelemetry/resources": "^1.17.1",
    "@opentelemetry/sdk-trace-base": "^1.17.1",
    "@opentelemetry/sdk-trace-node": "^1.17.1",
    "@opentelemetry/semantic-conventions": "^1.17.1",
    "@prisma/client": "^5.4.2",
    "@prisma/instrumentation": "^5.4.2"
},
"devDependencies": {
    "prisma": "^5.4.2"
}
```

> TypeError: parentTracer.getSpanLimits is not a function                                                                                                                                                                                                                                                                                                                  
     at new Span (/usr/src/app/node_modules/@prisma/instrumentation/node_modules/@opentelemetry/sdk-trace-base/build/src/Span.js:59:41)                                                                                                                                                                                                                                   
     at /usr/src/app/node_modules/@prisma/instrumentation/dist/ActiveTracingHelper.js:59:20                                                                                                                                                                                                                                                                               
     at Array.forEach (<anonymous>)                                                                                                                                                                                                                                                                                                                                       
     at ActiveTracingHelper.createEngineSpan (/usr/src/app/node_modules/@prisma/instrumentation/dist/ActiveTracingHelper.js:44:27)                                                                                                                                                                                                                                        
     at Wi.createEngineSpan (/usr/src/app/node_modules/@prisma/client/runtime/library.js:123:1687)                                                                                                                                                                                                                                                                        
     at mr.logger (/usr/src/app/node_modules/@prisma/client/runtime/library.js:114:1155)                                                                                                                                                                                                                                                                                  
     at /usr/src/app/node_modules/@prisma/client/runtime/library.js:114:910

**Comment by lewinskimaciej** [comment]
Any update to this? It broke our production in runtime after we updated to newest OTel libraries to get Logging functionalities. We had to remove Prisma instrumentation altogether for now.

**Comment by peng-huang-ch** [comment]
I've updated  the `@prisma/instrumentation` to `5.13.0`.
the OpenTelemetry dependencies 
```json
...
"@opentelemetry/api": "^1.8.0",
"@opentelemetry/auto-instrumentations-node": "^0.44.0",
"@opentelemetry/context-async-hooks": "1.23.0",
"@opentelemetry/core": "1.23.0",
"@opentelemetry/exporter-prometheus": "^0.50.0",
"@opentelemetry/exporter-trace-otlp-http": "^0.50.0",
"@opentelemetry/propagator-b3": "1.23.0",
"@opentelemetry/propagator-jaeger": "1.23.0",
"@opentelemetry/resources": "1.23.0",
"@opentelemetry/sdk-metrics": "1.23.0",
"@opentelemetry/sdk-node": "^0.50.0",
"@opentelemetry/sdk-trace-base": "1.23.0",
"@opentelemetry/semantic-conventions": "1.23.0",
"@prisma/client": "^5.13.0",
"@prisma/instrumentation": "^5.13.0",
...   
```
You can find the complete code in [the repo ](https://github.com/peng-huang-ch/nestjs-prisma-api)

**Comment by scottyeck** [comment]
We too are still seeing this, having updated to `5.14.0` and (from what I can tell) now using the OTEL dependencies pinned via https://github.com/prisma/prisma/issues/21473. We've also disabled `@prisma/instrumentation` for the time being.

> As far as I see, that issue mentions this error specifically in the context of Datadog's dd-trace library, are you using it as well by any chance?

@aqrln We are using `dd-trace`. If you have any additional guidance as to how to proceed, would greatly appreciate it.

**Comment by millsp** [comment]
Maybe related: https://github.com/prisma/prisma/issues/24373

**Comment by maxdeichmann** [comment]
Is there any update on this? I am running into the same issue.

**Comment by Marv963** [comment]
> I've updated the `@prisma/instrumentation` to `5.13.0`. the OpenTelemetry dependencies
> 
> ```json
> ...
> "@opentelemetry/api": "^1.8.0",
> "@opentelemetry/auto-instrumentations-node": "^0.44.0",
> "@opentelemetry/context-async-hooks": "1.23.0",
> "@opentelemetry/core": "1.23.0",
> "@opentelemetry/exporter-prometheus": "^0.50.0",
> "@opentelemetry/exporter-trace-otlp-http": "^0.50.0",
> "@opentelemetry/propagator-b3": "1.23.0",
> "@opentelemetry/propagator-jaeger": "1.23.0",
> "@opentelemetry/resources": "1.23.0",
> "@opentelemetry/sdk-metrics": "1.23.0",
> "@opentelemetry/sdk-node": "^0.50.0",
> "@opentelemetry/sdk-trace-base": "1.23.0",
> "@opentelemetry/semantic-conventions": "1.23.0",
> "@prisma/client": "^5.13.0",
> "@prisma/instrumentation": "^5.13.0",
> ...   
> ```
> 
> You can find the complete code in [the repo ](https://github.com/peng-huang-ch/nestjs-prisma-api)

Thank you!
`yarn add @prisma/instrumentation@5.13.0` fixed it for me

**Comment by rcidaleassumpo** [comment]
> We too are still seeing this, having updated to `5.14.0` and (from what I can tell) now using the OTEL dependencies pinned via #21473. We've also disabled `@prisma/instrumentation` for the time being until this is resolved.
> 
> > As far as I see, that issue mentions this error specifically in the context of Datadog's dd-trace library, are you using it as well by any chance?
> 
> @aqrln We are using `dd-trace`. If you have any additional guidance as to how to proceed, would greatly appreciate it.
> 
> #### Prisma information
> ```
> "@prisma/client": "^5.4.0",
> "@prisma/instrumentation": "^5.4.0",
> "prisma": "^5.4.0"
> ```
> 
> #### Environment & setup
> * OS: macOs
> * Database: PostgreSQL
> * Node.js version: 20

a little off topic, but if you don't mind telling me what's the setup for sending tracing from prisma to dd ?
do you basically just have the dd-trace doing its thing, then have a manual setup that does the opentelemetry setup ?


```
const exporter = new OTLPTraceExporter({
  url: url,
});

const traceProvider = new NodeTracerProvider({

});

traceProvider.addSpanProcessor(new BatchSpanProcessor(exporter));

traceProvider.register();

registerInstrumentations({
  tracerProvider: traceProvider,
  instrumentations: [new PrismaInstrumentation()],
});
```

liek this ? or did you manage to glue both together ?
