### ISSUE TITLE
Support `enum` in SQLite (via polyfill)

### ISSUE THREAD

**Issue by lglie** [prisma/prisma#2219]
## Problem
Now, enum removed in sqlite

## Solution
When develop time, It is very convenient to verify the schema.prisma  with sqlite

**Comment by pantharshit00** [comment]
Related: https://github.com/prisma/specs/issues/382

**Comment by tlonist-sang** [comment]
Has there been any update regarding this issue?

**Comment by pantharshit00** [comment]
@tlonist-sang Please see https://github.com/prisma/specs/issues/330 and https://github.com/prisma/specs/issues/382.

For now we have decided to not to polyfill database features. More details about the decision has been mentioned in the above issues. This might come in the future so stay tuned!

**Comment by devuxer** [comment]
This is a blocker for me. I can live with the database not enforcing enums (as it has no way of knowing about them), but it would be impractical to have to manually write a mapper for every model type that has an enum field just to get proper compile-time type checking and intellisense. The value of TypeScript is really compromised without this feature.

**Comment by beeman** [comment]
I would also really like to emphasize the importance of supporting this.

Having the ability to switch from SQLite to Postgres, without having to change the Prisma schema, is a very useful feature. 

The main places I see it useful are testing (I'd love to be able to not spin up Postgres on CI) and starter projects (where you want to provide a working DB at start, and later suggest them to use Postgres).

**Comment by rizkyramadhan** [comment]
We sorely need this, as switching between sqlite and postgresql are common in our project lifecycle.

**Comment by orefalo** [comment]
For me, it's all about principles - 
   one ORM to rule them all

If the product starts adding/remove feature per database... will quickly become a nightmare to implement/maintain.


I run my tests in sqllite, prod in mysql - guess I will have to do enums utside the ORM

**Comment by eden-omb** [comment]
Why not even just use a simple string in place of an enum when using SQLite? SQLite is mostly just used for dev envs, and even if it wasn't, so long as people use prisma client enums are even enforceable. And even when they're not, why forbid it at the schema level just because of the datasource provider?

**Comment by Ali1Ammar** [comment]
any update?

**Comment by KorigamiK** [comment]
> I would also really like to emphasize the importance of supporting this.
> 
> Having the ability to switch between SQLite and Postgres, without having to change the Prisma schema, is a very useful feature.
> 
> The main places I see it useful are testing (I'd love to be able to not spin up Postgres on CI) and starter projects (where you want to provide a working DB at start, and later suggest them to use Postgres).

I cannot agree more! I hope this issue surfaces again.

**Comment by john-schmitz** [comment]
What is the current project stance on this issue?

I could make a PR for it.

**Comment by ivan-kleshnin** [comment]
@lglie @john-schmitz I guess this issue would get a different reaction if you removed  `(via polyfill`) from its title 🤔 . 

Prisma devs:
*We don't need a polyfill – please just resolve `enum` to any text type for DBs that don't support enums. It's much less evil than incompatible model specs for a "database agnostic" tool.*

**Comment by homoky** [comment]
I see it as very important step towards better testing. We have right now about 6 000 test and for each we run in parralell the postgress db in docker and it is just because we need to use enums in production. This would simplify everything from the testing point.

I would not mind if it would be enabled with some flag so it is not default. But this is deal breaker for big teams from my point of view.

**Comment by alexferrari88** [comment]
having this would make our lives way easier for testing (switching between sqlite and postgres)

**Comment by juliusmarminge** [comment]
> having this would make our lives way easier for testing (switching between sqlite and postgres)

This 👆👆👆 use sqlite in ci so much faster than waiting for a postgres container

**Comment by asciant** [comment]
What's everyone's change their making to their schema when doing testing? To make enums test in SQLite.

**Comment by dzcpy** [comment]
Any updates? Will it be supported?

**Comment by richard-fairthorne** [comment]
I would be happy if I had to add an annotation to the schema to indicate that I am aware my target database may not enforce the enum. That way, developers can choose a schema that works everywhere, or a schema that is definitely enforced.

**Comment by ImLunaHey** [comment]
Hate to be that person but is there any update on this?
From the comments everyone seems to agree this is needed one way or another. 🤔

**Comment by dorbn4** [comment]
Now that this issue is open for almost 3 years it would be nice to get some kind of update on this. Supporting `enum`s would be amazing as you can simply use e.g. postgres for production and sqlite for local development and in CI pipelines for testing. 

In the [prisma documentation about enums](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#enum) is written "_Enums are implemented and enforced at Prisma level in MongoDB_", the same approach would be good enough for enum's in sqlite. If this is unacceptable for you then atleast put it behind a feature flag 🙏 

On a personal note, I do think that adding `enum`'s to sqlite on a prisma level would increase prisma's adoption and developer happiness :) 

<img width="1303" alt="Prisma sqlite enums" src="https://user-images.githubusercontent.com/80417067/218299583-171f5f37-ada2-428a-a62b-ae270668e33f.png">

**Comment by richard-fairthorne** [comment]
> @dorbn4 well said, I think the reason people use ORM's are to not bother too much about the features of a database since an ORM's job is to do the hardwork for me.

Yup. I use an ORM to abstract away the underlying database specific issues.

The reason I would switch to prisma is because of the wide variety of type safe language generators. 

If prisma doesn't do both of these things, at least for simple cases, I can stick accessing databases directly. At least, in rust, type safety can be provided by many db connector packages which query the schema and validate SQL at compile time.

**Comment by GandelXIV** [comment]
Any updated on this?

**Comment by richard-fairthorne** [comment]
> Why would you not use the mocked prisma for tests?

This does not solve the problem of requiring different schemas for different database engines, while using basic features.

**Comment by olalonde** [comment]
FWIW, it looks like SQLite *does* support enums: https://stackoverflow.com/a/17203007/96855

**Comment by janpio** [comment]
That is a workaround that allows you to achieve close behavior, which we could use to emulate real enums.

**Comment by olalonde** [comment]
> That is a workaround that allows you to achieve close behavior, which we could use to emulate real enums.

How is it different from PostgreSQL enums? Can't really tell the difference other than it's declared inline when creating the table.

**Comment by janpio** [comment]
Yes, that is what defines a workaround. SQLite does not support enums directly, but you use check constraints to achieve the same functionality.

**Comment by olalonde** [comment]
I don't want to argue too much about semantics but it could be argued that `check (col1 in ('value1','value2','value3,'value4'))` is just an enum type with an unusual syntax. Regardless, my point was that there is no need to enforce/verify the constraint client side in JavaScript via emulation/`polyfill`. We just need to tell the SQLite engine how to create enum columns using this syntax. I'm not familiar with Prisma architecture, maybe people meant something else by polyfill.

**Comment by janpio** [comment]
From our perspective a polyfill is, in this case, pretending that an enum exists as a construct for SQLite, so you can [use `enum Foo { .... }` in Prisma Schema Language](https://www.prisma.io/docs/concepts/components/prisma-schema/data-model#defining-enums). 

If you "just" want to have a field that behaves like an enum, that would require us to support the check constraint - which we _unfortunately_ also do not, for any database: https://github.com/prisma/prisma/issues/3388 (That is also a reason why we can not easily _just_ use the check constraint to emulate an enum - because we will add support for check constraints sooner or later, which will then mean we have a conflict how to present some check constraints from SQLite in PSL). 

It's messy, I know.

**Comment by dzcpy** [comment]
> Well, it's almost been three years since the original proposal and this still isn't implemented.
> 
> It is a very weird new user experience, to start building out a Prisma schema, see enums in the documentation, think "ooh, this would be perfect for X use case!", then have my editor complain that the connector does not, in fact, support them.
> 
> Prisma's a great library that offers a lot of benefits, but this is a bit silly. Is there an ETA on an implementation for this, preferably more specific than "sooner or later"?

Just use TypeORM instead, it's more feature rich and complete, not to say performance wise I think it's also better

**Comment by janpio** [comment]
We know that this feature would be very nice for some of our users, which is why the feature request is still open after 3 years and has not been closed. But we did not and do not have the capacity to build this right now, so it will have to wait a bit longer until we do. Sorry.

**Comment by devuxer** [comment]
@ladybunne,

I'd like to know the same thing.

Taking a look at the [Prisma Roadmap](https://prismaio.notion.site/Prisma-ORM-Roadmap-50766227b779464ab98899accb98295f), I note that this feature is not on it, so the best case scenario is probably "when everything else on the roadmap is done". That said, the roadmap doesn't list estimated completion dates, so it's hard to put a number to this. If I had to hazard a guess, I'd say "at least 6 months". It would be nice if @janpio could offer something like, we are in line behind X major features, y medium features, and z small features, but I don't know how Prisma's backlog is organized.

**Comment by dzcpy** [comment]
Or, as an alternative, is supporting pg-mem easier?

**Comment by janpio** [comment]
We can not give an ETA. We do not know. It might happen next, or it might happen never. We have not prioritized this yet, and do not plan to. It is not how we work right now. Sorry.

**Comment by mattwebhub** [comment]
Ehrm.. how something apparently so small can be this big of a pain point for everyone

**Comment by dzcpy** [comment]
At least there are many new ORMs comming out like orchid orm, stay alart Prisma 😂

**Comment by janpio** [comment]
If we built this, how would you expect the enum values to be stored in the database?
Any concrete examples on how other ORMs and database clients handle this?

**Comment by SagnikPradhan** [comment]
Seems like both [mikro-orm](https://github.com/mikro-orm/mikro-orm/blob/master/packages/sqlite/src/SqliteSchemaHelper.ts#L47) and [typeorm](https://github.com/typeorm/typeorm/pull/3700) use `CHECK` constraints

**Comment by absolutelysimon** [comment]
Agreed that it would be extremely useful to smoothly switch between SQLite and Postgres.

We would love this.

**Comment by olalonde** [comment]
As a workaround, I have resorted to using "enum tables" which are tables with a single id column and which use a seed script to populate the allowed values. It's a lot of boilerplate but it guarantees data consistency.

e.g.

```prisma
// stores allowed values for user roles
model UserRole {
  id String @id
  users User[]
}

model User {
  id  Int @id @default(autoincrement())
  roleId String @default("user")
  role UserRole @relation(fields: [roleId], references: [id])
}
```

**Comment by andriemc** [comment]
Any updates on this?

**Comment by Andrew-Pynch** [comment]
Any updates on this? my company would love to use prisma but we NEED this feature! :-)

**Comment by andriemc** [comment]
The reason this is missing is why I don't use prisma...

**Comment by andriemc** [comment]
The reason I don't prisma is because this is missing

**Comment by yanisurbis** [comment]
Is there any monetary value that we can attach to this issue? :)

**Comment by Andrew-Pynch** [comment]
> Is there any monetary value that we can attach to this issue? :)

1 billion dollars

**Comment by SeanMcGoff** [comment]
I'm not even 2 days into a new project and ran into this issue. It's rather silly that this is not a feature of prisma, even as a optional config

**Comment by richard-fairthorne** [comment]
> I'm not even 2 days into a new project and ran into this issue. It's rather silly that this is not a feature of prisma, even as a optional config

That's where I gave up a well. Throwing away 80% of their audience.

**Comment by devuxer** [comment]
> > I'm not even 2 days into a new project and ran into this issue. It's rather silly that this is not a feature of prisma, even as a optional config
> 
> That's where I gave up a well. Throwing away 80% of their audience.
> 
> In fact, that's where I determined that the main function of an ORM is to limit your ability to store and query data.
> 
> In fact, learning enough SQL to outclass an ORM takes about 30 minutes.

I know and am comfortable with SQL yet still find it very useful to be able to query/mutate a database using JS/TS. This enum issue is not an inherent problem with ORMs, it's a problem with Prisma.

**Comment by draew6** [comment]
This is something i would expect from best ORM.

**Comment by empflow** [comment]
we need this feature!!!

**Comment by muchisx** [comment]
Amazed aswell as how this is not yet implement atleast at the Prisma level.
What is the current workaround for this?

**Comment by salahmedamin** [comment]
Prisma Team, thank you for the amazing ORM, but THIS FEATURE IS A MUST !

**Comment by andriemc** [comment]
I'm officially leaving Prisma.

**Comment by NyllRE** [comment]
@muchisx create a model to simulate enums and link them with your model

**Comment by zwhitchcox** [comment]
> Why would you not use the mocked prisma for tests?

Try to mock as little as possible

**Comment by zwhitchcox** [comment]
> (That is also a reason why we can not easily _just_ use the check constraint to emulate an enum - because we will add support for check constraints sooner or later, which will then mean we have a conflict how to present some check constraints from SQLite in PSL).

Could you have this behind a feature flag, like `unstable_check_constraint_enum`, which we *know* will break at some point when you introduce check constraints? Then, when check constraints are implemented, we can just switch our code to use that? I'm fine with *only* using check constraints if it means I can use any database with my prisma model, and I get the feeling a lot of the people in this thread feel the same way @janpio

**Comment by janpio** [comment]
In theory we could, but my quote also included "easily just": Doing it this way, would definitely move this feature outside of "easily just" territory and into "pretty complex, both in implementation and documentation". Sorry.

**Comment by BenLebich** [comment]
I am currently migrating from MySQL to SQLite3, and this has been a blocker for me. I have over 15 different enums defined with over 50+ different references to the generated enums from the schema. Switching all of these to be statically defined in my typescript and having to do my checks every time I do a db action against an enum field just sounds miserable.

Having them just be stored as strings in the db, but have the enums enforced by typescript and auto-generated is all I really need...

**Comment by homerjam** [comment]
> Perhaps it is just me and my bubble, but with the recent PlanetScale pricing changes and the Astro DB launch, this feature may be more relevant now.

I don't think you're alone in this bubble : )

Imagine how trivial it would be to move from PlanetScale to Astro/Turso if it wasn't for this...

**Comment by listepo** [comment]
Yes this feature is in high demand

**Comment by danpitsch** [comment]
I ran into this on the first day of using Prisma, please add ENUM support for Sqlite.  For now, I am using "enum tables" suggested by @olalonde:

> As a workaround, I have resorted to using "enum tables" which are tables with a single id column and which use a seed script to populate the allowed values. It's a lot of boilerplate but it guarantees data consistency.
> 
> e.g.
> 
> ```prisma
> // stores allowed values for user roles
> model UserRole {
>   id String @id
>   users User[]
> }
> 
> model User {
>   id  Int @id @default(autoincrement())
>   roleId String @default("user")
>   role UserRole @relation(fields: [roleId], references: [id])
> }
> ```

I have always referred to this approach as "Lookup Tables", and is commonly used when there are more than a few items in the list. There are maybe 3 lines of extra code to define the table and seed the data vs. defining the ENUM.  So is a tolerable LOE, and is worth it for me to use Prisma and interoperate across multiple database products.  Perhaps if a section in the DOCS that explained how to do this as an alternative, it would be easier for developers to adopt.

All this said, I DO think that Prisma SHOULD build a real solution into the product, there is certainly enough interest.

**Comment by Andyloz** [comment]
Why not just let generate the typescript types for enum and store the contents as text? Maybe there can be a message saying that enums can't be enforced and that would be all

**Comment by fmineo** [comment]
I need this feature too 🥹

**Comment by akmaldika** [comment]
Need this feature 😢

**Comment by with-key** [comment]
omg...

**Comment by budchirp** [comment]
4 years and no update..

**Comment by MobinAskari** [comment]
I just came across this issue, considering it's been 4 years and there is no progress to be seen, I think should just use Postgres at this point...

**Comment by kevinshibuya** [comment]
Release ENUM for the masses 🔥🔥🔥

**Comment by NyllRE** [comment]
@MobinAskari the point was to be able to use sqlite on development and postgres on production. the lighter one while developing and the heavier more stable and capable one in production. since this is an ORM it's only a matter of developing a couple of functions from making the prisma library easily transportable between databases.

**Comment by NyllRE** [comment]
@MobinAskari it is, though you can just use a model like [danpitsch](https://github.com/prisma/prisma/issues/2219#issuecomment-2067711044) suggestsed. but prisma needs to add it either way

**Comment by GandelXIV** [comment]
I wonder how long it will take until someone finally decides to sit down and add this feature.

**Comment by tguelcan** [comment]
I am currently in the development phase and was also planning to switch between sqlite and postgres for local development and am very surprised that the ticket has existed for over 4 years and there is no feedback from the team. ENUMS are important functions. I hope for an (at least experimental) solution soon instead of creating a table.

**Comment by draew6** [comment]
@tguelcan i use postgres and sqlite for local. I just have script that creates schema for sqlite where Enums are removed and replaced as String. I do not expect them to fix this.

**Comment by Ed1ks** [comment]
There is so much demand for this. Why this gets ignored? 🙄

**Comment by anaibol** [comment]
+1

**Comment by paulo-pertierra** [comment]
Warding in case of change, back to using Prisma (last used 2 years ago), and a little surprised this still isn't in the roadmap.

**Comment by subodhk01** [comment]
Need this feature

**Comment by dzcpy** [comment]
> I just came across this issue, considering it's been 4 years and there is no progress to be seen, I think should just use Postgres at this point...

You should try Drizzle ORM

**Comment by michalryskiewicz** [comment]
+1

**Comment by mhmdsalahsebai** [comment]
I think this is the most needed feature

**Comment by mbarinov** [comment]
🤙

**Comment by chudnyi** [comment]
+1

**Comment by eralvarez** [comment]
+1

**Comment by anaibol** [comment]
+1

**Comment by Ed1ks** [comment]
+1

**Comment by taskindrp** [comment]
+1

**Comment by Ehbraheem** [comment]
Please add support for this feature. This is 2025 already

**Comment by NyllRE** [comment]
@Ehbraheem as of now based on the Prisma ORM roadmap right above your comment, you can see that they finally acknowledged this issue as necessary to resolve. so we might see a difference otherwise you will get pinged on this issue for another year unless you turn off notifications

**Comment by Ehbraheem** [comment]
> @Ehbraheem as of now based on the Prisma ORM roadmap right above your comment, you can see that they finally acknowledged this issue as necessary to resolve. so we might see a difference otherwise you will get pinged on this issue for another year unless you turn off notifications

Thanks for the clarification @NyllRE. I'll be on the lookout for changes.

**Comment by sorenbs** [comment]
It's happening!

**Comment by GandelXIV** [comment]
> It's happening!

Where will all my entertainment from reading this issue through the years go :( ?

**Comment by teddybee** [comment]
> It's happening!

One step forward.
Only the polymorphism needed for this ORM.

**Comment by mattwebhub** [comment]
Omg! This really happened. Am I seeing this right? I feel emotional, idk what's going on rn

**Comment by NyllRE** [comment]
### We used to pray for times like this
![image](https://github.com/user-attachments/assets/0ebbf65e-0d50-47af-8cf4-0ff18518f3f0)

**Comment by devuxer** [comment]
@jacek-prisma , I'm truly grateful that this issue has finally been resolved, but now that I try to use it, I realize it won't work for my particular situation. I use `primsa db pull` (introspect) frequently, and it seems that enums get removed from my schema.prisma file whenever I do this. Am I missing a setting or config option that would enable enums to stick after a db pull?

**Comment by jacek-prisma** [comment]
Hi @devuxer , the issue you're seeing should be resolved in the next minor prisma version.

**Comment by dm-pse** [comment]
Hi @jacek-prisma , Circling back to this again, I just tried the latest version, but I'm still facing a show-stopper with `prisma db pull`. With this new version, it thankfully does not strip out the enums anymore, so that part has been solved, but it does still strip out any `@map` attributes I add to the enum values. This prevents me from converting things like `Three_Word_Value` to a more human readable form, like "Three-Word Value". Is this something that could be fixed?
