### ISSUE TITLE
nested count, aggregate _count query inefficiency

### ISSUE THREAD

**Issue by mangotree0867** [prisma/prisma#23891]
### Bug description

When prisma builds count queries or aggregates for "_count" values why does it use IN to get values after joining when counting directly from the joined table would be much more efficient? Is there a certain reason to why it runs like this under the hood?

also I'm curious where the OFFSET came from. I'm guessing the offset value is 0 but I don't really understand why there is an OFFSET query here

you can see that using IN and OFFSET slows the query down a lot when you explain analyze the raw query 
![스크린샷 2024-04-19 오후 3 39 22](https://github.com/prisma/prisma/assets/74580651/2ddf7f98-a8b7-45f5-ade2-9fa1443a7349)

### How to reproduce

1. Run count query with nested condition
Eg)
```
    await this.prisma.productMetrics.count({
      where: {
        product: {
          visible: true,
          approvedAt: { not: null },
        },
      },
    });
```

2. See the raw sql query that prisma runs
Eg)
```
SELECT count(*)
FROM (SELECT "public"."product_metrics"."product_id" 
	  FROM "public"."product_metrics" 
	  WHERE ("public"."product_metrics"."product_id") IN 
	  	(SELECT "t0"."product_id" 
		 FROM "public"."product_metrics" AS "t0" 
                  INNER JOIN "public"."product" AS "j0" 
                  ON ("j0"."id") = ("t0"."product_id") 
		 WHERE ("j0"."visible" = 'true'
				AND "j0"."approved_at" IS NOT NULL 
				AND "t0"."product_id" IS NOT NULL
                                 )
		)
	  OFFSET 0
	 )
	 AS "sub"
```

### Expected behavior

I was expecting the code to count from the inner joined query straight up instead of using IN to match the product_ids again

```
SELECT count("t0"."product_id")
FROM "public"."product_metrics" AS "t0" INNER JOIN "public"."product" AS "j0" ON ("j0"."id") = ("t0"."product_id") 
WHERE ("j0"."visible" = 'true'
AND "j0"."approved_at" IS NOT NULL 
AND "t0"."product_id" IS NOT NULL)
```

### Prisma information

```
model Product {
  id                          Int                 @id @default(autoincrement())
  name                    String
  visible                   Boolean             @default(true)
  approvedAt          DateTime?           @map("approved_at")
  ProductMetrics    ProductMetrics[]

  @@map("product")
}

model ProductMetrics {
  productId             Int     @id @map("product_id")
  product               Product @relation(fields: [productId], references: [id], onDelete: Cascade)
  dayReviewCount        Int     @default(0) @map("day_review_count")
  dayLikeCount          Int     @default(0) @map("day_like_count")
  viewCount             Int     @default(0) @map("view_count")

  @@map("product_metrics")
}
```

TS code
```
    await this.prisma.productMetrics.count({
      where: {
        product: {
          visible: true,
          approvedAt: { not: null },
        },
      },
    });
```
  

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v16.17.0

### Prisma Version

```
4.12.0
```

**Comment by janpio** [comment]
> why does it use IN to get values after joining when counting directly from the joined table would be much more efficient? Is there a certain reason to why it runs like this under the hood?

Probably just slipped through on our side when the feature was built - and because it returns the correct data, and no one has reported this as inefficient before, there was no need to revisit it.

> also I'm curious where the OFFSET came from. I'm guessing the offset value is 0 but I don't really understand why there is an OFFSET query here

Probably similar reasons as above - using a `OFFSET 0` when no offset is actually needed probably looked like a fair tradeoff to keep some code simple. Is the query faster without the `OFFSET 0`?

**Comment by mangotree0867** [comment]
Thank you janpio for your detailed follow up with the bug!

> Can you try the same query again with a newer version of Prisma, to make sure that this has not been fixed in the meantime?
Sure, I tried with 5.12.1 version and I found out that it has been fixed so that the query doesn't use the IN statement after joining(thx for the update! should have tried updating the version before reporting it mb) but I found out that the OFFSET statement was still there

```
SELECT COUNT(*) 
FROM (SELECT "public"."product_metrics"."product_id" 
	  FROM "public"."product_metrics" 
	  LEFT JOIN "public"."product" AS "j1" 
	  ON ("j1"."id") = ("public"."product_metrics"."product_id") 
	  WHERE (
		  	 "j1"."visible" = 'true'
			 AND "j1"."approved_at" IS NOT NULL 
			 AND ("j1"."id" IS NOT NULL)
			)
	  OFFSET 0
	 )
	 AS "sub"
```

> Additionally, can you try with the [relationJoins preview feature](https://www.prisma.io/docs/orm/prisma-client/queries/relation-queries#relation-load-strategies-preview)? That might also have impact on the generated SQL query and its performance.
I'm getting an error when I tried the relationJoins preview feature on the count query but it seems to be intended. I see that its omitted from the count query (If I'm using it wrong I would find it very kind of you if you could correct me thx!)

```
    await this.prisma.productMetrics.count({
      relationLoadStrategy: 'join',
      where: {
        product: {
          visible: true,
          approvedAt: { not: null },
        },
      },
    });
```

_from index.d.ts_
```
  type ProductMetricsCountArgs<ExtArgs extends $Extensions.InternalArgs = $Extensions.DefaultArgs> = 
    Omit<ProductMetricsFindManyArgs, 'select' | 'include' | 'distinct' | 'relationLoadStrategy'> & {
      select?: ProductMetricsCountAggregateInputType | true
    }
```

> Is the query faster without the OFFSET 0?
Comparing the two queries that I got from the updated version of prisma I did find out that including OFFSET did have an impact on the cost of the query.
![스크린샷 2024-04-21 오전 4 31 43](https://github.com/prisma/prisma/assets/74580651/25e36cd5-d9e1-4fc6-9e51-41b7f8f78d0a)

**Comment by DearTanakorn** [comment]
I'm using Prisma 6.3.1 and @prisma/client 6.3.1 (the latest versions), but count queries still include an OFFSET clause even when no pagination is applied. This extra OFFSET, although set to 0, causes unnecessary overhead and impacts performance.

**Comment by Mreddi1** [comment]
I'm using Prisma 6.9.0, and it still did not fixed.. @mangotree0867 @janpio

**Comment by eliliam** [comment]
Also using Prisma 6.12.0 and we're also having issues due to the `OFFSET` causing the query to not make use of the correct table index, which results in the query taking ~100x longer than it should if it used the correct index.
