### ISSUE TITLE
Postinstall script fails with ECONNRESET

### ISSUE THREAD

**Issue by lucasavila00** [prisma/prisma#23927]
### Bug description

Similar to what has been reported before https://github.com/prisma/prisma/issues/20193

We're seeing lots of CI jobs failures because of this. Retrying the jobs make it work.

I'd appreciate if prisma could retry it on it's own when download fails. Similar to what was suggested on https://github.com/prisma/prisma/issues/23325

### How to reproduce

Installing prisma with NPM

### Prisma information

It fails to install

### Environment & setup

Ubuntu 22, Hetzner Servers in Germany, Gitlab CI

### Prisma Version

```
prisma                  : 4.16.2
@prisma/client          : Not found
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.16.1-1.4bc8b6e1b66cb932731fb1bdbbc550d1e010de81
Default Engines Hash    : 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81
Studio                  : 0.484.0
```

**Comment by dgellow** [comment]
Hi, we are facing the same problem in GitHub workflows.

```
. postinstall: > PRISMA_GENERATE_SKIP_AUTOINSTALL=true prisma generate
. postinstall: Prisma schema loaded from ../shared/prisma/schema.prisma
. postinstall: node:internal/process/promises:289
. postinstall:             triggerUncaughtException(err, true /* fromPromise */);
. postinstall:             ^
. postinstall: Error: read ECONNRESET
. postinstall:     at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
. postinstall:   errno: -104,
. postinstall:   code: 'ECONNRESET',
. postinstall:   syscall: 'read',
. postinstall:   attemptNumber: 1,
. postinstall:   retriesLeft: 2
. postinstall: }
```

**Comment by maxkaido** [comment]
```
 remote: [4/4] Building fresh packages...        
remote: error /app/node_modules/@prisma/engines: Command failed.        
remote: Exit code: 1        
remote: Command: node scripts/postinstall.js        
remote: Arguments:         
remote: Directory: /app/node_modules/@prisma/engines        
remote: Output:        
remote: node:internal/process/promises:289        
remote:             triggerUncaughtException(err, true /* fromPromise */);        
remote:             ^        
remote:         
remote: Error: read ECONNRESET        
remote:     at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {        
remote:   errno: -104,        
remote:   code: 'ECONNRESET',        
remote:   syscall: 'read',        
remote:   attemptNumber: 1,        
remote:   retriesLeft: 2        
remote: }        
```

**Comment by maxkaido** [comment]
I've updated prisma to the latest version 5.13 and issue gone

**Comment by RobertCraigie** [comment]
We're still running into this frequently even with multiple retries configured for the `pnpm install` step and on `v5.13`

**Comment by Jolg42** [comment]
I guess this is related to the current status of Cloudflare  https://www.cloudflarestatus.com/

I'm sorry for the issue you experienced today.
Are you still experiencing this issue now?
I'm traveling and I cannot do much for now, I'm hoping this is already resolved.

I'll definitely discuss this with my colleagues tomorrow.

**Comment by RobertCraigie** [comment]
Thankfully we've managed to workaround this by re-routing traffic through different IPs

**Comment by SevInf** [comment]
Hey everyone. Since CloudFlare incident is solved now, we are going to close the issue. Feel free to open an new one if it is still regularly happening for your.
Thank you!

**Comment by Thimoss** [comment]
I still get this issue even though my prism is already version ^6.7.0

**Comment by piscopancer** [comment]
Started happening to me for no reason with local Pg server, pgadmin works fine, other libs like `pg` connect successfully but running `prisma generate` results in the same connection error. What's up with prisma?

**Comment by alex1yaremchuk** [comment]
Experiencing it on mobile internet connection.

**Comment by Blthrst** [comment]
Experiencing it on both mobile and wired internet connection

**Comment by Gata-chan** [comment]
Experiencing this on wi-fi
