### ISSUE TITLE
dotenv loading issue with PrismaClient

### ISSUE THREAD

**Issue by Maxime-J** [prisma/prisma#24634]
### Bug description

In 5.16.0 release, my .env files are no longer loaded, leading to an error using Prisma Client.

```
error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:7
   |
 6 |   provider = "postgresql"
 7 |   url      = env("DATABASE_URL")
```
Debug:
```
prisma:tryLoadEnv Environment variables not found at null +13ms
prisma:tryLoadEnv Environment variables not found at undefined +1ms
prisma:tryLoadEnv No Environment variables loaded +1ms
```

It's working with the previous release 5.15.1:
```
prisma:tryLoadEnv Environment variables not found at null +2ms
prisma:tryLoadEnv Environment variables loaded from /projectPath/.env +1ms
```

Note that env loading logic has been changed in  https://github.com/prisma/prisma/pull/24417

### How to reproduce

Any classic Prisma project should be concerned.
See Prisma information for a minimal reproducible case.

### Expected behavior

.env file in project root should be loaded when PrismaClient is used.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model test {
  id Int @id
}

```

```ts
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
await prisma.test.count();
```

### Environment & setup

- OS: Debian 11
- Node.js version: 20.15.0

### Prisma Version

```
prisma                  : 5.16.0
@prisma/client          : 5.16.0
Computed binaryTarget   : debian-openssl-1.1.x
Operating System        : linux
Architecture            : x64
Node.js                 : v20.15.0
Query Engine (Node-API) : libquery-engine 34ace0eb2704183d2c05b60b52fba5c43c13f303 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Schema Engine           : schema-engine-cli 34ace0eb2704183d2c05b60b52fba5c43c13f303 (at node_modules/@prisma/engines/schema-engine-debian-openssl-1.1.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.16.0-24.34ace0eb2704183d2c05b60b52fba5c43c13f303
Default Engines Hash    : 34ace0eb2704183d2c05b60b52fba5c43c13f303
Studio                  : 0.502.0

```

**Comment by WhyAsh5114** [comment]
Facing the same issue

**Comment by lolcabanon** [comment]
Same!

`$ pnpx prisma version` :

```
Environment variables loaded from .env
prisma                  : 5.16.0
@prisma/client          : 5.15.1
Computed binaryTarget   : debian-openssl-1.1.x
Operating System        : linux
Architecture            : x64
Node.js                 : v20.11.1
Query Engine (Node-API) : libquery-engine 34ace0eb2704183d2c05b60b52fba5c43c13f303 (at ../../../.cache/pnpm/dlx/32qs76zfpdzhrg4l3y6ui3zucu/19050821341-163a2/node_modules/.pnpm/@prisma+engines@5.16.0/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Schema Engine           : schema-engine-cli 34ace0eb2704183d2c05b60b52fba5c43c13f303 (at ../../../.cache/pnpm/dlx/32qs76zfpdzhrg4l3y6ui3zucu/19050821341-163a2/node_modules/.pnpm/@prisma+engines@5.16.0/node_modules/@prisma/engines/schema-engine-debian-openssl-1.1.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.16.0-24.34ace0eb2704183d2c05b60b52fba5c43c13f303
Default Engines Hash    : 34ace0eb2704183d2c05b60b52fba5c43c13f303
Studio                  : 0.502.0
```

**Comment by gideontonkinson** [comment]
Same issue

**Comment by DangaRanga** [comment]
Also facing this issue. 

```
Environment variables loaded from .env
prisma                  : 5.16.0
@prisma/client          : 5.16.0
Computed binaryTarget   : windows
Operating System        : win32
Architecture            : x64
Node.js                 : v20.15.0
Query Engine (Node-API) : libquery-engine 34ace0eb2704183d2c05b60b52fba5c43c13f303 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 34ace0eb2704183d2c05b60b52fba5c43c13f303 (at node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.16.0-24.34ace0eb2704183d2c05b60b52fba5c43c13f303 
Default Engines Hash    : 34ace0eb2704183d2c05b60b52fba5c43c13f303
Studio                  : 0.502.0
```

Strangely enough, some queries worked as normal, but when trying to execute my seeders it failed due to the `DATABASE_URL` environment variable not being found

**Comment by SikoSoft** [comment]
Same!

I spent the past two hours investigating all these other scenarios before noticing this package got updated recently and decided to check if there was a recent release.

Glad to hear it's not just me at least.

But yes, 5.16.0 does not work for me. The last version I was using was 5.13.0 and it worked fine.

**Comment by dcryan** [comment]
Same issue.
I have `prisma: 5.16.0` and `@prisma/client: 5.16.0` also. I even tried moving around my `.env` file from the root directory to under the `prisma` directory. Still didn't work. If you need it working, downgrading `@prisma/client` to `v5.15.1` worked for me as a temporary workaround.

**Comment by kingkingburger** [comment]
same issue

It works well with `v5.15.1` for me. try the downgrade

`pnpx prisma version`
Environment variables loaded from .env
prisma                  : 5.16.0
@prisma/client          : 5.16.0
Computed binaryTarget   : windows
Operating System        : win32
Architecture            : x64
Node.js                 : v20.10.0
Query Engine (Node-API) : libquery-engine 34ace0eb2704183d2c05b60b52fba5c43c13f303 (at C:\Users\dnjsa\AppData\Local\pnpm-cache\dlx\32qs76zfpdzhrg4l3y6ui3zucu\1905459ec4e-604\node_modules\.pnpm\@prisma+engines@5.16.0\node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 34ace0eb2704183d2c05b60b52fba5c43c13f303 (at C:\Users\dnjsa\AppData\Local\pnpm-cache\dlx\32qs76zfpdzhrg4l3y6ui3zucu\1905459ec4e-604\node_modules\.pnpm\@prisma+engines@5.16.0\node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.16.0-24.34ace0eb2704183d2c05b60b52fba5c43c13f303
Default Engines Hash    : 34ace0eb2704183d2c05b60b52fba5c43c13f303
Studio                  : 0.502.0
Preview Features        : driverAdapters

**Comment by jkomyno** [comment]
Hey everyone, thanks for notifying us about this issue. We're looking onto this and plan on releasing a patch release (5.16.1) shortly, probably tomorrow. Sorry for this disruption, but thanks again for pointing this problem out!

**Comment by jkomyno** [comment]
Hello @Maxime-J, @gideontonkinson and others, we've just released [Prisma 5.16.1](https://www.npmjs.com/package/prisma/v/5.16.1), which contains the fix to this regression (and an additional test to ensure it doesn't happen again).

Please install it, re-run `prisma generate`, and you should be good to go. You're welcome to leave feedback here in the comments :)

**Comment by lolcabanon** [comment]
I confirm it fixed my issue! Thanks :smiley:

**Comment by samhinton88** [comment]
Unfortunately I'm still experiencing the issue despite having upgraded:
```
npx prisma -v
Environment variables loaded from .env
prisma                  : 5.16.1
@prisma/client          : 5.16.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v20.14.0
Query Engine (Node-API) : libquery-engine 34ace0eb2704183d2c05b60b52fba5c43c13f303 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 34ace0eb2704183d2c05b60b52fba5c43c13f303 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.16.0-24.34ace0eb2704183d2c05b60b52fba5c43c13f303
Default Engines Hash    : 34ace0eb2704183d2c05b60b52fba5c43c13f303
Studio                  : 0.502.0
```

**Comment by je-movers-market** [comment]
@samhinton88 You haven't upgraded. Your client version is still 5.16.0.

**Comment by kingkingburger** [comment]
@samhinton88
The @prisma/client version must be `5.16.1`.  `5.16.0` is the problematic version
 `@prisma/client` need `npm i @prisma/client@lastest` or `pnpm i @prisma/client@lastet`
Maybe it'll work

**Comment by samhinton88** [comment]
Ah didn't occur to me that I had to upgrade both libs. Thanks!

**Comment by jkomyno** [comment]
> Ah didn't occur to me that I had to upgrade both libs. Thanks!

Hi @samhinton88, yeah, generally speaking, `prisma` + `@prisma/client` + any other `@prisma/*` package you depend on should have the same version. In fact, when you have two different versions and you run `prisma generate`, you should be able to observe the warning:

```
Versions of `prisma@x.x.x` and `@prisma/client@x.x.x` don't match.
This might lead to unexpected behavior.
Please make sure they have the same version.
```

Hope that helps! Cheers 👋🏻
