### ISSUE TITLE
[6.7.0] NextJS - Prisma

### ISSUE THREAD

**Issue by devpanda0** [prisma/prisma#27079]
### Bug description

See bug. It occurs directly at startup

### Severity

🚨 Critical: Data loss, app crash, security issue

### Reproduction

https://github.com/devpanda0/prisma-nextjs-repro

pull the repo, install packages, generate Prisma files, then run `nexr dev --turbo`

### Expected vs. Actual Behavior

fix it

### Frequency

Consistently reproducible

### Does this occur in development or production?

Both development and production

### Is this a regression?

The error has been occurring since switching to “Rust free”

### Workaround

No workaround found

### Prisma Schema & Queries

```prisma
generator client {
  provider        = "prisma-client"
  output          = "../src/prisma"
  previewFeatures = ["queryCompiler", "driverAdapters"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id                    String   @id @default(cuid(2))
  discordId             String   @unique
  username              String
  logoUrl               String
  currentOrganizationId String?
  guildIds              String[] @default([])
  createdAt             DateTime @default(now())
  updatedAt             DateTime @updatedAt

  // Better-auth Felder
  email         String? @unique
  emailVerified Boolean @default(false)
  image         String? // Könnte logoUrl verwenden

  sessions Session[]
  accounts Account[]

  @@index([id, discordId])
}

model Session {
  id        String   @id
  expiresAt DateTime
  token     String
  createdAt DateTime
  updatedAt DateTime
  ipAddress String?
  userAgent String?
  userId    String
  user      User     @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([token])
  @@map("session")
}

model Account {
  id                    String    @id
  accountId             String
  providerId            String
  userId                String
  user                  User      @relation(fields: [userId], references: [id], onDelete: Cascade)
  accessToken           String?
  refreshToken          String?
  idToken               String?
  accessTokenExpiresAt  DateTime?
  refreshTokenExpiresAt DateTime?
  scope                 String?
  password              String?
  createdAt             DateTime
  updatedAt             DateTime

  @@map("account")
}

model Verification {
  id         String    @id
  identifier String
  value      String
  expiresAt  DateTime
  createdAt  DateTime?
  updatedAt  DateTime?

  @@map("verification")
}
```

### Prisma Config

```ts
import 'dotenv/config';
import path from 'node:path';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  earlyAccess: true,
  schema: path.join('prisma'),
});
```

### Logs & Debug Info

```
> next dev --turbo

   ▲ Next.js 15.3.1 (Turbopack)
   - Local:        http://localhost:3000
   - Network:      http://10.8.3.10:3000
   - Environments: .env

 ✓ Starting...
 ✓ Ready in 1657ms
 ○ Compiling / ...
 ✓ Compiled / in 3.4s
 ⨯ ./src/prisma/client.ts:14:1
Module not found: Can't resolve './enums.js'
  12 |
  13 | import * as runtime from "@prisma/client/runtime/wasm"
> 14 | import * as $Enums from "./enums.js"
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  15 | import * as $Class from "./internal/class.js"
  16 | import * as Prisma from "./internal/prismaNamespace.js"
  17 |



https://nextjs.org/docs/messages/module-not-found



./src/prisma/client.ts:18:1
Module not found: Can't resolve './enums.js'
  16 | import * as Prisma from "./internal/prismaNamespace.js"
  17 |
> 18 | export * as $Enums from './enums.js'
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  19 | /**
  20 |  * ## Prisma Client
  21 |  *



https://nextjs.org/docs/messages/module-not-found



./src/prisma/client.ts:15:1
Module not found: Can't resolve './internal/class.js'
  13 | import * as runtime from "@prisma/client/runtime/wasm"
  14 | import * as $Enums from "./enums.js"
> 15 | import * as $Class from "./internal/class.js"
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  16 | import * as Prisma from "./internal/prismaNamespace.js"
  17 |
  18 | export * as $Enums from './enums.js'



https://nextjs.org/docs/messages/module-not-found



./src/prisma/client.ts:16:1
Module not found: Can't resolve './internal/prismaNamespace.js'
  14 | import * as $Enums from "./enums.js"
  15 | import * as $Class from "./internal/class.js"
> 16 | import * as Prisma from "./internal/prismaNamespace.js"
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  17 |
  18 | export * as $Enums from './enums.js'
  19 | /**



https://nextjs.org/docs/messages/module-not-found


 ○ Compiling /_error ...
 ✓ Compiled /_error in 1157ms
 GET / 500 in 5013ms

```

### Environment & Setup

- **OS:** Windows
- **Database:** PostgreSQL
- **Node.js version:** v22.14.0

### Prisma Version

```
Loaded Prisma config from "F:\Aufträge\test\prisma.config.ts".
Prisma config detected, skipping environment variable loading.
Prisma schema loaded from prisma
prisma                  : 6.7.0
@prisma/client          : 6.7.0
Computed binaryTarget   : windows
Operating System        : win32
Architecture            : x64
Node.js                 : v22.14.0
TypeScript              : 5.8.3
Query Engine (Node-API) : libquery-engine 3cff47a7f5d65c3ea74883f1d736e41d68ce91ed (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 3cff47a7f5d65c3ea74883f1d736e41d68ce91ed (at node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 6.7.0-36.3cff47a7f5d65c3ea74883f1d736e41d68ce91ed
Default Engines Hash    : 3cff47a7f5d65c3ea74883f1d736e41d68ce91ed
Studio                  : 0.511.0
Preview Features        : driverAdapters, queryCompile
```

**Comment by devpanda0** [comment]
when i disable the native client in PrismaPg i got node:crypto error

**Comment by devpanda0** [comment]
maybe any news? Can anyone reproduce the error?

**Comment by djshubs** [comment]
I'm getting a similar error.

**Comment by FGoessler** [comment]
Hey @devpanda0 👋 

It seems you are using the new generator which is currently in preview (`provider = "prisma-client"`). 

I think we have fix for this particular issue coming up that will fix the used file extension in the generated output. 
Can you try out a recent dev build like `6.8.0-dev.24` please? 
Alternatively you can manually [configure the used file extension](https://www.prisma.io/docs/orm/prisma-schema/overview/generators#field-reference-1) by setting `generatedFileExtension = "ts` in the generator block.

You should also be able to work around this by using our old generator (`provider = "prisma-client-js"`) for now.

**Comment by devpanda0** [comment]
> Hey @devpanda0 👋 
> 
> It seems you are using the new generator which is currently in preview (`provider = "prisma-client"`). 
> 
> I think we have fix for this particular issue coming up that will fix the used file extension in the generated output. 
> Can you try out a recent dev build like `6.8.0-dev.24` please? 
> Alternatively you can manually [configure the used file extension](https://www.prisma.io/docs/orm/prisma-schema/overview/generators#field-reference-1) by setting `generatedFileExtension = "ts` in the generator block.
> 
> You should also be able to work around this by using our old generator (`provider = "prisma-client-js"`) for now.
> 

Hey, I’ll try it out and give you some feedback. Thanks for your reply! :)

**Comment by devpanda0** [comment]
okay, its works now but not more in the middleware

**Comment by FGoessler** [comment]
What do you mean by "not more in the middleware" @devpanda0 ? 🤔

**Comment by devpanda0** [comment]
@FGoessler 
 ⚠ ./generated/prisma/internal/class.ts:79:32
Ecmascript file had an error
  77 |
  78 |   getQueryCompilerWasmModule: async () => {
> 79 |     const { readFile } = await import('node:fs/promises')
     |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  80 |     const { createRequire } = await import('node:module')
  81 |     const require = createRequire(import.meta.url)



 ⚠ ./generated/prisma/internal/class.ts:80:37
Ecmascript file had an error
  78 |   getQueryCompilerWasmModule: async () => {
  79 |     const { readFile } = await import('node:fs/promises')
> 80 |     const { createRequire } = await import('node:module')
     |                                     ^^^^^^^^^^^^^^^^^^^^^
  81 |     const require = createRequire(import.meta.url)
  82 |
  83 |     const wasmModulePath = require.resolve("@prisma/client/runtime/query_compiler_bg.postgresql.wasm")



 ⚠ ./generated/prisma/client.ts:13:1
Ecmascript file had an error
  11 | import * as process from 'node:process'
  12 | import * as path from 'node:path'
> 13 | import { fileURLToPath } from 'node:url'
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  14 | const __dirname = path.dirname(fileURLToPath(import.meta.url))
  15 |
  16 | import * as runtime from "@prisma/client/runtime/client"

**Comment by devpanda0** [comment]
Tested with `6.8.0-dev.46` @FGoessler

**Comment by devpanda0** [comment]
Tested with `6.9.0-dev.3` same problem as above. i don't know why :( @FGoessler

**Comment by devpanda0** [comment]
When i use the runtime "edge-light" i got this error:

 ⚠ ./generated/prisma/internal
Package @prisma/client can't be external
The request @prisma/client/runtime/query_engine_bg.postgresql.wasm matches serverExternalPackages (or the default list).
Only .mjs, .cjs, .js, .json, or .node can be handled by Node.js.

**Comment by devpanda0** [comment]
> we have this issue on our radar and keep you posted here once we had the time to investigate and potentially fix it. We have some work for this planned in our current sprint leading up the 6.9.0 release.
> 
> Until then please try to use the old generator as a workaround. The new generator is still in preview and has various edge cases in which it might not work or we haven't documented all necessary build configuration steps for all scenarios.
okay, ty.

> Can it be that your "middleware" is code that gets bundled for the frontend? As Prisma is a database framework it is not expected to be bundled client side. If you only need specific Model or Enum types in your frontend you can import them directly from ./generated/prisma/enums.ts or ./generated/prisma/models/YourModel.ts. Those file have no node specific dependencies and can be imported in frontend code.

no, this middleware is full server-side and I don't use enums or models types in the middleware.
@FGoessler

**Comment by mathi123** [comment]
Seems fixed in 6.16,

although I did need to add the **importFileExtension** (not sure why) to get it to work.

```
generator client {
    provider = "prisma-client"
    output   = "client"

    importFileExtension = "ts"
}
```

**Comment by jasonappah** [comment]
dropping a quick note to vouch for @mathi123's fix :) worked for me with on 6.19.0, but only after adding `importFileExtension = "ts"`

**Comment by jcubic** [comment]
Got same error after migrating to Prisma 7.

Adding `importFileExtension = "ts"` doesn't work.

**Comment by jdhenry08** [comment]
@jcubic What version of next? I just ran into the same problem after updating to Prisma 7, using next@14.2.5, but I don't remember running into a similar problem when using Prisma 7 with next@15 (or was it 16?) in a different project.

**Comment by tyler-dot-earth** [comment]
here's how i'm dealing with this so far ⏬ but i'm still working on the upgrade in our repo.

i have prisma in own pnpm monorepo package like: `<git_root>/packages/prisma`

tsconfig looks roughly like
```
    "compilerOptions": {
        "noEmit": false,
        "outDir": "./dist",
        "rootDir": "./src",
        "module": "NodeNext",
        "moduleResolution": "NodeNext",
    },
```

`package.json` looks roughly like this
```
{
    "name": "@org/prisma",
    "version": "0.1.0",
    "private": true,
    "type": "module",
    "main": "./dist/index.js",
    "types": "./dist/index.d.ts",
    "files": [
        "dist",
        "src"
    ],
    "devDependencies": {
        "@prisma/config": "catalog:",
        "prisma": "catalog:",
        "prisma-json-types-generator": "catalog:",
        "typescript": "catalog:foundation"
    },
    "dependencies": {
        "@prisma/client": "catalog:",
        "@prisma/adapter-pg": "catalog:"
    },
    "imports": {
        "#*": {
            "types": "./dist/*.d.ts",
            "default": "./dist/*.js"
        },
        "#generated/*": {
            "types": "./dist/generated/*.d.ts",
            "default": "./dist/generated/*.js"
        },
        "#scripts/utils": {
            "types": "./dist/scripts/utils/*.d.ts",
            "default": "./dist/scripts/utils/*.js"
        }
    },
    "exports": {
        ".": {
            "types": "./dist/index.d.ts",
            "default": "./dist/index.js"
        },
        "./client": {
            "types": "./dist/client.d.ts",
            "default": "./dist/client.js",
            "browser": "./dist/generated/browser.js"
        },
        "./browser": {
            "types": "./dist/generated/browser.d.ts",
            "default": "./dist/generated/browser.js"
        },
        "./db-client": {
            "types": "./dist/db-client.d.ts",
            "default": "./dist/db-client.js"
        },
    },
}
```

`schema.prisma`
```
    provider               = "prisma-client" // the no-rust engine; https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/no-rust-engine
    engineType             = "client" // req. for the no-rust engine
    runtime                = "nodejs"
    moduleFormat           = "esm"
    generatedFileExtension = "ts"
    importFileExtension    = "js"
```

⤴️ note the use of `js` - that's because i use the export map to the built files (which are `js`). alo important: `imports` map means i never import a `.js` within my package - i import like `import { X } from "#generated/whatever"` and the import map resolves it.

then i mostly use the `browser` exports for types as i'm not sure of any value of the other ones.

again - still working through the updates, but seems to be working well enough so far.

**Comment by jcubic** [comment]
@jdhenry08 I use Next@16.0.3

**Comment by hanhn-dev** [comment]
I got the same issue and I solved it with my changes as following. I added `moduleFormat`, `generatedFileExtension` and `importFileExtension`. One thing to note that I added them after migrating from v6 to v7.

```
generator client {
  provider = "prisma-client"
  output   = "../generated/prisma"
  moduleFormat = "esm"
  generatedFileExtension = "ts"
  importFileExtension = "ts"
}
```

**Comment by mosespace** [comment]
> I got the same issue and I solved it with my changes as following. I added `moduleFormat`, `generatedFileExtension` and `importFileExtension`. One thing to note that I added them after migrating from v6 to v7.
> 
> ```
> generator client {
>   provider = "prisma-client"
>   output   = "../generated/prisma"
>   moduleFormat = "esm"
>   generatedFileExtension = "ts"
>   importFileExtension = "ts"
> }
> ```

🔥 I also admit after adding the following, it was fixed. Using Nextjs 16.0.3 and Prisma Version 7

**Comment by jdhenry08** [comment]
> I got the same issue and I solved it with my changes as following. I added `moduleFormat`, `generatedFileExtension` and `importFileExtension`. One thing to note that I added them after migrating from v6 to v7.
> 
> ```
> generator client {
>   provider = "prisma-client"
>   output   = "../generated/prisma"
>   moduleFormat = "esm"
>   generatedFileExtension = "ts"
>   importFileExtension = "ts"
> }
> ```

This DID NOT work for me on next@14.2.5.

**Comment by nishatislam04** [comment]
after implementing the guide from @hanhn-dev at latest nextjs `v16.0.5` the js importing error resolved.
when i first faced it, i was very lost. and had a hard time googling this issue
i hope prisma fix this issue either in built-in or add the support on the official prisma docs. 

edit: i am using prisma `v7.0.1`

**Comment by jcubic** [comment]
I just tested again. I have two databases. Adding the below code to both schema files fixed the issue. Even before upgrading to `7.0.1`.

```
  moduleFormat = "esm"
  generatedFileExtension = "ts"
  importFileExtension = "ts"
```

**Comment by lexmin0412** [comment]
Same Problem with Next.js when upgrade from v6, resolved with:

```ts
generator client {
  ...
  generatedFileExtension = "ts"
  importFileExtension = "ts"
}
```

**Comment by dfodeker** [comment]
I ran into the same issue while upgrading **Next.js 16.0.3** and migrating **Prisma from v6.6.0 → v7.2.0**.

The first thing I did   was **delete the existing `./generated/prisma` folder** . ( probably not necessary )

After that, I was able to fix it in a couple different ways.

---

## Option 1: Node-style resolution (changes generated imports)

When I set Node ESM settings in `tsconfig.json`:

```json
{
  "compilerOptions": {
    "module": "nodenext",
    "moduleResolution": "nodenext"
  }
} 

```

and updated the  prisma generator

```ts
generator client {
  moduleFormat = "esm"
  generatedFileExtension = "ts"
  importFileExtension = "ts"
}
```

This caused the generated client to use .ts imports instead of .js, and the build passed. I personally could not get the generator setting to work with node as my module resolution 

---
## Option 2: Bundler-style resolution

Changing TypeScript to bundler resolution also fixed it, even though the Prisma docs recommend "moduleResolution": "node"

```json
{
  "compilerOptions": {
    "module": "esnext",
    "moduleResolution": "bundler"
  }
}
```

Then running bun prisma generate / npm prisma generate worked without further changes. Hopefully this helps someone else upgrading.

**Comment by devnchill** [comment]
still encountering this problem . i did required changes in schema.prisma as other mentioned above , that doesn't seems to fix it. Using turborepo .

    "prisma": "^7.2.0"

**Comment by iammdsameer** [comment]
Here’s what worked for me in my Next.js app with **`prisma@^7.2.0`**, in case anyone else runs into the same issue:

1. Remove the entire `generated/` directory (this folder is created after running `npx prisma generate`).

2. Update `tsconfig.json`
   - Set the module resolution strategy to:
     ```json
     {
       "moduleResolution": "bundler"
     }
     ```

3. Regenerate the Prisma client
   ```bash
   npx prisma generate

After doing the above, everything started working as expected.
It seems the issue was caused by stale generated files combined with an incompatible moduleResolution setting.

**Comment by geneshairzan** [comment]
```
generator client {
...
  generatedFileExtension = "ts" // THIS LINE SAVE THE DAY
  importFileExtension = "ts" // THIS LINE SAVE THE DAY
```

**Comment by nxtvoid** [comment]
i ran into this issue today on Turborepo

```json
"prisma": "7.7.0"
"next": "16.2.4"
"turbo": "2.8.17"
```

what @hanhn-dev mentioned solved this problem for me

```prisma
generator client {
  provider               = "prisma-client"
  output                 = "../generated/prisma"
  moduleFormat           = "esm"
  generatedFileExtension = "ts"
  importFileExtension    = "ts"
}
```
