### ISSUE TITLE
Postgres pagination filter with value 1 returns multiple values

### ISSUE THREAD

**Issue by tfiwm** [prisma/prisma#2786]
**Describe the bug**
Using the first: 1 or last: 1 in a query returns more than 1 result

**To Reproduce**
Use a pagination filter first or last with value 1

**Expected behavior**
I receive 1 node

**Screenshots**
![image](https://user-images.githubusercontent.com/988473/42910671-bdc5330a-8ae8-11e8-97eb-8b54fdbef9cb.png)

**Versions (please complete the following information):**
 - OS: `OS X High Sierra`
 - `prisma` CLI: [e.g. `prisma/1.12.0 node-v8.9.2`]
 - Prisma Server: [e.g. `1.12.0`]
 - `graphql-cli`, `prisma-binding`, `graphql-yoga`

**Comment by do4gr** [comment]
Hey @tfiwm,

can you post some more information about this? I tried reproducing this but only always got one node. Can you maybe post your data model or a minimal sample data model that shows that behavior?

Thanks!

**Comment by brikou** [comment]
I'm having the **almost** same issue (but weirder), using prisma 1.15.0 image, with: 

```graphql
# datamodel
type Foo {
    id: ID! @unique
    bars: [Bar!]!
}

type Bar {
    id: ID! @unique
    quantity: Int!
}
```

```graphql
# seed
mutation {
    foo_1: createFoo(
        data: {
            bars: {
                create: [{ quantity: 1 }, { quantity: 2 }, { quantity: 3 }]
            }
        }
    ) {
        id
    }
}
```

# GQL Query

```graphql
{
  foos {
    bars(orderBy: quantity_DESC, first: 1) {
      id
      quantity
    }
  }
}
```

## expected result:

```json
{
  "data": {
    "foos": [
      {
        "bars": [
          {
            "id": "cjle2yiqm00650a87wmblhx3e",
            "quantity": 3
          },
        ]
      }
    ]
  }
}
```

## actual result:

```json
{
  "data": {
    "foos": [
      {
        "bars": [
          {
            "id": "cjle2yiqf00610a87i5tbyr6p",
            "quantity": 1 # >>>>>>>>>>>> ORDER is wrong
          },
          {
            "id": "cjle2yiqj00630a87cun5jq4f",
            "quantity": 2 # >>>>>>>> I don't have 1 neither 3 results but 2 :/
          }
        ]
      }
    ]
  }
}
```

This is IMO quite an important bug :bug: (because order is not correct), beside that prisma is lovely :1st_place_medal:

**Comment by rvlewerissa** [comment]
Skipping doesn't work me as well on #2972, maybe it's related.

**Comment by marktani** [comment]
Hey @brikou, we couldn't reproduce this yet. Can you prepare step by step reproduction instructions to help us with that? 🙂

**Comment by brikou** [comment]
@marktani maybe I forgot to tell you I'm using postgres connector and checked with prisma image 0.14.2 and 0.15

Tell me if you miss information, if you still cannot reproduce then I'll create a repo with everything (docker-compose, datamodel.graphql, ... and so on)

Thank to take time for this :+1:

**Comment by brikou** [comment]
Here is my docker-compose (because postgres version is probably interesting too)

```yaml
version: "3"

services:
    postgres:
        image: postgres:10.5-alpine

    prisma:
        depends_on:
            - postgres
        image: prismagraphql/prisma:1.15.1
        ports:
            - "4466:4466"
        environment:
            PRISMA_CONFIG: |
                databases:
                    default:
                        connector: postgres
                        host: postgres
                        port: 5432
                        user: postgres

```

**Comment by brikou** [comment]
@marktani great `reproduction-available`!!!

**Comment by mavilein** [comment]
Thanks for reporting and providing thorough descriptions! 🙏  We fixed this issue and it is available in version `1.15.2` 🎉 . The build will be available in a few minutes.

**Comment by brikou** [comment]
thanks @mavilein but the issue is still there :) I've just try with `1.15.3` and my reproduction is still relevant :bug: 

```graphql
{ foos { bars(first: 1) { id quantity } } } # gives 2 results
{ foos { bars(first: 2) { id quantity } } } # gives 2 results (ok then)
{ foos { bars(first: 3) { id quantity } } } # gives 2 results

{ foos { bars(orderBy: quantity_DESC) { id  quantity } } } # works
{ foos { bars(orderBy: quantity_ASC) { id  quantity } } } # works
{ foos { bars(first: 1, orderBy: quantity_DESC) { id  quantity } } } # gives 2 results and ignores orderBy
```

Please re-open this bug report, ping @marktani
