### ISSUE TITLE
Prisma Accelerate Down - AWS outage?

### ISSUE THREAD

**Issue by collasanta** [prisma/prisma#28329]
### Bug description

My Prod Prisma-Accelerate db is down after AWS Outage, 

Seems that the binary generation got impacted.

`{\"code\":\"P6008\",\"message\":\"Accelerate was not able to connect to your database. The underlying error is: error requesting Query Engine from pool\"}} (The request id was: 9918e0cd78756461)"}`

Any updates here? thanks

### Severity

🚨 Critical: Data loss, app crash, security issue

### Expected vs. Actual Behavior

Expected: normal requests 

Actual Behaviour: 
Error code P6008

<img width="873" height="386" alt="Image" src="https://github.com/user-attachments/assets/07da271e-6119-4704-8313-058fef5ed50c" />

<img width="938" height="66" alt="Image" src="https://github.com/user-attachments/assets/c195f143-6195-43da-b9ce-2b8da9ad968f" />

**Comment by jcyuan** [comment]
same........
but wait, you mean it caused by your AWS outage, not Accelerate itself?
i think this should be caused by Accelerate itself because my google CloudSql works well.

**Comment by collasanta** [comment]
> same........ but wait, you mean it caused by your AWS outage, not Accelerate itself? i think this should be caused by Accelerate itself because my google CloudSql works well.

Seems to be similar issue to https://github.com/prisma/prisma/issues/27700

Problem to generate the binaries due to problems with third party providers, like cloudflare and AWS. 

I suggest the Prisma Accellerate team to make their infrastructure more resilient, we are considering moving on about using their service. 2 critical incidents in a short period of time.

**Comment by siviwexakaza** [comment]
same issue, cant even use the studio to look at my tables. Is this because of the AWS outage?

**Comment by simurgh420** [comment]
same issue almost everything is Down.

**Comment by jcyuan** [comment]
> > same........ but wait, you mean it caused by your AWS outage, not Accelerate itself? i think this should be caused by Accelerate itself because my google CloudSql works well.
> 
> Seems to be similar issue to [#27700](https://github.com/prisma/prisma/issues/27700)
> 
> Problem to generate the binaries due to problems with third party providers, like cloudflare and AWS.
> 
> I suggest the Prisma Accellerate team to make their infrastructure more resilient, we are considering moving on about using their service. 2 critical incidents in a short period of time.

not, that's a different problem, i encountered that one too before, and it was fixed by a rebooting of their CLI server.
Accelerate proxy server is down now i believe.

**Comment by PaulNext** [comment]
All of our service interfaces that use Prisma acc are down. Where are the official engineers? Please see the log of the large-scale error as soon as possible.

Error fetching payment details: Error [PrismaClientKnownRequestError]: 
Invalid `prisma.payment.findRaw()` invocation:


This request could not be understood by the server: {"type":"UnknownJsonError","body":{"code":"P6008","message":"Accelerate was not able to connect to your database. The underlying error is: error requesting Query Engine from pool"}} (The request id was: 9919bc702da3deb7)
    at async h (.next/server/pages/api/payment/scan.js:1:3113)
    at async Module.m (.next/server/pages/api/payment/scan.js:1:1756) {
  code: 'P5000',
  meta: [Object],
  clientVersion: '6.17.1'
}

2025-10-20T12:21:12.199Z [error] Error [PrismaClientKnownRequestError]: 
Invalid `prisma.payee.findMany()` invocation:



2025-10-20T12:21:12.202Z [error] ⨯ Error: Failed to load static file for page: /en/500 ENOENT: no such file or directory, open '/var/task/.next/server/pages/en/500.html'
    at async Object.handler (___next_launcher.cjs:57:3)
2025-10-20T12:21:12.204Z [error] Error [PrismaClientKnownRequestError]: 
Invalid `prisma.payee.findMany()` invocation:

**Comment by siviwexakaza** [comment]
It's been over 4 hours now and we still cant connect to databases in us-east-1
NeonBD did put out a notification on their status page saying us-east-1 is affected, I wonder why Prisma did not do the same?
The status page shows that everything is fine

**Comment by PaulNext** [comment]
Our payments protocol processes tens of thousands of dollars in transactions every minute. Please pay attention to this as soon as possible. This is a disaster that will affect millions of dollars in transactions a day.

**Comment by jcyuan** [comment]
i think it's just fixed. my project works fine now.

**Comment by jacek-prisma** [comment]
I think this was a temporary issue 3 weeks ago, so I'm going to close it.
