### ISSUE TITLE
previousValues -> id result malformed on DELETED subscriptions

### ISSUE THREAD

**Issue by frankdugan3** [prisma/prisma#2847]
**Describe the bug**
When subscribed to `DELETED` events, `previousValues` -> `id` returns the string `CuidGCValue(...)`. (`...` represents the actual ID)

**To Reproduce**

1. Subscribe to `DELETED` and be sure to query `previousValues` with the `id` field:

```graphql
subscription {
  user {
    previousValues {
      id
    }
  }
}
```
2. Delete an entry to trigger subscription.

**Expected behavior**
The `id` field should be the actual ID. I suspect a function is being returned as a string rather than being called somewhere in the code.

**Versions (please complete the following information):**
 - OS: `Fedora 28`
 - `Prisma 1.13.2`

First mentioned in #2824.

**Comment by Enricopv** [comment]
Just commenting to say I am experiencing this issue as well.

**Comment by divyenduz** [comment]
I am able to reproduce this as well. The returned data looks like: 

```
{
  "data": {
    "user": {
      "previousValues": {
        "id": "CuidGCValue(cjkcezgmc00f40884ljcf9asf)"
      }
    }
  }
}
```

**Comment by mavilein** [comment]
Thanks for reporting! 🙏 
I pushed a fix and created a release `1.13.4`. Build artifacts will be available in a few minutes.

**Comment by MitchellMonaghan** [comment]
Hey guys wondering if I am missing something or if this fix is not working. I am currently using a demo server on prisma cloud and UI says it is version 1.18-beta-1. When I lookup 1.18-beta tag in the prisma repo it look like this change is in there (https://github.com/prisma/prisma/commit/ae844618857502a2b9c180c3b3742c6b0b01aedf). In my app I have a subscription for notifications and when I delete a notification I currently still get this:

```json
{
    "data": {
        "notification": {
            "mutation": "DELETED",
            "previousValues": {
                "id": "CuidGCValue(cjmvnu812any60b48oxw07heq)",
                "viewed": false,
                "__typename": "NotificationPreviousValues"
            },
            "node": null,
            "__typename": "NotificationSubscriptionPayload"
        }
    }
}
```

Any help would be great thanks.

**Comment by mavilein** [comment]
Thanks for reporting the issue and your thorough description! 🙏 This has been fixed in `1.18.1`.

**Comment by afrankel-sfdo** [comment]
@mavilein I'm seeing a similar, but slightly different, issue with delete mutation IDs as `StringIdGCValue(ID_HERE)`

Tested against `1.18.1`

---

Response:
```
{  
   "type":"data",
   "id":"1",
   "payload":{  
      "data":{  
         "feedSubscription":{  
            "mutation":"DELETED",
            "node":null,
            "previousValues":{  
               "id":"StringIdGCValue(cjoel023cwjtc0a01bh5awc32)",
               "message":"edited the message! 1542043696120",
               "__typename":"CommentPreviousValues"
            },
            "__typename":"CommentSubscriptionPayload"
         }
      }
   }
}
```

based on a data model of:
```
type Comment {
  id: ID! @unique
  createdAt: DateTime!
  updatedAt: DateTime!
  isPublic: Boolean! @default(value: "false")
  message: String!
  author: User!
  children: [Comment!]! @relation(name: "CommentOnComment", onDelete: CASCADE)
  parent: Comment @relation(name: "CommentOnComment", onDelete: SET_NULL)
}

type User {
  id: ID! @unique
  email: String! @unique
  password: String!
  name: String!
  comments: [Comment!]!
}

```

subscription:
```
type Subscription {
  feedSubscription: CommentSubscriptionPayload
}
```

resolver:
```
const Subscription = {
  feedSubscription: {
    subscribe: (parent, args, ctx, info) => {
      return ctx.db.subscription.comment(
        {
          where: {
            node: {
              isPublic: true
            }
          }
        },
        info
      );
    }
  }
};
```

**Comment by mavilein** [comment]
@afrankel-sfdo : We indeed had one more regression here. Will reopen and fix soon.

**Comment by afrankel-sfdo** [comment]
@mavilein any updates? anyway I can assist?

**Comment by slikts** [comment]
Just ran into this issue as well and worked around it like so:
```js
const [, id] = previousValues.id.match(/\((\w+?)\)/);
```

**Comment by mavilein** [comment]
@afrankel-sfdo : Thanks for pinging. Thought i merged a fix but i didn't. The fix is available in `1.23.4`.

**Comment by afrankel-sfdo** [comment]
@mavilein thanks! Upgraded to `prisma@^1.23.4` (confirmed via yarn.lock), ran `yarn prisma generate` then `yarn prisma deploy`. Restarted the server, but still seeing: `id: "StringIdGCValue(cjqia4yt43o2f0991q6zszwmg)"` in `previousValues` on a `DELETE` mutation. 

Is there some set I'm missing?

**Comment by mavilein** [comment]
@afrankel-sfdo : You just upgraded your Prisma Client dependency. You need to upgrade your Prisma server as well.

**Comment by mavilein** [comment]
@afrankel-sfdo : where did you start your Prisma server? Probably through Docker? If yes, then `docker ps` will tell you what version you are running.

**Comment by afrankel-sfdo** [comment]
@mavilein oh, maybe that's the issue... I'm using the deployed Prisma instance. When will that see an upgrade?

**Comment by mavilein** [comment]
@afrankel-sfdo : Do you mean our public demo clusters?

**Comment by mavilein** [comment]
@afrankel-sfdo : The bugfix will be available within the next hour on those servers.

**Comment by afrankel-sfdo** [comment]
@mavilein looks great, thanks!!

```
{
   "type":"data",
   "id":"1",
   "payload":{
      "data":{
         "feedSubscription":{
            "mutation":"DELETED",
            "node":null,
            "previousValues":{
               "id":"cjqpcb68e08i00a26nfw0v0co",
               "message":"edited the message! 1547047790512",
               "__typename":"CommentPreviousValues"
            },
            "__typename":"CommentSubscriptionPayload"
         }
      }
   }
}
```
