### ISSUE TITLE
Deploying relation name change and explicit back relation is stuck

### ISSUE THREAD

**Issue by marktani** [prisma/prisma#2906]
**Describe the bug**

When adding an implicit backrelational field and changing the relation name at the same time, the deployment will be stuck.

**To Reproduce**
1. Deploy this datamodel:

```graphql
type Category {
    id: ID! @unique
    slug: String! @unique
}

type Project {
    id: ID! @unique
    slug: String! @unique
    category: Category! @relation(name: "Category")
}
```

2. Deploy this datamodel:

```diff
type Category {
    id: ID! @unique
    slug: String! @unique
+   projects: [Project!]! @relation(name: "Category2")

}

type Project {
    id: ID! @unique
    slug: String! @unique
-   category: Category! @relation(name: "Category")
+   category: Category! @relation(name: "Category2")
}
```

3. The deployment is stuck:

```sh
Deploying service `r-2796` to stage `dev2` to server `local` 104ms

Changes:

  Category (Type)
  + Created field `projects` of type `[Relation!]!`

  Project (Type)
  ~ Updated field `category`

  Category (Relation)
  - Deleted relation between undefined and undefined

  Category2 (Relation)
  + Created relation between Category and Project

Applying changes (19/5) ⣟
```

**Expected behavior**

The deployment goes through. The relation was renamed.

**Versions (please complete the following information):**
 - Prisma Server: `prismagraphql/prisma:1.13`

**Additional context**

Originally reported here: #2796. Added to #2018.

**Comment by mavilein** [comment]
Thanks for reporting the issue and your thorough description! 🙏 This has been fixed in `1.18.1`.

**Comment by heymartinadams** [comment]
For some reason, it’s still not working for me with `1.18.1`. Still spinning at `Applying changes`.

![image](https://user-images.githubusercontent.com/11673745/47196517-c18fc980-d315-11e8-9c0a-af7edb843b49.png)

**Comment by marktani** [comment]
Is `1.18.1` your server version, or your CLI version?
The relevant one in this context is the server version 🙂

**Comment by heymartinadams** [comment]
Awesome, @marktani! That did it 🙌🏼
