### ISSUE TITLE
Allow for custom IDs to be submitted in a create-mutation

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#3839]
Prisma currently always generates globally unique IDs for the elements stored in the database. It would be awesome if I could submit my own ID in a `createX`-mutation: `XCreateInput` for a type `X` should have an additional field: `id: ID`.

Open questions:
- It's unclear to me if Prisma should validate that the ID is unique in the DB or if that should be the responsibility of the client that provides the ID.

**Comment by jdspugh** [comment]
I'm currently implementing a mobile database layer for the app I'm working on that handles online and offline modes. Really enjoying graphcool/prisma but now I just found out about this limitation and it seems complicated to work. So I am going to write my own graphql-like database implementation specific for this app instead.

About the open question. Allow this as a setting for each database i.e. if they want ID checking or not. I'm sure there are good use cases for both.

**Comment by joshhopkins** [comment]
Similar case as @jdspugh, need to perform diffs on object hashes – seems redundant to store another `uid` next to the `id` field.

**Comment by do4gr** [comment]
We just merged this feature into the 1.30 alpha. 

The id field will now follow the behaviour laid out here: https://github.com/prisma/prisma/issues/3403. It can now in some cases be provided by the user. Either as a required or an optional field. On the current datamodel v1.0 it will be optional. If the user provides an id, it needs to meet the requirements for valid ids.

1. It has to be unique, which the database will ensure since there are Primary Key constraints on the id columns. In case of a unique violation the user will receive an error and the mutation will be aborted.

2. It needs to fit in the underlying database column. On the SQL connectors this can be either INT, STRING(25) for CUIDs or String(36) for UUIDs. For Mongo this means it has to be a valid ObjectId. This will be validated by Prisma before hitting the database. If this fails the user will receive an error and the mutation will be aborted.

**Comment by jide** [comment]
I tried to upgrade my docker instance to 1.30-alpha, as well as the cli, and I still can't update or create content with an id, using the playground or the new (awesome!) admin, where the id field is disabled. I wiped out everything and my schema is as simple as it can be to test this : 
```gql
type User {
  id: Int! @id(strategy: NONE)
  updatedAt: DateTime! @updatedAt
  createdAt: DateTime! @createdAt
  name: String!
}
```

I have put `prototype: true` in the `PRISMA_CONFIG` part of docker-compose.yml.

You mention that the id can be provided "in some cases", can you be more specific on what cases this would work ?

**Comment by jide** [comment]
Ah it works with ID instead of Int.

**Comment by jide** [comment]
prisma-binding does not reflect the new api atm though.

**Comment by do4gr** [comment]
Yes, sorry for not mentioning this. This feature is not yet propagated to Bindings or the Client. It is implemented only on the server side. You can test it using the playground or by sending queries directly to the API. 

We'll adjust the Client and Bindings as soon as we have some testing feedback.

**Comment by jide** [comment]
If someone wants to try with prisma-binding in the meanwhile, you can manually edit the generated schema and add your id fields, you'll then be able to forward to prisma.

**Comment by nikolasburk** [comment]
I've created a separate issue to track this functionality in the client API: https://github.com/prisma/prisma/issues/4219

**Comment by pantharshit00** [comment]
This has been implemented, closing.
