### ISSUE TITLE
@unique seems not work in MongoDB

### ISSUE THREAD

**Issue by soqt** [prisma/prisma#3855]
```graphql
type User {
    id: ID @id 
    phoneNumber: String @unique 
}
```

unique directive seems not working in MongoDB. I can always generate more than one user with same phone number.

<img width="421" alt="screen shot 2019-01-13 at 7 52 00 pm" src="https://user-images.githubusercontent.com/10392539/51084927-0dafa600-176d-11e9-9ee9-b358b4aba1ea.png">

<img width="994" alt="screen shot 2019-01-13 at 7 51 45 pm" src="https://user-images.githubusercontent.com/10392539/51084932-156f4a80-176d-11e9-9889-a2a0426e0fc8.png">

prisma 1.24.0

**Comment by pantharshit00** [comment]
Hi @soq,

I am unable to reproduce the bug in the latest version of prisma server(ie 1.24.0)

Here is the error msg I get when I try to create a duplicate value item:
![image](https://user-images.githubusercontent.com/22195362/51113857-896f2880-1829-11e9-89fb-a26b7975f448.png)

I also checked the database docker container to make sure only one record is there: 
![image](https://user-images.githubusercontent.com/22195362/51113872-9d1a8f00-1829-11e9-9e1c-44fe20e964cb.png)


I think you are using 1.23 which lacks this functionality. Please upgrade to prisma 1.24 in your docker-compose file. This line defines the prisma version in that file: 
![image](https://user-images.githubusercontent.com/22195362/51114810-66924380-182c-11e9-800b-6d1ee2aaaae2.png)

**Comment by sandorTuranszky** [comment]
I can confirm this issue with `image: prismagraphql/prisma:1.24`
Can create multiple records with the same email

```
type User {
  id: ID! @id
  name: String!
  email: String! @unique
}
```

**Comment by pantharshit00** [comment]
@sandorTuranszky I am still unable to reproduce with your provided datamodel,

![image](https://user-images.githubusercontent.com/22195362/51394333-28fd2580-1b60-11e9-8667-6a0c0ab589bb.png)

Please link a working reproduction 🙏

**Comment by sandorTuranszky** [comment]
I wish I could help you to reproduce it. Maybe if you make a fresh install and use MongoDB Atlas free plan - this is what I did.

I ran `prisma init` and followed instructions. Then added `email: String! @unique` to the existing `datamodel.prisma` file that was auto-generated and deployed it. 
In the graphql playground, I can create multiple records with the same email

**Comment by pantharshit00** [comment]
I guess you are still using 1.23 somehow. I testing this one mongo 4.0 as well and everything works as expected. Please contact me on slack(slack.prisma.io) so that I can help debug the problems. Thanks 🙏

**Comment by guimochila** [comment]
This has been fixed? I'm having the same issue on **prismagraphql/prisma:1.25.3**. 
![code](https://user-images.githubusercontent.com/4387043/51785711-218add00-215b-11e9-8989-4424ccc07c6b.png)

Mongodb version: v4.0.5

I can create multiple users with the same email. Thanks guys!

**Comment by pantharshit00** [comment]
cc @do4gr

**Comment by sandorTuranszky** [comment]
The issue persists for 1.24 version

**Comment by sandorTuranszky** [comment]
Just for the record
Using the playground that comes with `"apollo-server-express": "^1.3.6",` I am getting `"message": "Email taken"` when saving an existing email.  However, with Prisma playground `:4466` I can save the same email multiple times.

**Comment by do4gr** [comment]
I tried reproducing this locally with Prisma 1.25.4 against Mongo 3.6 and Mongo 4.0. In both cases I got the expected unique constraint error. 

Can you check your Mongo instance whether there is actually a unique constraint being generated on the correct field? I'm using Robo 3T here, email is the unique field. And it shows a unique index  (email_U) on the db level for that field which is correct. 

<img width="663" alt="bildschirmfoto 2019-01-29 um 17 52 36" src="https://user-images.githubusercontent.com/16278407/51925256-f3bdc680-23ee-11e9-8452-5f27181a3fd3.png">

**Comment by guimochila** [comment]
@do4gr After restarting the docker compose and also the application, it worked. Not sure what was the exactly issue. Thanks 👏.

**Comment by sandorTuranszky** [comment]
@do4gr I am using MongoDb Atlas and there is no `email_U` index created. MongoDb 4.0.5
<img width="1249" alt="index" src="https://user-images.githubusercontent.com/11644015/51933546-d5ad9180-2401-11e9-957f-9be08181e28f.png">

**Comment by sandorTuranszky** [comment]
Mongod DB Atlas `4.0.5`, `prisma:1.25` - issue is gone! Everything works as expected!

**Comment by israelglar** [comment]
This error is still happening on version 1.26.6.

The steps to reproduce:
> I ran `prisma init` and followed instructions. Then added `email: String! @unique` to the existing `datamodel.prisma` file that was auto-generated and deployed it.
> In the graphql playground, I can create multiple records with the same email

The catch here is to add the @unique constraint after a initial deploy and after adding the constraint run `prisma deploy` again.

The @unique works for all fields that already had it on the first deploy, but after "redeploy" the new @unique contraints doesn't work.

But if we stop the prisma docker container and run it again, all the constraints work. but the problem continues. If we add a new constraint and redeploy, the new constraint doesn't work

**Comment by do4gr** [comment]
Thanks for the detailed description @israelglar, I'll look into it next week.

**Comment by soqt** [comment]
Although I fixed my issue last time, but it occurs again in version 1.27.3.

**Comment by kolengri** [comment]
confirm, same problem.

**Comment by seklyza** [comment]
yes, here too, prisma 1.27.4

**Comment by do4gr** [comment]
@israelglar description really helped! We were not setting/unsetting the unique constraint in the case of an update to the field, only during initial creates. I fixed that now, but you will have to remove and then add the @unique from fields in order for Prisma to recognise the change and add the constraint. 

Please test and comment if you're still running into problems.

**Comment by leafyshark** [comment]
I have this same issue, however, the @unique directive triggers the constraint error with every field apart from email or mail. 

For example, when user enters their “name” on the ‘name: String! @unique’ field, the error is triggered. However, when the field is ‘email: String! @unique’ then multiple of the same email can be created with no error shown. I am on latest version of prisma (1.30.02 I think). docker-compose file is up to date with this version too. Using mongoDB connector. Any ideas why this is still happening?

**Comment by pantharshit00** [comment]
For anyone still experiencing this, please open a new issue with a minimal reproduction.

**Comment by hbarve1** [comment]
MONGODB_VERSION=4.0.10

PRISMA_VERSION=1.34

```
type User @db(name: "users") {
  id: ID! @id
  name: String!
  email: String! @unique
  password: String!
}
```

I'm also facing the same issue, a user with unique email constrain, still it is not showing any error.

**Comment by gustawdaniel** [comment]
I experienced this error in one collection but in second it works great.

Expected:

```
db.collection.getIndexes()
```

should have 

```
    {
		"v" : 2,
		"unique" : true,
		"key" : {
			"email" : 1
		},
		"name" : "email_U",
		"ns" : "default_default.User",
		"sparse" : true
	}
```

But it worked on my local environment. How I debugged? 

```
docker-compose up
``` 

on server and I saw error on server

```
{"key":"error/handled","requestId":"local:cjylx3hc200uk07020vmv4etb","payload":{"exception":"com.prisma.deploy.schema.AuthFailure: No 'Authorization' header provided.","query":"{\n        listProjects {\n          name\n        }\n      }","variables":"{}","code":"3015","stack_trace":"com.prisma.deploy.schema.SchemaBuilderImpl.verifyAuthOrThrow(SchemaBuilder.scala:314)\\n com.prisma.deploy.schema.SchemaBuilderImpl.$anonfun$listProjectsField$1(SchemaBuilder.scala:108)\\n sangria.execution.Resolver.resolveField(Resolver.scala:1024)\\n sangria.execution.Resolver.$anonfun$collectActionsPar$1(Resolver.scala:445)\\n scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:156)\\n scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:156)\\n scala.collection.Iterator.foreach(Iterator.scala:937)\\n scala.collection.Iterator.foreach$(Iterator.scala:937)\\n scala.collection.AbstractIterator.foreach(Iterator.scala:1425)\\n scala.collection.IterableLike.foreach(IterableLike.scala:70)\\n scala.collection.IterableLike.foreach$(IterableLike.scala:69)\\n scala.collection.AbstractIterable.foreach(Iterable.scala:54)\\n scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:156)\\n scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:154)\\n scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)\\n sangria.execution.Resolver.collectActionsPar(Resolver.scala:439)\\n sangria.execution.Resolver.resolveFieldsPar(Resolver.scala:45)\\n sangria.execution.Executor.executeOperation(Executor.scala:155)\\n sangria.execution.Executor.$anonfun$execute$7(Executor.scala:97)\\n scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)\\n scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)\\n scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)\\n akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)\\n akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)\\n scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)\\n scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)\\n akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)\\n akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)\\n akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)\\n akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\\n akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\\n akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\\n akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)","message":"No 'Authorization' header provided."}}
```

but no info about this on my local computed on command 

```
prisma deploy
```

This is probably connected with https://github.com/prisma/prisma/issues/4284

Even when I disabled `managementApiSecret` described ![here](https://www.prisma.io/docs/prisma-server/authentication-and-security-kke4/#management-api-secret) i did not fix problem. 

I removed `email: String! @unique` from my model and saw these logs

```
prisma_1  | [Debug] Scheduling deployment for project default_default
mongo_1   | 2019-07-27T19:45:32.464+0000 I COMMAND  [conn4] CMD: dropIndexes default_default.Invitation
prisma_1  | Encountered exception while applying migration. Rolling back. com.mongodb.MongoCommandException: Command failed with error 27 (IndexNotFound): 'index not found with name [email_U]' on server mongo:27017. The full response is { "nIndexesWas" : 3, "ok" : 0.0, "errmsg" : "index not found with name [email_U]", "code" : 27, "codeName" : "IndexNotFound" }
prisma_1  | com.mongodb.MongoCommandException: Command failed with error 27 (IndexNotFound): 'index not found with name [email_U]' on server mongo:27017. The full response is { "nIndexesWas" : 3, "ok" : 0.0, "errmsg" : "index not found with name [email_U]", "code" : 27, "codeName" : "IndexNotFound" }
prisma_1  | 	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:179)
prisma_1  | 	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:370)
prisma_1  | 	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:356)
prisma_1  | 	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:651)
prisma_1  | 	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:618)
prisma_1  | 	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:494)
prisma_1  | 	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:491)
prisma_1  | 	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$BasicCompletionHandler.completed(AsynchronousSocketChannelStream.java:237)
prisma_1  | 	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$BasicCompletionHandler.completed(AsynchronousSocketChannelStream.java:220)
prisma_1  | 	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126)
prisma_1  | 	at sun.nio.ch.Invoker.invokeDirect(Invoker.java:157)
prisma_1  | 	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(UnixAsynchronousSocketChannelImpl.java:553)
prisma_1  | 	at sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:276)
prisma_1  | 	at sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:297)
prisma_1  | 	at com.mongodb.internal.connection.AsynchronousSocketChannelStream.readAsync(AsynchronousSocketChannelStream.java:132)
prisma_1  | 	at com.mongodb.internal.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:491)
prisma_1  | 	at com.mongodb.internal.connection.InternalStreamConnection.access$1000(InternalStreamConnection.java:74)
prisma_1  | 	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:608)
prisma_1  | 	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:593)
prisma_1  | 	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:494)
prisma_1  | 	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:491)
prisma_1  | 	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$BasicCompletionHandler.completed(AsynchronousSocketChannelStream.java:237)
prisma_1  | 	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$BasicCompletionHandler.completed(AsynchronousSocketChannelStream.java:220)
prisma_1  | 	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126)
prisma_1  | 	at sun.nio.ch.Invoker.invokeDirect(Invoker.java:157)
prisma_1  | 	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(UnixAsynchronousSocketChannelImpl.java:553)
prisma_1  | 	at sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:276)
prisma_1  | 	at sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:297)
prisma_1  | 	at com.mongodb.internal.connection.AsynchronousSocketChannelStream.readAsync(AsynchronousSocketChannelStream.java:132)
prisma_1  | 	at com.mongodb.internal.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:491)
prisma_1  | 	at com.mongodb.internal.connection.InternalStreamConnection.access$1000(InternalStreamConnection.java:74)
prisma_1  | 	at com.mongodb.internal.connection.InternalStreamConnection$2.onResult(InternalStreamConnection.java:356)
prisma_1  | 	at com.mongodb.internal.connection.InternalStreamConnection$2.onResult(InternalStreamConnection.java:345)
prisma_1  | 	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
prisma_1  | 	at com.mongodb.internal.connection.InternalStreamConnection$3.completed(InternalStreamConnection.java:448)
prisma_1  | 	at com.mongodb.internal.connection.InternalStreamConnection$3.completed(InternalStreamConnection.java:445)
prisma_1  | 	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$1.completed(AsynchronousSocketChannelStream.java:118)
prisma_1  | 	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$1.completed(AsynchronousSocketChannelStream.java:112)
prisma_1  | 	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$2.completed(AsynchronousSocketChannelStream.java:183)
prisma_1  | 	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$2.completed(AsynchronousSocketChannelStream.java:177)
prisma_1  | 	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$AsyncWritableByteChannelAdapter$WriteCompletionHandler.completed(AsynchronousSocketChannelStream.java:209)
prisma_1  | 	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$AsyncWritableByteChannelAdapter$WriteCompletionHandler.completed(AsynchronousSocketChannelStream.java:200)
prisma_1  | 	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126)
prisma_1  | 	at sun.nio.ch.Invoker$2.run(Invoker.java:218)
prisma_1  | 	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
prisma_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
prisma_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
prisma_1  | 	at java.lang.Thread.run(Thread.java:748)
prisma_1  | [Debug] Applied migration for project default_default
mongo_1   | 2019-07-27T19:45:32.598+0000 I NETWORK  [listener] connection accepted from 172.19.0.7:42106 #6 (4 connections now open)
mongo_1   | 2019-07-27T19:45:32.599+0000 I NETWORK  [conn6] received client metadata from 172.19.0.7:42106 conn6: { driver: { name: "mongo-java-driver|mongo-scala-driver", version: "3.8.0-beta3-44-g1ff4ce53c-dirty|2.4.0" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "4.15.0-50-generic" }, platform: "Java/Oracle Corporation/1.8.0_202-b08|Scala/2.12.6" }
mongo_1   | 2019-07-27T19:45:32.602+0000 I ACCESS   [conn6] Successfully authenticated as principal prisma on admin from client 172.19.0.7:42106
prisma_1  | [INFO] Opened connection [connectionId{localValue:3, serverValue:6}] to mongo:27017
```

Then I removed all collection (in my case `invitation`) and had on docker

```
prisma_1  | [Debug] Scheduling deployment for project default_default
prisma_1  | [Debug] Applied migration for project default_default
```

and 

```
Changes:

  User (Type)
  - Deleted field `createdInvitations`

  Team (Type)
  - Deleted field `openInvitations`

  Invitation (Type)
  - Deleted type `Invitation`

  TeamInvitationsInvitator (Relation)
  - Deleted relation between undefined and undefined

  TeamInvitations (Relation)
  - Deleted relation between undefined and undefined
```

on local machine. So now I removed collectio 

```
 db.Invitation.getIndexes()
```

Mongo responded

```
mongo_1   | 2019-07-27T19:51:18.244+0000 I COMMAND  [conn5] CMD: drop default_default.Invitation
mongo_1   | 2019-07-27T19:51:18.248+0000 I STORAGE  [conn5] Finishing collection drop for default_default.Invitation (a423a515-8dce-463a-9558-6d2f8a8cb9a2).
```

And added again `Invitation` to model

I executed `prisma deploy` again

```
Changes:

  Invitation (Type)
  + Created type `Invitation`
  + Created field `id` of type `ID!`
  + Created field `invitedBy` of type `User!`
  + Created field `invitedTo` of type `Team`
  + Created field `invitedAs` of type `Enum!`
  + Created field `email` of type `String!`
  + Created field `createdAt` of type `DateTime!`

  User (Type)
  + Created field `createdInvitations` of type `[Invitation!]!`

  Team (Type)
  + Created field `openInvitations` of type `[Invitation!]!`

  TeamInvitationsInvitator (Relation)
  + Created an inline relation between `Invitation` and `User` in the column `invitedBy` of table `Invitation`

  TeamInvitations (Relation)
  + Created an inline relation between `Invitation` and `Team` in the column `invitedTo` of table `Invitation`
```

and on docker

```
prisma_1  | [Debug] Initializing deployment worker for default_default
prisma_1  | [Debug] Scheduling deployment for project default_default
mongo_1   | 2019-07-27T19:53:25.517+0000 I STORAGE  [conn6] createCollection: default_default.Invitation with generated UUID: f90d5582-ddb5-41ed-a60f-cbbc32b121a8
mongo_1   | 2019-07-27T19:53:25.577+0000 I INDEX    [conn6] build index on: default_default.Invitation properties: { v: 2, unique: true, key: { email: 1 }, name: "email_U", ns: "default_default.Invitation", sparse: true }
mongo_1   | 2019-07-27T19:53:25.579+0000 I INDEX    [conn6] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongo_1   | 2019-07-27T19:53:25.582+0000 I INDEX    [conn6] build index done.  scanned 0 total records. 0 secs
mongo_1   | 2019-07-27T19:53:25.601+0000 I INDEX    [conn6] build index on: default_default.Invitation properties: { v: 2, key: { invitedBy: 1 }, name: "invitedBy_R", ns: "default_default.Invitation" }
mongo_1   | 2019-07-27T19:53:25.602+0000 I INDEX    [conn6] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongo_1   | 2019-07-27T19:53:25.604+0000 I INDEX    [conn6] build index done.  scanned 0 total records. 0 secs
mongo_1   | 2019-07-27T19:53:25.615+0000 I INDEX    [conn6] build index on: default_default.Invitation properties: { v: 2, key: { invitedTo: 1 }, name: "invitedTo_R", ns: "default_default.Invitation" }
mongo_1   | 2019-07-27T19:53:25.616+0000 I INDEX    [conn6] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongo_1   | 2019-07-27T19:53:25.617+0000 I INDEX    [conn6] build index done.  scanned 0 total records. 0 secs
prisma_1  | [Debug] Applied migration for project default_default
```

Finally I have on mongo

```
db.Invitation.getIndexes()
[
	{
		"v" : 2,
		"key" : {
			"_id" : 1
		},
		"name" : "_id_",
		"ns" : "default_default.Invitation"
	},
	{
		"v" : 2,
		"unique" : true,
		"key" : {
			"email" : 1
		},
		"name" : "email_U",
		"ns" : "default_default.Invitation",
		"sparse" : true
	},
	{
		"v" : 2,
		"key" : {
			"invitedBy" : 1
		},
		"name" : "invitedBy_R",
		"ns" : "default_default.Invitation"
	},
	{
		"v" : 2,
		"key" : {
			"invitedTo" : 1
		},
		"name" : "invitedTo_R",
		"ns" : "default_default.Invitation"
	}
]
```

So it is fixed.

# Summary

Working solution:
- check what tells `docker-compose up`
- remove collection form prisma model 
- drop mongo collection (you can create backup and save your data)
- create prisma model again
- prisma deploy 

Note: I experienced this error after using command `prisma deploy --no-migrate`

**Comment by Mhmdabed11** [comment]
Still facing same issue. I am using
`Mongo v3.6`
`Prisma v1.34`
I can create multiple users with same email.
