### ISSUE TITLE
Error creating types using @id and @sequence

### ISSUE THREAD

**Issue by frandiox** [prisma/prisma#4412]
**Describe the bug**

I tried to create a type using the new datamodel v1.1:

```gql
type AtomicRefNumber {
  id: Int!
    @id(strategy: SEQUENCE)
    @sequence(name: "AtomicRefNumber", initialValue: 10000, allocationSize: 1)
}
```

<details>
<summary>This part is fixed already fixed</summary>

Note that the id field needs to be called `id`. If it's called `value` instead, the generated Prisma schema would look like this:

```gql
createAtomicRefNumber(data: AtomicRefNumberCreateInput!): AtomicRefNumber!
...
input AtomicRefNumberCreateInput {
  value: Int!
}
```

This doesn't look correct because the id is supposed to be generated automatically in a sequence but the "create" mutation is asking for the id.

Changing the id field name form `value` to `id` generates the schema as expected.

</details>

The generated create mutation looks like this:

```gql
createAtomicRefNumber: AtomicRefNumber!
```

However, when trying to perform this mutation by using either `prisma-binding` or GraphQL playground:

```gql
mutation {
  createAtomicRefNumber {
    id
  }
}
```

=> `Whoops. Looks like an internal server error. Search your server logs for request ID: us1:cjumv2n334dmk0b12fony61sx"`

I'm using the demo servers (US) so I can't see the logs.

Seems like a bug but perhaps I'm doing something wrong.

**Expected behavior**

It returns a new incremental ID (starting at 10000, increasing 1 by 1) in the field where `@id` is assigned.

**Versions (please complete the following information):**
 - Connector: demo-servers
 - Prisma Server: `1.32-beta`
 - `prisma` CLI: `prisma/1.26.6 (darwin-x64) node-v10.13.0`
 - OS: `OS X Mojave` 
 - other dependencies: `prisma-binding`

**Comment by pantharshit00** [comment]
Hi @frandiox 

This is a bug that we have fixed in the stable release. We will back merge the changes to beta in the next release so demo server's dont have it yet.

See: https://github.com/prisma/prisma/releases/tag/1.31.1

**Comment by pantharshit00** [comment]
Closing as it already fixed :)

**Comment by frandiox** [comment]
@pantharshit00 Thanks! Did you check the second part of the issue? I tried with `id` name and was still giving problems. Perhaps is still related to the name, not sure.

**Comment by frandiox** [comment]
@pantharshit00 Just noticed the title of this issue is for the part that was already fixed. Is there any news for the error when using `@id @sequence` together?

**Comment by pantharshit00** [comment]
@frandiox 
I should work now. Please give it a try again with a new service in the demo server or locally with the latest version

**Comment by frandiox** [comment]
@pantharshit00 Thanks! Unfortunately it still throws the same `Whoops. Looks like an internal server error. Search your server logs for request ID: us1:cjvi8jftu192r0b54i6285iu` 😢 

I deleted the service and created it again to test that in `prisma-us1`.

**Comment by darthmeme** [comment]
Hey! I'm also having the same issue with using `@sequence`. Are there any updates?
