### ISSUE TITLE
Postgres parameterized interval is passed incorrectly in raw query

### ISSUE THREAD

**Issue by Sytten** [prisma/prisma#4647]
## Bug description
Consider the following query:
```typescript
  const endDate = new Date('2020-12-15T06:00:00');
  const startDate = new Date('2020-12-20T06:00:00Z');
  const interval = '1 day';

  const result = await ctx.prisma.$queryRaw`
    SELECT
      start_ts AS timestamp,
      COUNT(*) AS value
    FROM
      generate_series(${startDate}::TIMESTAMP, ${endDate}::TIMESTAMP, ${interval}::INTERVAL) AS start_ts
    LEFT JOIN "Ticket" AS t ON t."createdAt" >= start_ts AND t."createdAt" < start_ts + ${interval}::INTERVAL
    GROUP by start_ts
    ORDER BY start_ts
  `;
```
This should work, but fails. It only works if the `interval` is first casted to `TEXT` and then to `INTERVAL`:
```
${interval}::TEXT::INTERVAL
```

## Expected behavior

It should be possible to cast it directly to interval.

## Prisma information

```
@prisma/cli          : 2.12.1
@prisma/client       : 2.12.1
Current platform     : darwin
Query Engine         : query-engine cf0680a1bfe8d5e743dc659cc7f08009f9587d58 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli cf0680a1bfe8d5e743dc659cc7f08009f9587d58 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core cf0680a1bfe8d5e743dc659cc7f08009f9587d58 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt cf0680a1bfe8d5e743dc659cc7f08009f9587d58 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.322.0
```

**Comment by pantharshit00** [comment]
Hey @Sytten 

Can you please share the sql schema of `Ticket` table so that I can try a reliable reproduction? Thanks!

**Comment by Sytten** [comment]
This was confirmed as a bug in the pg driver, but here is a (really) simplified version of it:
```prisma
model Ticket {
  id           Int          @id @default(autoincrement())
  createdAt    DateTime     @default(now())
}
```

**Comment by pantharshit00** [comment]
I can confirm this one. Error returned from the engine: `Raw query failed. Code: `08P01`. Message: `db error: ERROR: insufficient data left in message``

Version used: 
```
@prisma/cli          : 2.14.0-dev.45
@prisma/client       : 2.14.0-dev.45
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 85cf7930a5fc63cd99fa483153fd33cb35d49cfa (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 85cf7930a5fc63cd99fa483153fd33cb35d49cfa (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 85cf7930a5fc63cd99fa483153fd33cb35d49cfa (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 85cf7930a5fc63cd99fa483153fd33cb35d49cfa (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.332.0

```

**Comment by pantharshit00** [comment]
This is still reproducible in `2.22.0-dev.55`.

**Comment by JClackett** [comment]
Also having issues with this query

```ts
await prisma.$queryRaw`SELECT "createdAt"::date, COUNT("createdAt") FROM "User"
      WHERE "createdAt" BETWEEN NOW() - INTERVAL '${days} DAYS' AND NOW()
      GROUP BY "createdAt"::date
      ORDER BY "createdAt"`
```

adding the days variable as a dynamic value causes an issue with this error:

```
prisma:query SELECT "createdAt"::date, COUNT("createdAt") FROM "ContactRequest"
      WHERE "createdAt" BETWEEN NOW() - INTERVAL '$1 DAYS' AND NOW()
      GROUP BY "createdAt"::date
      ORDER BY "createdAt"
[ERROR]  PrismaClientKnownRequestError3 [PrismaClientKnownRequestError]:
Invalid `prisma.queryRaw()` invocation:


  Your raw query had an incorrect number of parameters. Expected: `0`, actual: `1`.

{
  code: 'P1016',
  clientVersion: '2.29.1',
  meta: { expected: 0, actual: 1 }
}
```

It doesn't like the interval value being dynamic it seems as if I just pass a regular number in there its fine, any ideas?

**Comment by elie222** [comment]
@JClackett this workaround works from the original message:

```
where date > current_date - ${period}::TEXT::INTERVAL
```

Ran into the same issue. Still a problem but double casting not the end of the world. Thanks for the solution @Sytten.

**Comment by emcpow2** [comment]
Also getting `Raw query failed. Code: `08P01`. Message: `db error: ERROR: insufficient data left in message` error in this case

```typescript
        await this.prismaService.$queryRaw`
          SELECT "id"
          FROM "entities"
          WHERE "id" = ${entityId} FOR UPDATE
          `;
```

**Comment by Weakky** [comment]
Hey,

This issue was fixed by https://github.com/prisma/prisma-engines/pull/2847. It will be available in the next release under the `improvedQueryRaw` feature flag.

Beware that enabling `improvedQueryRaw` is a breaking change. Release notes will contain information as to how to upgrade (so will the documentation).

Thanks for reporting 🙏

**Comment by bawahakim** [comment]
@Weakky thanks that solved my problem! 

For those trying with the `improvedQueryRaw`, this worked for me, to get a variable number of dates after current date

`WHERE DATE("completedAt") >= CURRENT_DATE - ${days + " day"}::interval`

**Comment by khangho2511** [comment]
this problem still happens but after restarting the server it is good.
