### ISSUE TITLE
Generate TEXT fields from String

### ISSUE THREAD

**Issue by nlarusstone** [prisma/prisma#4713]
Hi,

I’m using `prisma2 lift` to generate my database, but it’s generating all my String fields as `VARCHAR` with size 191. Unfortunately, when I go to populate these fields, some of my data has more than 191 characters. Is there a way I can get `prisma2 lift` to generate `TEXT` fields or specify my desired length of `VARCHAR`?

Thanks!

**Comment by sohailhaider** [comment]
Any update on this guys? Link is spec ready?

**Comment by thebiglabasky** [comment]
Hi @sohailhaider 
We released a preview of [extended native types support](https://www.prisma.io/docs/concepts/components/preview-features/native-types/) which we're working on integrating with migrate this quarter. This should allow to have more control over this.

**Comment by albertoperdomo** [comment]
Prisma Migrate (in Preview) now supports native types (in Preview) starting from 2.15.0.

You should be able to customize your String fields to use different underlying columns types, e.g. `varchar(50)`, `text`, etc. Docs are available [here](https://www.prisma.io/docs/concepts/components/preview-features/native-types).

Please share your feedback [here](https://github.com/prisma/prisma/issues/4045). Closing.

**Comment by calidion** [comment]
@albertoperdomo 
Still not working.

```
The provided value for the column is too long for the column's type. Column: content
```
I have enabled preview native types.

**Comment by calidion** [comment]
it seems unacceptable to change field length for existing data.

```
You are about to alter the column `cover` on the `thread` table, which contains 264 non-null values. The data in that column will be cast from `VarChar(255)` to `VarChar(191)`
```

**Comment by tomhoule** [comment]
@calidion can you elaborate?

**Comment by richellyitalo** [comment]
```
model MyModel {
 ...
 field String @db.Text
 ...
}
```
