### ISSUE TITLE
Missing stack trace in prisma.$transaction

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma#4815]
## Bug description

When running this:

```js
const transactionUpdate = prisma.transaction.create({
	data: {
		// ...
		amount: amount,
		user: {
			connect: {
				id: userId,
			},
		},
	},
})

const userUpdate = prisma.user.update({
	where: { id: userId },
	data: {
		balance: {
			increment: amount,
		},
	},
})

await prisma.$transaction([transactionUpdate, userUpdate])
```

when `amount` is unset, it results in the following error:

```
Error: Error in query graph construction: QueryParserError(QueryParserError { path: QueryPath { segments: ["Mutation", "createOneTransaction", "data", "TransactionCreateInput", "amount"] }, error_kind: RequiredValueNotSetError })
    at /Users/luca/projects/ws-backend/node_modules/@prisma/client/runtime/index.js:27330:19
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

This is really frustrating since I have no idea where in my code this error occurred.

## Environment & setup

- OS: 
- Database: 
- Node.js version: 
- Prisma version: 2.13.0

```
@prisma/cli          : 2.13.0
@prisma/client       : 2.13.0
Current platform     : darwin
Query Engine         : query-engine 833ab05d2a20e822f6736a39a27de4fc8f6b3e49 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 833ab05d2a20e822f6736a39a27de4fc8f6b3e49 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 833ab05d2a20e822f6736a39a27de4fc8f6b3e49 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 833ab05d2a20e822f6736a39a27de4fc8f6b3e49 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.329.0
✨  Done in 2.60s.
```

**Comment by timsuchanek** [comment]
The stack trace is missing due to the Node.js async error handling, Prisma Client can't fix that.
However, if you provide a reproduction, we can look into it and see if there's something to improve.

**Comment by steebchen** [comment]
Basically this happens whenever you use prisma.$transaction. 

```ts
import { PrismaClient } from '@prisma/client'

const client = new PrismaClient()

async function init() {
	const userID = "123"

	const userUpdate = client.user.update({
		where: { id: userID },
		data: {
			email: "new",
		},
	})

	const postCreate = client.post.create({
		data: {
			title: "hi",
			content: "what up",
			author: {
				connect: {
					id: userID,
				},
			},
		},
	})

	await client.$transaction([userUpdate, postCreate])
}

init().catch((err) => {
	console.log(err)
	process.exit(1)
}).then((err) => {
	client.$disconnect()
	process.exit(0)
})
```

```prisma
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id       String  @id @default(cuid())
  email    String  @unique
  username String
  name     String?

  posts    Post[]
}

model Post {
  id      String  @id @default(cuid())
  title   String
  content String?

  author   User   @relation(fields: [authorID], references: [id])
  authorID String
}
```

I also pushed an example project to https://github.com/steebchen/prisma-stacktrace-reproduction.

**Comment by pantharshit00** [comment]
We still don't ship proper stacktraces. 
![image](https://user-images.githubusercontent.com/22195362/119278903-f559cb00-bc45-11eb-8cb4-f31fbb941a5a.png)

**Comment by cbuchacher** [comment]
Note that Prisma does have the stack trace of the call site. It could potentially add to the Error object. It does already add some information in dev mode: https://github.com/prisma/prisma/pull/8646.

**Comment by eduhenke** [comment]
We are needing this because we are integrating with an APM solution, and all queries we perform have a `.$transaction` wrapped in them([because we also need RLS-support](https://github.com/prisma/prisma/issues/5128#issuecomment-921179713))
