### ISSUE TITLE
`prisma generate` fails when using pnpm workspaces because it tries to install prisma dependencies with npm or yarn

### ISSUE THREAD

**Issue by keyworks** [prisma/prisma#5340]
## Bug description

`prisma migrate dev` appears to be running npm to install `@prisma/cli` but it fails since my project is a pnpm project.

## How to reproduce

1. Set up your repo to use pnpm workspaces and `workspace:` protocol in package.json (see https://pnpm.js.org/en/workspaces)
2. Write a schema.
3. Run the initial migration: `pnpx prisma migrate dev --name init --preview-feature`  

I get the following error:
```
myapp (master *) $ pnpx prisma migrate dev --name init --preview-feature
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "dev.db" at "file:./dev.db"

SQLite database dev.db created at file:./dev.db

The following migration(s) have been created and applied from new schema changes:

migrations/
  └─ 20210129014823_init/
    └─ migration.sql

Running generate... (Use --skip-generate to skip the generators)
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:^0.4.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jkim/.npm/_logs/2021-01-29T01_48_26_656Z-debug.log
Error: Command failed with exit code 1: npm install -D @prisma/cli@2.15.0
```

## Expected behavior

No error

## Environment & setup

- OS: MacOS
- Database: SQLite
- Node.js version: v10.22.0
- Prisma version: 2.15.0

**Comment by keyworks** [comment]
Actually I just got past the issue by just manual installing @prisma/client in my local project. I ran: `pnpm add @prisma/client`.

**Comment by pantharshit00** [comment]
Looks like we always use npm to install the client package if it is missing. Workaround should suffice here for now but we should recheck this assumption in code.

**Comment by pantharshit00** [comment]
This is still reproducible, we should add a special case for pnpm

**Comment by PabloSzx** [comment]
@keyworks could you confirm this issue is fixed using these versions of prisma?

I personally tested in a couple projects and everything seems to work correctly now

```
"prisma": "2.27.0-integration-fix-sdk-pnpm.1",
"@prisma/client": "2.27.0-integration-fix-sdk-pnpm.1",
```

**Comment by keyworks** [comment]
Still doesn't seem to be working for me:

```
$ pnpx prisma migrate dev --name init
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "dev" at "127.0.0.1:3306"

Already in sync, no schema change or pending migration was found.

Running generate... (Use --skip-generate to skip the generators)
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:^0.4.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/itp-docker/.npm/_logs/2021-06-30T17_09_15_639Z-debug.log
Error: Command failed with exit code 1: npm install -D prisma@2.27.0-integration-fix-sdk-pnpm.1
```

It appears to be still running `npm install` instead of `pnpm install`. 

This is my setup:

```
$ pnpx prisma --version
Environment variables loaded from .env
prisma               : 2.27.0-integration-fix-sdk-pnpm.1
@prisma/client       : Not found
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 6f7f670adbb07fd4b8862c6d2bcb8c4703065918 (at node_modules/.pnpm/@prisma/engines@2.27.0-2.6f7f670adbb07fd4b8862c6d2bcb8c4703065918/node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 6f7f670adbb07fd4b8862c6d2bcb8c4703065918 (at node_modules/.pnpm/@prisma/engines@2.27.0-2.6f7f670adbb07fd4b8862c6d2bcb8c4703065918/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 6f7f670adbb07fd4b8862c6d2bcb8c4703065918 (at node_modules/.pnpm/@prisma/engines@2.27.0-2.6f7f670adbb07fd4b8862c6d2bcb8c4703065918/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 6f7f670adbb07fd4b8862c6d2bcb8c4703065918 (at node_modules/.pnpm/@prisma/engines@2.27.0-2.6f7f670adbb07fd4b8862c6d2bcb8c4703065918/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : 6f7f670adbb07fd4b8862c6d2bcb8c4703065918
Studio               : 0.408.0
```

**Comment by PabloSzx** [comment]
@keyworks I don't know what to tell you, I've tested it in monorepo projects with the "monorepo:" protocol and everything works fine, maybe prisma/client has to be installed?

![image](https://user-images.githubusercontent.com/8672915/124004500-1381bc00-d9a6-11eb-8ee9-923a7b968ae9.png)

![image](https://user-images.githubusercontent.com/8672915/124004582-27c5b900-d9a6-11eb-882d-6ef1fe95f709.png)

You will need to actually create a repo with the issue and not only instructions

**Comment by millsp** [comment]
Usually, we attempt an install when the `@prisma/client` is not found, which is the case for @keyworks
```
@prisma/client       : Not found
```
Our current logic could certainly be improved. What we do is that we check if `yarn` is installed, if yes then we run `yarn add @prisma/client`, if not then we run `npm install @prisma/client`. So `pnpm` is not covered here.

So my next question is, what happens if I have `npm`, `pnpm` and `yarn` installed all at once, how would we know which package manager to use? My first idea is that we would try to detect how is this running in the first place (via `pnpx`, `npx`, or `yarn`). This is currently possible with:
```
process.env.npm_execpath
process.env.npm_config_user_agent
```
Which for `yarn` yields something like 
```
/home/millsp/.npm-global/lib/node_modules/yarn/bin/yarn.js
yarn/1.22.10 npm/? node/v14.16.0 linux x64
```
However, I've seen folks using `yarn`, or `pnpm` but run their commands with `npx`. For such scenarios, the above logic would not work (we need to make it more resilient). So the idea is to override this logic if we find existing lock files:
* use `yarn` if `yarn.lock` and `node_modules/.yarn-inytegrity`
* use `pnpm` if `pnpm-lock.yaml` and `node_modules/.modules.yml`
* use `npm` if `package-lock.json` and `node_modules/.package-lock.json`

**Comment by keyworks** [comment]
@PabloSzx Here's a minimal repro: https://github.com/keyworks/prisma-issue-5340

It's slightly different error behaviour than the one I originally reported but the root cause is the same. When I try to run a migration, it runs `npm` instead of `pnpm` which my repo uses.

**Comment by millsp** [comment]
When I run your repro, and running `pnpm i` before hand, it works well. But if I skip that step, I can reproduce what you've experienced when running `pnpx prisma migrate`. Can you confirm this?

So I assume that you are using `prisma` installed globally, then we attempt an install when you run  (because we need to install `@prisma/client` in your project).

On your repro, you show that `pnpx prisma --version` is `2.26.0`, could you please re-run that command in your fresh repro? Thanks

**Comment by keyworks** [comment]
@millsp My apologies, I wrote this in such a rush I made some mistakes in the repro steps. 

I updated the `pnpx prisma --version` output in the README.md (I originally accidentally tested with 2.26 so I pasted the wrong output and forgot to update it)

I removed `@prisma/client` dependency in package.json. This is probably why it was working for you initially. It is not supposed to be there and I accidentally committed it. 

Hopefully you should be able to repro consistently now.

**Comment by millsp** [comment]
No worries :) Thanks! Indeed, if we don't find the `@prisma/client`, we attempt to install it. Once this is issue is fixed, the expected behavior is that we modify your `package.json` on your behalf (as it is the case for `yarn` and `npm` users).

**Comment by bryanmig** [comment]
I can confirm this fixes the problem:

```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (2.27.0-integration-fix-sdk-pnpm.1) to ./../../common/temp/node_modules/.pnpm/@prisma+client@2.27.0-integration-fix-sdk-pnpm.1_e65d142a06ef7e93699c380be6b525d3/node_modules/@prisma/client in 784ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
``
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
``

```

**Comment by gaggle** [comment]
Just to say I had this problem, I've switched `package.json` to:
```
    "prisma": "2.27.0-integration-fix-sdk-pnpm.2",
    "@prisma/client": "2.27.0-integration-fix-sdk-pnpm.2"
```

And I had this script already in there:
```
    "postinstall": "prisma generate",
```

And now things work:
```
$ pnpm install
Scope: all 6 workspace projects
../../node_modules/.pnpm/@prisma+engines@2.27.0-2.6f7f670adbb07fd4b8862c6d2bcb8c4703065918/node_modules/@prisma/engines: Running postinstall script, done in 1.6s
../../node_modules/.pnpm/prisma@2.27.0-integration-fix-sdk-pnpm.2/node_modules/prisma: Running preinstall script, done in 53ms
../../node_modules/.pnpm/prisma@2.27.0-integration-fix-sdk-pnpm.2/node_modules/prisma: Running install script, done in 53ms
../../node_modules/.pnpm/@prisma+client@2.27.0-integration-fix-sdk-pnpm.2_aa989df761f5be952059643708d47aa6/node_modules/@prisma/client: Running postinstall script, done in 998ms

dependencies:
- @prisma/client 2.26.0
+ @prisma/client 2.27.0-integration-fix-sdk-pnpm.2
- prisma 2.26.0
+ prisma 2.27.0-integration-fix-sdk-pnpm.2

../.. preinstall$ npx -y only-allow pnpm
└─ Done in 4.1s
. postinstall$ prisma generate
│ Environment variables loaded from .env
│ Prisma schema loaded from prisma/schema.prisma
│ ✔ Generated Prisma Client (2.27.0-integration-fix-sdk-pnpm.2) to ./../../node_modules/.pnpm/@prisma+client@2.27.0-integration-fix-sdk-pnpm.2_aa989df761f5be952059643708d47aa6/node_modules/@pri
│ You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
│ ```
│ import { PrismaClient } from '@prisma/client'
│ const prisma = new PrismaClient()
│ ```
└─ Done in 3.3s
```

And my app just works again. Thanks 👍

**Comment by gaggle** [comment]
(BTW if the context is of interest I described this fix in my article-series exploring TS monorepo patterns: https://dev.to/jonlauridsen/attempt-3-build-the-source-4oa3)

**Comment by v-morlock** [comment]
We are experiencing the same issue using yarn 2, even when using 2.27.0-integration-fix-sdk-pnpm.2

**Comment by Jolg42** [comment]
I think what's happening here is that when your project doesn't have `prisma` or `@prisma/client` dependencies installed 

Current workaround:
- Use any version of Prisma (latest recommended)
- pnpm add @prisma/client
- pnpm add -D prisma

We need to add pnpm support here:
https://github.com/prisma/prisma/blob/ea886f84f2f7923eb93533092cd82be7d4af99aa/packages/sdk/src/predefinedGeneratorResolvers.ts

**Comment by v-morlock** [comment]
Actually we are using the exact same setup as before - on 2.23.0, everything has been working just fine, on 2.29.0, we are getting the npm-error. We use prisma within a workspace of a yarn2-monorepo.

our new dependencies look like this:

```
    "@prisma/client": "^2.29.0",
    "prisma": "^2.29.0",
```

**Comment by Jolg42** [comment]
@v-morlock It would be good to open a seperate issue for Yarn 2 since it might be a different, but maybe related problem.

**Comment by ankhzet** [comment]
@millsp 
> So the idea is to override this logic if we find existing lock files

Wouldn't work in some cases, f.e. in rushjs monorepo lock files are kept in a separate subdirectory. Probably better way would be to explicitly state used package manager (f.e. `"prisma.packageManager"` field in `package.json`) or to handle this special usecase separately (maybe, search for `rush.json` in parent directories, but this would add more complexity to the logic and more maintenance burden). Otherwise migrate script errors out with `npm ERR! code EUNSUPPORTEDPROTOCOL` even if `pnpx` was used to run the command.

For now manually installing `@prisma/client` beforehand allows to circumvent the problem.

**Comment by pilchard** [comment]
This isn't monorepo specific, just pnpm. I have just walked through the [Quickstart](https://www.prisma.io/docs/getting-started/quickstart) with pnpm in a clean directory and encountered this. I don't mind (would rather) install dependencies manually but it isn't mentioned anywhere on that page (though it does indicate ts-node). Installing @prisma/client manually was all that was needed. I just needed to mock up a quick sqlite example and it's annoying to be commenting on an issue midway through the Quickstart instead.

**Comment by savager** [comment]
Is there a specific version I can install to avoid this currently? I don't want to move away from pnpm monorepo at the moment.

**Comment by savager** [comment]
Thanks, I believe I’ve tried that but I’ll double check. Appreciate it

**Comment by millsp** [comment]
Hey folks, we have just improved our `pnpm` detection logic to fix this issue, and we will release this in our `4.13.0` release. That said, you can try it now by installing our `dev` version. `npm install prisma@dev`.
