### ISSUE TITLE
Prisma migrate - always reporting Data loss / migration file changed even with simple field addition

### ISSUE THREAD

**Issue by webnoob** [prisma/prisma#5551]
Say I have a scheme (you already have a copy of my schema for https://github.com/prisma/prisma/issues/4748).

Adding a simple field like `status Int @default(0)` then running `migrate`. It reports:

![image](https://user-images.githubusercontent.com/10404747/107350647-97074300-6ac1-11eb-9bf0-28f9782203c7.png)

I can assure you those migration files have not been manually changed since they were applied. This happens without fail for me.

There is no way for me to be able think about using this in production (or even alpha testing) with simple fields being added causing a DB reset.

## How to reproduce

Have a scheme (use my example one if needs be as this is the one I've used) and without making any changes, run:

1: npx prisma migrate dev --create-only --preview-feature
2: npx prisma migrate dev --preview-feature

Let it apply the migrations, then add the status field as above to the `model Arc` in my schema. Then run the above commands again. It will complain with the error in the screenshot.

## Environment & setup

- OS: Windows
- Database: MySQL 8.0
- Node.js version: 12
- Prisma version: 

```
@prisma/cli          : 2.14.0
@prisma/client       : 2.14.0
Current platform     : windows
Query Engine         : query-engine 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at ..\..\..\..\node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at ..\..\..\..\node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at ..\..\..\..\node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at ..\..\..\..\node_modules\@prisma\engines\prisma-fmt-windows.exe)
Studio               : 0.332.0

```

**Comment by Jolg42** [comment]
Hi @webnoob 

Could you send us a copy of your schema? (If you don't want to post it publicly you can send it  to schemas@prisma.io with this issue URL)

Also could you try to reproduce with the latest version of Prisma? `2.16.1`

**Comment by webnoob** [comment]
I mentioned in my OP you already have my schema for #4748. Do you need it again?

I'm not in a position to upgrade just yet so can't. I will do ASAP.

**Comment by Jolg42** [comment]
Oh sorry, somehow I missed that part 😓 No need then thanks!

**Comment by webnoob** [comment]
Worth adding. Just upgraded to 2.17.0 and added changed one model to have native DB types `penName String?` became `penName String? @db.VarChar(250)` (I did this for about 15 strings in my PenName model). When creating the migration, it created a migration to drop ALL tables in my DB and recreate them.

I assume that's not right ...

**Comment by tomhoule** [comment]
@webnoob there is a known regression with MySQL on windows in 2.17.0. We are considering shipping a patch, but in the meantime the right move is to revert to 2.16.0. We planned time to look into your issues before 2.18.0, help is coming.

**Comment by webnoob** [comment]
Ok - good to know.
It's not holding up my workflow at the moment so I'll stay on latest so I can easily test for you guys. Just hit me up when you need some info! :)

**Comment by tomhoule** [comment]
If you are tracking latest, the fix should already be (or be soon) in `prisma@dev`, so that's an option I forgot to mention

**Comment by webnoob** [comment]
Ok, I'll consider moving to that then - thanks.

**Comment by webnoob** [comment]
This issue seems to have been resolved in 2.18.0. I added one prop against my Book model and the generated SQL was:
```
-- AlterTable
ALTER TABLE `book` ADD COLUMN     `randomField` VARCHAR(191);
```
No foreign keys being dropped or recreated and no data loss warnings (as I would expect with a simple change like this) 🥳 

Thanks for your hard work @tomhoule and @Jolg42 

Update 2.18.0 - the one update to rule them all!

**Comment by sk8Guerra** [comment]
I have **prisma 2.30.0** and **@prisma/client 2.22.1** and I still see the waring: _**Do you want to continue? All data will be lost.**_ 🤔

How is the behavior in prod? Will it in prod also reset the DB or?

**Comment by tomhoule** [comment]
No, in prod you should use `prisma migrate deploy`, which only applies migrations (it will never offer/ask you to reset).

**Comment by MatteoGauthier** [comment]
Thanks for your answer, but it's confusing, does someone know a blog post explaining database migrations with prisma ? (with dataloss issue)

**Comment by Jolg42** [comment]
Hi @MatteoGauthier 
This is where you can find more details in the docs https://www.prisma.io/docs/concepts/components/prisma-migrate/prisma-migrate-limitations-issues#data-loss-when-resetting-database

I can also recommend this guide https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate

If you have any questions / feedback I invite you to create an [issue](https://github.com/prisma/prisma/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) or [discussion](https://github.com/prisma/prisma/discussions)
We'll be happy to help!

**Comment by MatteoGauthier** [comment]
> Hi @MatteoGauthier This is where you can find more details in the docs [prisma.io/docs/concepts/components/prisma-migrate/prisma-migrate-limitations-issues#data-loss-when-resetting-database](https://www.prisma.io/docs/concepts/components/prisma-migrate/prisma-migrate-limitations-issues#data-loss-when-resetting-database)
> 
> I can also recommend this guide [prisma.io/docs/guides/database/developing-with-prisma-migrate](https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate)
> 
> If you have any questions / feedback I invite you to create an [issue](https://github.com/prisma/prisma/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) or [discussion](https://github.com/prisma/prisma/discussions) We'll be happy to help!

Thanks a lot for your answer, it's more clear for me now. Thanks
