### ISSUE TITLE
Initial migrate combined with seed returns "table does not exist"

### ISSUE THREAD

**Issue by paulosalvatore** [prisma/prisma#5887]
## Bug description

When creating the first migration by running `npx prisma migrate dev --preview-feature` with a valid `prisma/seed.ts`, an error is thrown.

**PS.:** It works fine when running `npx prisma seed --preview-feature` after DB is created.

```bash
PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: The table `user` does not exist in the current database.
    at cb (C:\GitHub\poc-nestjs-ocean\node_modules\@prisma\client\runtime\index.js:78689:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'P2021',
  clientVersion: '2.17.0',
  meta: { table: 'user' }
}
Error: Command failed with exit code 1: ts-node "C:\GitHub\poc-nestjs-ocean\src\prisma\seed.ts"
    at makeError (C:\GitHub\poc-nestjs-ocean\node_modules\prisma\build\index.js:2566:15)
    at handlePromise (C:\GitHub\poc-nestjs-ocean\node_modules\prisma\build\index.js:3234:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.tryToRunSeed (C:\GitHub\poc-nestjs-ocean\node_modules\prisma\build\index.js:61766:16)
    at async MigrateDev2.parse (C:\GitHub\poc-nestjs-ocean\node_modules\prisma\build\index.js:61902:13)
    at async main (C:\GitHub\poc-nestjs-ocean\node_modules\prisma\build\index.js:100809:18) {
  shortMessage: 'Command failed with exit code 1: ts-node "C:\\GitHub\\poc-nestjs-ocean\\src\\prisma\\seed.ts"',
  command: 'ts-node "C:\\GitHub\\poc-nestjs-ocean\\src\\prisma\\seed.ts"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

## How to reproduce

1. Create a migration with an `User` model
2. Create a `seed.ts` file that adds an user
3. Run `npx prisma migrate dev --preview-feature`

## Expected behavior

Create DB record without throwing any errors.

## Prisma information

```prisma
model User {
  id           Int         @id @default(autoincrement())

  email        String      @unique
  password     String?

  name         String?
}
```

## Environment & setup

- OS: Windows
- Database: MariaDB
- Node.js version: 12.18.4
- Prisma version: 2.17.0

**Comment by tomhoule** [comment]
Hi @paulosalvatore — I think this is a symptom of a known regression with MySQL on windows in 2.17.0 — this is fixed in 2.18.0, so I'll close. Thanks for reporting the issue, and if you see the same problem in 2.18.0, feel free to reopen!

**Comment by paulosalvatore** [comment]
Not sure if I'm doing anything wrong, but still experiencing errors in `2.18.0`.

## Npm script

```json
"prisma:migrate": "npx prisma migrate dev --preview-feature",
"prisma:merge": "npx prisma-merge",
"prisma:run": "npm run prisma:merge & rimraf src/prisma/migrations & npx prisma migrate dev --preview-feature --name init & npm run prisma:generate & npx prisma db seed --preview-feature"
```

## Error stack

```
Running ts-node "src\prisma\seed.ts" ...
PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: The table `user` does not exist in the current database.
    at cb (C:\projects\backend\node_modules\@prisma\client\runtime\index.js:79160:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'P2021',
  clientVersion: '2.18.0',
  meta: { table: 'user' }
}
Error: Command failed with exit code 1: ts-node "src\prisma\seed.ts"
    at makeError (C:\projects\backend\node_modules\prisma\build\index.js:2564:15)
    at handlePromise (C:\projects\backend\node_modules\prisma\build\index.js:3232:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.tryToRunSeed (C:\projects\backend\node_modules\prisma\build\index.js:61995:16)
    at async MigrateDev2.parse (C:\projects\backend\node_modules\prisma\build\index.js:62146:13)
    at async main (C:\projects\backend\node_modules\prisma\build\index.js:103094:18) {
  shortMessage: 'Command failed with exit code 1: ts-node "src\\prisma\\seed.ts"',
  command: 'ts-node "src\\prisma\\seed.ts"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

## Full terminal log after running script

```bash
C:\projects\backend>npm run prisma:run

> backend@0.0.1 prisma:run C:\projects\backend
> npm run prisma:merge & rimraf src/prisma/migrations & npx prisma migrate dev --preview-feature --name init & npm run prisma:generate & npx prisma db seed --preview-feature


> backend@0.0.1 prisma:merge C:\projects\backend
> npx prisma-merge

npx: installed 89 in 5.113s
Merged prima files into src/prisma/schema.prisma
Environment variables loaded from .env
Prisma schema loaded from src\prisma\schema.prisma
Datasource "db": MySQL database "db" at "localhost:3306"

√ - Drift detected: Your database schema is not in sync with your migration history.
- The following migration(s) are applied to the database but missing from the local migrations directory: 20210306090654_init


We need to reset the MySQL database "db" at "localhost:3306".
Do you want to continue? All data will be lost. ... yes


Running ts-node "src\prisma\seed.ts" ...
PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: The table `user` does not exist in the current database.
    at cb (C:\projects\backend\node_modules\@prisma\client\runtime\index.js:79160:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'P2021',
  clientVersion: '2.18.0',
  meta: { table: 'user' }
}
Error: Command failed with exit code 1: ts-node "src\prisma\seed.ts"
    at makeError (C:\projects\backend\node_modules\prisma\build\index.js:2564:15)
    at handlePromise (C:\projects\backend\node_modules\prisma\build\index.js:3232:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.tryToRunSeed (C:\projects\backend\node_modules\prisma\build\index.js:61995:16)
    at async MigrateDev2.parse (C:\projects\backend\node_modules\prisma\build\index.js:62146:13)
    at async main (C:\projects\backend\node_modules\prisma\build\index.js:103094:18) {
  shortMessage: 'Command failed with exit code 1: ts-node "src\\prisma\\seed.ts"',
  command: 'ts-node "src\\prisma\\seed.ts"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
The following migration(s) have been created and applied from new schema changes:

migrations/
  └─ 20210306090746_init/
    └─ migration.sql

✔ Generated Prisma Client (2.18.0) to .\node_modules\@prisma\client in 383ms

Everything is now in sync.

> backend@0.0.1 prisma:generate C:\projects\backend
> npx prisma generate

Environment variables loaded from .env
Prisma schema loaded from src\prisma\schema.prisma

✔ Generated Prisma Client (2.18.0) to .\node_modules\@prisma\client in 377ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
\`\`\`
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
\`\`\`
Environment variables loaded from .env
Prisma schema loaded from src\prisma\schema.prisma
Running ts-node "src\prisma\seed.ts" ...

Your database has been seeded.
```

**Comment by tomhoule** [comment]
Maybe older migrations created with 2.17.0?

**Comment by paulosalvatore** [comment]
I always run `rimraf src/prisma/migrations` to delete all migrations before running it again, since generated migrations after the first one contains a lot of constraints removal and erases the data no matter what.

I can create a GitHub repo to simulate the behaviour if that helps.
