### ISSUE TITLE
Query raw run throws the following error ```incorrect binary data format in bind parameter 3```

### ISSUE THREAD

**Issue by edilson** [prisma/prisma#7194]
### Bug description

I'm trying to run a raw query casting the types of some attributes but getting the error describe at the title. I have run the query at the database console and it is working.

### How to reproduce

```
const deliveryPriceCalculated =
      await prisma.$queryRaw<ZipCodeRange>`SELECT * FROM zip_ranges_brazil WHERE
      weight = ${weight}
      AND number_service = ${number_service}
      AND (${zip_origin})::INTEGER BETWEEN zip_origin_start::INTEGER AND zip_origin_end::INTEGER
      AND (${zip_destination})::INTEGER BETWEEN zip_destination_start::INTEGER AND zip_destination_end::INTEGER`
```

### Expected behavior

Run the query and give me the expected data. 

### Prisma information

```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model ZipCodeRange {
  id                    String   @id @default(uuid())
  number_service        String   @db.VarChar(20)
  region                String   @db.VarChar(100)
  delivery_time         Int
  weight                Float
  value                 Float
  zip_origin_start      String   @db.VarChar(50)
  zip_origin_end        String   @db.VarChar(50)
  zip_destination_start String   @db.VarChar(50)
  zip_destination_end   String   @db.VarChar(50)
  zip_origin_ref        String   @db.VarChar(50)
  zip_destination_ref   String   @db.VarChar(50)
  created_at            DateTime @default(now())
  updated_at            DateTime @default(now())

  @@map("zip_ranges_brazil")
}
```

### Environment & setup

- OS: Ubuntu 20
- Database: Postgres
- Node.js version: 15.4.0

### Prisma Version

```
2.22.1
```

**Comment by celber** [comment]
Got the same issue. Prisma changes raw query to lowercase. For column names, you can simply use quotes, but for internal functions (::INTEGER) there is no workaround :(

**Comment by edilson** [comment]
@celber  So there is no way to cast attributes when running a query?

**Comment by janpio** [comment]
Ouch. 

Do you have logs showing the lower cased queries @celber? Would make it super easy to understand and prioritize this.

**Comment by edilson** [comment]
@janpio it is possible to perform casts using $queryRaw?

**Comment by janpio** [comment]
What you wrote above indicates it is not right now because of a bug. I do not think we have documentation or previous issues/discussions about this.

**Comment by celber** [comment]
I do not have logs no more because i have already did workaround for this issue, but this is supereasy to reproduce :)
Here you have my WHERE clause which works fine in any PG client, yet is lowercased in prisma queryRaw. st_sistancesphere function does not exists so query fails. Funny thing is that prisma logs query as i have written it, but from postgres i get error containing lowercased fragment, so lowercasing must be done at some of the last steps.

`
const locationQuery = `ST_DistanceSphere(ST_SetSRID(ST_MakePoint(${query.location.lng},${query.location.lat}),4326), ST_SetSRID(ST_MakePoint(lng,lat),4326)) / 1000 < ${query.radius || 25}`;
`

**Comment by pantharshit00** [comment]
I am unable to reproduce this with `2.23` and `2.22.1`. 
![image](https://user-images.githubusercontent.com/22195362/119848913-d4d18f80-bf29-11eb-8c33-85f0975124d0.png)

```ts
import { PrismaClient, ZipCodeRange } from "@prisma/client";

async function main() {
  const prisma = new PrismaClient();
  let weight = 0;
  let number_service = "test";
  let zip_origin = 2;
  let zip_destination = 124;

  const deliveryPriceCalculated =
    await prisma.$queryRaw<ZipCodeRange>`SELECT * FROM zip_ranges_brazil WHERE
      weight = ${weight}
      AND number_service = ${number_service}
      AND (${zip_origin})::INTEGER BETWEEN zip_origin_start::INTEGER AND zip_origin_end::INTEGER
      AND (${zip_destination})::INTEGER BETWEEN zip_destination_start::INTEGER AND zip_destination_end::INTEGER`;
  console.log(deliveryPriceCalculated);
  prisma.$disconnect();
}

main();
```


Can you please share the variables which you are passing into the query? Maybe make a minimal reproduction inside of a git repo so I don't need to make assumptions here.

**Comment by edilson** [comment]
@pantharshit00 here is the query running with the variables I'm using

![Captura de Tela 2021-05-27 às 14 01 53](https://user-images.githubusercontent.com/35120901/119867441-48f14080-bef4-11eb-9fe8-8dab30540326.png)

**Comment by pantharshit00** [comment]
Thanks for the screenshot, I can reproduce now with the following script:
```ts
import { PrismaClient, ZipCodeRange } from "@prisma/client";

async function main() {
  const prisma = new PrismaClient({
    log: ["query"],
  });
  let weight = 18;
  let number_service = "03298";
  let zip_origin = "89160027";
  let zip_destination = "1";

  const deliveryPriceCalculated =
    await prisma.$queryRaw<ZipCodeRange>`SELECT * FROM zip_ranges_brazil WHERE
      weight = ${weight}
      AND number_service = ${number_service}
      AND (${zip_origin})::INTEGER BETWEEN zip_origin_start::INTEGER AND zip_origin_end::INTEGER
      AND (${zip_destination})::INTEGER BETWEEN zip_destination_start::INTEGER AND zip_destination_end::INTEGER`;
  console.log(deliveryPriceCalculated);
  prisma.$disconnect();
}

main();

```

Cast these params as integers as a workaround for now.

**Comment by edilson** [comment]
@pantharshit00 it looks like even casting the params it is not returning the desired data because the BETWEEN params are not being casted.

**Comment by matthewmueller** [comment]
@edilson were you able to find a workaround?

I'm a bit confused why this is happening. Postgres syntax is case-insensitive afaik. For example, you can cast strings to integers with the following:

```sql
select '100'::integer
# 100
```

**Comment by edilson** [comment]
@matthewmueller no, for that case I'm using the pg module as a workaround until this is fixed

**Comment by celber** [comment]
Here you got the very exact query i run:

```
SELECT
         id, name, data, lat, lng, city, "categoryId", "userId",
         (select name from hekete."User" where id="userId") as "userName"
 FROM xxx."Advertisement"
 WHERE
         ST_DistanceSphere(ST_SetSRID(ST_MakePoint(17.03533,51.10773),4326), ST_SetSRID(ST_MakePoint(lng,lat),4326)) / 1000 < 25
         AND
         1=1
 LIMIT 50
 OFFSET 0;
```

Works OK with pg adapter.

**Comment by Weakky** [comment]
Hey,

This issue was fixed by https://github.com/prisma/prisma-engines/pull/2847. It will be available in the next release under the `improvedQueryRaw` feature flag.

Beware that enabling `improvedQueryRaw` is a breaking change. Release notes will contain information as to how to upgrade (so will the documentation).

Thanks for reporting 🙏

**Comment by muhammad-Osman** [comment]
> Hey,
> 
> This issue was fixed by [prisma/prisma-engines#2847](https://github.com/prisma/prisma-engines/pull/2847). It will be available in the next release under the `improvedQueryRaw` feature flag.
> 
> Beware that enabling `improvedQueryRaw` is a breaking change. Release notes will contain information as to how to upgrade (so will the documentation).
> 
> Thanks for reporting pray

this is still not working i am querying database on the base of date and it is saying like

db error: ERROR: incorrect binary data format in bind parameter 3

const newToRoleResult: any = await prisma.$queryRaw`
        SELECT distinct on (p.id) p.id, count(*), DATE(p.start_date), a.grade, a.reviewed_at 
      FROM assessments a, people p WHERE (a.status = CAST('done' AS assessment_status) 
      AND a.reviewee_id = p.id AND 
      (p.institute_id = ${instituteId} 
        OR (p.institute_id in 
          (SELECT inst.id FROM institute inst WHERE inst.mat_id = ${instituteId}))))
          ${
            newToRole == "NTR"
              ? newToRole
                ? Prisma.sql`AND p.start_date::DATE BETWEEN ${startDate}::DATE AND ${endDate}::DATE`
                : Prisma.empty
              : newToRole == "NNTR"
              ? Prisma.sql`AND NOT p.start_date <= ${startDate} AND NOT p.start_date >= ${endDate}`
              : Prisma.empty
          } 
          GROUP BY a.grade, p.id, a.reviewed_at ORDER BY p.id, a.reviewed_at DESC`;
