### ISSUE TITLE
Could not resolve @prisma/client despite the installation that we just tried.

### ISSUE THREAD

**Issue by Southclaws** [prisma/prisma#7234]
### Bug description

I've come back to work on a product again after a couple of weeks and it broke (again) which I guess just happens as prisma is evolving quickly but this one I couldn't figure out the fix.

Locally, it generates fine still, but in the Docker image which our backend deploys it throws this after `yarn dlx prisma generate`

```
Error: Could not resolve @prisma/client despite the installation that we just tried.
Please try to install it by hand with npm install @prisma/client and rerun prisma generate 🙏.
```

(Which I tried and doesn't make any difference)

I also tried installing prisma globally with `npm i -g prisma` and the same issue occurs. Same with `npx prisma generate` too.

`npx prisma` results in this:

```
root@53e11231ecb9:/api# npx prisma
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '/root/.npm/_npx/141/lib/node_modules/prisma/scripts/preinstall-entry.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! prisma@2.23.0 preinstall: `node scripts/preinstall-entry.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the prisma@2.23.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-23T17_55_36_862Z-debug.log
Install for [ 'prisma@latest' ] failed with code 1
```

I did manage to get it to work once by running the yarn dlx command twice, but I can't remember how, it's been a few hours now!

Are there any specific changes that happened in the last few weeks that I need to make changes for?

One aspect of this project is that it's a multi-tenant yarn workspaces repo with a few different packages inside, but the root package includes `prisma` as a dependency and `@prisma/client` as a dev dependency (which I'm not sure why, I think it solved another similar issue a couple of months back)

### How to reproduce

It's probably project specific, but just running generate triggers it.

### Prisma information

Schema isn't relevant. It generates fine on development machine (mac)

### Environment & setup

- OS: Building a Docker image (based on `golang:latest`)
- Node.js version: 12.18.3

### Prisma Version

```
prisma               : 2.23.0
@prisma/client       : 2.23.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine adf5e8cba3daf12d456d911d72b6e9418681b28b (at ../usr/local/nvm/versions/node/v12.18.3/lib/node_modules/prisma/node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli adf5e8cba3daf12d456d911d72b6e9418681b28b (at ../usr/local/nvm/versions/node/v12.18.3/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core adf5e8cba3daf12d456d911d72b6e9418681b28b (at ../usr/local/nvm/versions/node/v12.18.3/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt adf5e8cba3daf12d456d911d72b6e9418681b28b (at ../usr/local/nvm/versions/node/v12.18.3/lib/node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : adf5e8cba3daf12d456d911d72b6e9418681b28b
Studio               : 0.393.0
```

**Comment by Southclaws** [comment]
I got it to run successfully, but I had to do this (I think)

- yarn dlx prisma generate: that fails with the error
- yarn add @prisma/client
- yarn dlx prisma generate: fails again
- yarn dlx prisma generate: magically works

**Comment by Southclaws** [comment]
Okay it seems installing `@prisma/client` fresh each time works, which is fine!
```
  generate:
    cmds:
      # Generate database bindings and data model types.
      - yarn add @prisma/client
      - yarn dlx prisma generate
```

**Comment by janpio** [comment]
Can you share a reproduction project that has the same problem? First time I hear about this error, so it most probably has to do with your specific setup.

**Comment by pantharshit00** [comment]
@Southclaws Are you using Yarn v2? If yes, then this is a duplicate of https://github.com/prisma/prisma/issues/1439

You need to use the node_modules linker to make Prisma work there.

**Comment by ahollenbach** [comment]
Not using yarn 2 and encounter this issue when building in docker as well.

I notice it occurs specifically when upgrading from prisma 2.23.0 -> 2.24.0, and only when upgrading `prisma` and not `@prisma/client`, which is fine at 2.24+

Dockerfile
```dockerfile
<...>
RUN yarn install
RUN yarn run build:js
RUN dotenv -e .env.development -- yarn prisma generate
```

Output
```sh
 > [10/10] RUN dotenv -e .env.development -- yarn prisma generate:
#14 0.645 yarn run v1.22.5
#14 0.705 $ /node_modules/.bin/prisma generate
#14 1.355 Environment variables loaded from .env
#14 2.070 Prisma schema loaded from prisma/schema.prisma
#14 3.659 [1/4] Resolving packages...
#14 4.129 [2/4] Fetching packages...
#14 5.198 info fsevents@2.3.2: The platform "linux" is incompatible with this module.
#14 5.198 info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
#14 5.230 [3/4] Linking dependencies...
#14 8.626 [4/4] Building fresh packages...
#14 8.799 success Saved 0 new dependencies.
#14 9.336 [1/4] Resolving packages...
#14 9.845 [2/4] Fetching packages...
#14 10.86 info fsevents@2.3.2: The platform "linux" is incompatible with this module.
#14 10.86 info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
#14 10.89 [3/4] Linking dependencies...
#14 14.33 [4/4] Building fresh packages...
#14 14.53 success Saved 0 new dependencies.
#14 14.62 Error: Could not resolve @prisma/client despite the installation that we just tried.
#14 14.62 Please try to install it by hand with npm install @prisma/client and rerun yarn prisma generate :pray:.
#14 14.65 error Command failed with exit code 1.
#14 14.65 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by janpio** [comment]
Please open a new issue @ahollenbach as this sounds different enough to get its own investigation. Please make sure to fill the full issue tempalte so we have all information. Thanks.

**Comment by ahollenbach** [comment]
I ended up not creating a ticket, but it looks like 2.26.0 resolved this issue for me.

**Comment by gex** [comment]
> Alternately, you can generate the client in a different location than the default: https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/generating-prisma-client#using-a-custom-output-path

i'm a bit lost in this yarn-pnp-prisma black hole. i tried this solution (custom output path) but it doesn't work for me.

`package.json`

```
  "dependencies": {
    "@prisma/client": "2.29.0"
  },
  "devDependencies": {
    "@types/node": "^16.4.13",
    "@types/prettier": "^2",
    "prettier": "^2.3.2",
    "prisma": "2.29.0",
    "ts-node-dev": "^1.1.8",
    "typescript": "^4.3.5"
  }
```

`schema.prisma`

```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  output   = "../src/generated/client"
}
```

output of `DEBUG='*' yarn prisma generate`

```
  prisma:loadEnv project root found at /home/node/api/package.json +0ms
  prisma:tryLoadEnv Environment variables not found at null +0ms
  prisma:tryLoadEnv Environment variables not found at undefined +0ms
  prisma:tryLoadEnv No Environment variables loaded +0ms
  prisma:engines using Node API: false +0ms
  prisma:engines binaries to download query-engine, migration-engine, introspection-engine, prisma-fmt +0ms
Prisma schema loaded from prisma/schema.prisma
  prisma:getConfig Using Query Engine Binary at: /home/node/api/.yarn/unplugged/prisma-npm-2.29.0-aadd46b583/node_modules/prisma/query-engine-linux-musl +0ms
  prisma:getDMMF Using Query Engine Binary at: /home/node/api/.yarn/unplugged/prisma-npm-2.29.0-aadd46b583/node_modules/prisma/query-engine-linux-musl +0ms
  prisma:generator prismaCLIDir undefined +0ms
  prisma:generator prismaClientDir undefined +1ms
  prisma:generator baseDir /home/node/api/prisma +0ms
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 350ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done in 0s 476ms
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 362ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done in 0s 490ms
  prisma:generator prismaCLIDir undefined +2s
  prisma:generator prismaClientDir undefined +0ms
Error: Error: Could not resolve @prisma/client despite the installation that we just tried.
Please try to install it by hand with npm install @prisma/client and rerun yarn prisma generate 🙏.
    at Object.prisma-client-js (/home/node/api/.yarn/unplugged/prisma-npm-2.29.0-aadd46b583/node_modules/prisma/build/index.js:35010:17)
    at async generators.stopOnError (/home/node/api/.yarn/unplugged/prisma-npm-2.29.0-aadd46b583/node_modules/prisma/build/index.js:36224:19)
    at async /home/node/api/.yarn/unplugged/prisma-npm-2.29.0-aadd46b583/node_modules/prisma/build/index.js:17214:29
```

**Comment by mjknight50** [comment]
I came across this in my Docker build.

This can happen if you have  "@prisma/client" in the **devDependencies**.
Move it to **dependencies**

**Comment by janpio** [comment]
That is unexpected and would be a problem we might want to fix. Is this reproducible @mjknight50? If so, we would appreciate a separate issue about this.

**Comment by rinogo** [comment]
@janpio

> That is unexpected and would be a problem we might want to fix. Is this reproducible @mjknight50? If so, we would appreciate a separate issue about this.

Definitely reproducible! I came across this in my NestJS/Prisma/Docker production build. Moving Prisma from `devDependencies` to `dependencies` as @mjknight50 suggested fixed the problem.

**Comment by mjknight50** [comment]
Yup what @janpio said.

**Comment by janpio** [comment]
Ok, rereading this, `@prisma/client` indeed belongs into `dependencies` and not `devDependencies` of course. Can you open a quick issue with reproduction steps and the error message? That would be nice - then we can look at that in isolation from the original issue here @rinogo @mjknight50 - thanks!

**Comment by lytk4dev** [comment]
I had this problem, because i didn't install prisma in my project.

**Comment by bugwheels94** [comment]
This happens in npm workspaces too. In npm workspace the deps are installed on the parent directory while @prisma/client appears locally for some reason

**Comment by cesarve77** [comment]
> This happens in npm workspaces too. In npm workspace the deps are installed on the parent directory while @prisma/client appears locally for some reason

did you fix it?

**Comment by bugwheels94** [comment]
> > This happens in npm workspaces too. In npm workspace the deps are installed on the parent directory while @prisma/client appears locally for some reason
> 
> did you fix it?

I switched to Typeorm

**Comment by DanielOberlechner** [comment]
I have this issue as well is nobody able to solve this problem.
But I'm as well working on a m1 Max Machine and had problems with the python version.
Finally got installed but can't import ...]

This can't be it does it?

**Comment by kolserdav** [comment]
I get this error when I run `prisma generate` inside `node_modules` in my library which has `@prisma/client` as a dependency. Is there any example how to use `@prisma/client` inside npm library?

**Comment by kolserdav** [comment]
> I get this error when I run `prisma generate` inside `node_modules` in my library which has `@prisma/client` as a dependency. Is there any example how to use `@prisma/client` inside npm library?

My problem was solved by moving `prisma` from `devDependenies` to `depenencies`. The fact is that when installing my library from npm, `prisma` was not installed because it was in `devDependenies` and `prisma generate` was launched from a package that is higher in the folder hierarchy than the project root, this caused error:
```sh
Error: Could not resolve @prisma/client despite the installation that we just tried
```

**Comment by huanlirui** [comment]
how to fix ???

![image](https://user-images.githubusercontent.com/40491203/186402797-ae307559-0c5d-4f08-ae5f-40d4ea6bca90.png)

**Comment by josejonathan7** [comment]
estou com mesmo problema no ambiente kubernetes o meu @prisma/client esta nas dependencias, deixei nas configurações para instala as dependencias e logo em seguida executar npx prisma generate, mas ele fica retornando o seguinte erro

![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/71531287/186910268-ded13a52-0511-49f8-a6fe-5c14f1359518.png)

**Comment by leppaott** [comment]
We just update from 4.2.1 into 4.3.1 and get this?

We do have
`"workspaces": [
    "../common"
  ],`
in the same package.json where `prisma generate` fails but this shouldn't affect the generation?

` prisma:generator  prismaCLIDir /parent/node_modules/prisma +860ms
  prisma:generator  prismaClientDir /parent/service/node_modules/@prisma/client +1ms
Error: Error: Could not resolve @prisma/client despite the installation that we just tried.`

Also we have the 4.3.1. "prisma" installed on parent module's package.json hence /parent/node_modules/prisma.

**Comment by sarink** [comment]
This happened to me because I _only_ had `@prisma/client` installed, and I needed to also install `prisma`

**Comment by kuubson** [comment]
yeah the `prisma` must be also installed, especially when using `pnpm` (ensure that the versions are the same)

**Comment by ta-cos** [comment]
> 

I just did this 🥇 thank you for the reminder

**Comment by and-ratajski** [comment]
> yeah the `prisma` must be also installed, especially when using `pnpm` (ensure that the versions are the same)

Yeah, but it's worth mentioning that it HAS to be added before overall _install_ command, e.g:

```Dockerfile
FROM node:18-alpine
ARG node_env_type=development
ARG database_url

RUN apk update && apk upgrade
RUN apk add --no-cache python3 py3-pip make g++ \
   && rm -rf /var/cache/apk/*

WORKDIR /app
COPY ./app .

RUN npm install -g pnpm

# WARNING! Install prisma BEFORE overall package installation!
RUN pnpm add prisma
RUN pnpm add @prisma/client

RUN pnpm install --shamefully-hoist

ENV PATH ./node_modules/.bin/:$PATH
ENV NODE_ENV ${node_env_type}
ENV DATABASE_URL ${database_url}

RUN npx prisma generate

CMD [ "pnpm", "dev" ]
```

**Comment by nullbuddy1243** [comment]
> This happened to me because I _only_ had `@prisma/client` installed, and I needed to also install `prisma`

Bless you.  Somehow I missed that step too working on a new codebase.  o7

**Comment by scorpio-demon** [comment]
> This happened to me because I _only_ had `@prisma/client` installed, and I needed to also install `prisma`

Unexpected, but work! :)

**Comment by TD-Media** [comment]
Fixed it by upgrading Webstorm to the latest version

**Comment by viewplatgh** [comment]
Resolved by `yarn add prisma` for me

**Comment by Eliav2** [comment]
tried everting written in here but issue still persists (when deolying to firebase clound functions, locally works pefectly fine).
any farther suggestions?

**Comment by janpio** [comment]
Open your own issue @Eliav2 and provide the information the bug issue template asks for. With no information, it will be impossible to help you.

**Comment by Eliav2** [comment]
resolved the issue by coping Prisma folder into dist folder(which is uploaded to firebase) and removing the manual command 'prisma generate' (that was run on npm postinstall script).

**Comment by smug9ler505** [comment]
I had the same problem. Resolved it by removing "postinstall": "prisma generate" from scripts in package.json

**Comment by Weakky** [comment]
Hey @Southclaws,

Are you still experiencing this issue? If not, we'd like to close it.

Thank you 🙏

**Comment by Southclaws** [comment]
I can't even remember this issue so it's safe to say it's probably working fine now!

**Comment by pnkjbee2** [comment]
npm install --save-dev prisma
(had the same issue, use this)

**Comment by MuhammadAnas47** [comment]
npm i --save-dev prisma ts-node @types/node

works for me!.

**Comment by ishkov2709** [comment]
> Решено `yarn add prisma`для меня

thanks so much, it helped

**Comment by Feridinha** [comment]
> This happened to me because I _only_ had `@prisma/client` installed, and I needed to also install `prisma`

I love you, I really do

**Comment by igloo1505** [comment]
I know this issue is closed, but I wanted to add my own issue:

I'm working in a turborepo monorepo with pnpm. I have multiple packages using prisma, and one of them worked fine with `@prisma/client v^5.10.2` and `prisma@latest`. The other that was giving me the same error described above was using `@prisma/client v^5.13.0` and a matching `prisma@^5.13.0`. Moving the latter versions over to match the former made things magically work.

**Comment by kopax** [comment]
I am  upgrading from yarn 1 to yarn 4 and I am struggling on this for hours, none of the ideas here helped.

**Comment by net-tech** [comment]
> I know this issue is closed, but I wanted to add my own issue:
> 
> I'm working in a turborepo monorepo with pnpm. I have multiple packages using prisma, and one of them worked fine with `@prisma/client v^5.10.2` and `prisma@latest`. The other that was giving me the same error described above was using `@prisma/client v^5.13.0` and a matching `prisma@^5.13.0`. Moving the latter versions over to match the former made things magically work.

You are a godsend

**Comment by emmasaf** [comment]
I removed the node_modules,and it magically start works.

**Comment by teknology** [comment]
> I am upgrading from yarn 1 to yarn 4 and I am struggling on this for hours, none of the ideas here helped.

I've been struggling with it for 2 days now. It's getting ridiculous.

**Comment by aishtiaq7** [comment]
Mine got fixed when I made sure all the **npm** packages were **re-installed**, that meant deleting the node_modules and reinstalling the packages.

**Comment by pantharshit007** [comment]
Dont know how i suddenly got this error when it was working fine until now. I just deleted the node_modules and package-lock.
Tried everything but didn't work then, I did this:
```bash
npm cache clean --force
cd packages/db
npm uninstall prisma @prisma/client
npm cache clean --force
npm install prisma@5.22.0 @prisma/client@5.22.0
npx prisma generate #it worked
cd ../..
npm i
``

**Comment by hemantvardani** [comment]
I uninstalled @prisma/client and re-installed. I worked.

**Comment by NilPuig** [comment]
for those using pnpm, this worked for me: 
```
 pnpm update;
rm -rf node_modules;
pnpm uninstall prisma @prisma/client; 
pnpm add @prisma/client;
pnpm add prisma -D;
```

**Comment by Aladiah96** [comment]
I got the same issue yesterday and my coworker got it today. It was as simple as reinstalling @prisma/client, but by now it should be fixed I guess

**Comment by richardpokhrel** [comment]
this is causing because in your package. json there is differernt version of prisma client and prisma try installing the same version of both and it just work fine

**Comment by npathirana-boundary** [comment]
> npm i --save-dev prisma ts-node @types/node

This did work. tnx

**Comment by oiabhishekk** [comment]
> I got the same issue yesterday and my coworker got it today. It was as simple as reinstalling @prisma/client, but by now it should be fixed I guess

its still not fixed

**Comment by khaosdoctor** [comment]
Commenting to say that on version 6.14 this started happening to me too. We have a turborepo setup with both `@prisma/client` and `prisma` installed correctly but it doesn't work. If I remove all the node_modules, then run `prisma generate` NOT through `yarn dlx` then it works once, if I try to run again it fails.

**Comment by oiabhishekk** [comment]
If this error occurs with Next.js, I recommend reviewing the following documentation, as it helped resolve the issue for me: https://www.prisma.io/docs/orm/more/help-and-troubleshooting/nextjs-help

**Comment by khaosdoctor** [comment]
> If this error occurs with Next.js, I recommend reviewing the following documentation, as it helped resolve the issue for me: https://www.prisma.io/docs/orm/more/help-and-troubleshooting/nextjs-help

Unfortunately not, we are using Nest.js :/

**Comment by zyf0330** [comment]
I use pnpm in a monorepo, prisma v6. 
I fix this by do this:
I remove all node_modules in every package except root node_modules, and then pnpm i.
