### ISSUE TITLE
Display more robust error information in migration cli

### ISSUE THREAD

**Issue by evcohen** [prisma/prisma#7651]
## Problem

Im trying to set up prisma in an existing project with a mysql db. Creating the first migration works, but then `npx prisma migrate dev` returns this error:

```
Migration `20210614151810_initial_migration` failed to apply cleanly to the shadow database.
Error:
Database error
Error querying the database: Server error: `ERROR 42000 (1071): Specified key was too long; max key length is 3072 bytes'
   0: sql_migration_connector::flavour::mysql::sql_schema_from_migration_history
             at migration-engine/connectors/sql-migration-connector/src/flavour/mysql.rs:321
   1: sql_migration_connector::sql_database_migration_inferrer::validate_migrations
             at migration-engine/connectors/sql-migration-connector/src/sql_database_migration_inferrer.rs:88
   2: migration_core::api::DevDiagnostic
             at migration-engine/core/src/api.rs:95
```

I have no idea which line in the migration file this is referring to or the key. It would be great to have clear and actionable error reports. 

## Suggested solution

More robust error handling in migrate tool

**Comment by tomhoule** [comment]
We released https://github.com/prisma/prisma/issues/7908 in 2.26.0, but this won't help in this case since the error happens on the shadow database, and we're not using these diagnostics there. Let's extend the new errors to more places.

**Comment by pimeys** [comment]
MySQL should be done, does the issue still persist with the latest version @evcohen?

**Comment by tomhoule** [comment]
Since we assume it is fixed, let's close this issue. Please open a new one if something similar happens.
