### ISSUE TITLE
Precompiled engine files for `aarch64-unknown-linux-musl` target (Alpine Linux on ARM, e.g. M1)

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#8478]
## Problem

Right now you can't use Prisma on Docker alpine on M1 mac as it requires `aarch64-unknown-linux-musl` binaries. As M1 will see more adoption, people will run into this frequently. 

## Suggested solution
Provide precompiled binaries for `aarch64-unknown-linux-musl` target like we have precompiled binaries for `x86-linux-musl`

## Alternatives
1. Ask user to compile the binary themselves
2. Document use `node:lts` instead of `node:lts-alpine` which is not ideal.

## Additional context
https://github.com/prisma/prisma/issues/7755

Naming as `unknown` is intended like that, see more information internally: https://prisma-company.slack.com/archives/C016KUHB1R6/p1627469574008300?thread_ts=1626873669.001400&cid=C016KUHB1R6

**Comment by Brooooooklyn** [comment]
I'm maintaining Docker images for cross compile: https://github.com/orgs/napi-rs/packages/container/package/napi-rs%2Fnodejs-rust.
The `ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine` is for compile `aarch64-unknown-linux-musl` target, see https://github.com/napi-rs/package-template/blob/main/.github/workflows/CI.yaml#L79 for example.

**Comment by safareli** [comment]
This could be "solved" by using `docker build --platform linux/arm64 ` [see this article](
https://web.archive.org/web/20210527154633/https://blog.jaimyn.dev/how-to-build-multi-architecture-docker-images-on-an-m1-mac/)

**Comment by jensmeindertsma** [comment]
What can I do to help get support for this implemented?

**Comment by huikaihoo** [comment]
Any plan or timeline to support this?

**Comment by artursudnik** [comment]
v3.7.0 has been released, but it seems that this issue is not fixed, is it?

**Comment by janpio** [comment]
The issue is not closed, hence the problem is not solved and stays open here for tracking.

**Comment by artursudnik** [comment]
I see. Thanks. it has been added to the 3.7.0 milestone this is why I am asking.

**Comment by Josh-a-e** [comment]
Yeah, this has become an issue for our engineers using M1s - is there any indication as to whether this item is any sort of priority?

**Comment by Axxxx0n** [comment]
what can we do to help?

**Comment by muqshots** [comment]
Any update on this?

**Comment by jensmeindertsma** [comment]
How can we help get this prioritised?

**Comment by spvn87** [comment]
Hopefully this will help in the interim:

```Dockerfile
FROM rust:1.58.1-alpine3.14 as prisma
ENV RUSTFLAGS="-C target-feature=-crt-static"
RUN apk --no-cache add openssl direnv git musl-dev openssl-dev build-base perl protoc
RUN git clone --depth=1 --branch=3.9.0 https://github.com/prisma/prisma-engines.git /prisma && cd /prisma
RUN cargo build --release --jobs 1

FROM node:16.14.0-alpine3.14
WORKDIR /src
ENV PRISMA_QUERY_ENGINE_BINARY=/prisma-engines/query-engine \
  PRISMA_MIGRATION_ENGINE_BINARY=/prisma-engines/migration-engine \
  PRISMA_INTROSPECTION_ENGINE_BINARY=/prisma-engines/introspection-engine \
  PRISMA_FMT_BINARY=/prisma-engines/prisma-fmt \
  PRISMA_CLI_QUERY_ENGINE_TYPE=binary \
  PRISMA_CLIENT_ENGINE_TYPE=binary
COPY --from=prisma /prisma/target/release/query-engine /prisma/target/release/migration-engine /prisma/target/release/introspection-engine /prisma/target/release/prisma-fmt /prisma-engines/
COPY . /src
RUN cd src && yarn install
```

**Comment by aqrln** [comment]
@spvn87 What is the reason behind using the binary engine here?
I'm pretty sure this should also work with the library engine, the only pitfall I'm aware of is you need to add `.node` to the file name for Node.js to recognise it as an addon and allow loading it (so, in your example, that would mean copying `/prisma/target/release/libquery_engine.so` to `/prisma-engines/libquery_engine.so.node` and setting `PRISMA_QUERY_ENGINE_LIBRARY=/prisma-engines/libquery_engine.so.node`).

**Comment by beemstream** [comment]
> Hopefully this will help in the interim:
> 
> ```dockerfile
> FROM rust:1.58.1-alpine3.14 as prisma
> ENV RUSTFLAGS="-C target-feature=-crt-static"
> RUN apk --no-cache add openssl direnv git musl-dev openssl-dev build-base perl protoc
> RUN git clone --depth=1 --branch=3.9.0 https://github.com/prisma/prisma-engines.git /prisma && cd /prisma
> RUN cargo build --release --jobs 1
> 
> FROM node:16.14.0-alpine3.14
> WORKDIR /src
> ENV PRISMA_QUERY_ENGINE_BINARY=/prisma-engines/query-engine \
>   PRISMA_MIGRATION_ENGINE_BINARY=/prisma-engines/migration-engine \
>   PRISMA_INTROSPECTION_ENGINE_BINARY=/prisma-engines/introspection-engine \
>   PRISMA_FMT_BINARY=/prisma-engines/prisma-fmt \
>   PRISMA_CLI_QUERY_ENGINE_TYPE=binary \
>   PRISMA_CLIENT_ENGINE_TYPE=binary
> COPY --from=prisma /prisma/target/release/query-engine /prisma/target/release/migration-engine /prisma/target/release/introspection-engine /prisma/target/release/prisma-fmt /prisma-engines/
> COPY . /src
> RUN cd src && yarn install
> ```

Am i doing something wrong or does this take more than 30mins? 😄

**Comment by pigooosuke** [comment]
I use `amd64/node:16-alpine` image in the case of M1 Mac.

**Comment by spvn87** [comment]
@beemstream whoops, try removing `--jobs 1` from the cargo build line, it should significantly speed things up.

I was getting a memory exhaustion error when building because I have docker limited to 2 gigs.  Assuming you have a sane amount allocated, concurrent jobs should be safe!

**Comment by spvn87** [comment]
@aqrln ahh that’s probably it. I couldn’t get the so lib to load so I just switched to the binary, let me try that change.

**Comment by wataruian** [comment]
Following this implementation. Using debian based image is not ideal for me as it is so large.

**Comment by ggohierroy** [comment]
> Hopefully this will help in the interim:
> 
> ```dockerfile
> FROM rust:1.58.1-alpine3.14 as prisma
> ENV RUSTFLAGS="-C target-feature=-crt-static"
> RUN apk --no-cache add openssl direnv git musl-dev openssl-dev build-base perl protoc
> RUN git clone --depth=1 --branch=3.9.0 https://github.com/prisma/prisma-engines.git /prisma && cd /prisma
> RUN cargo build --release --jobs 1
> 
> FROM node:16.14.0-alpine3.14
> WORKDIR /src
> ENV PRISMA_QUERY_ENGINE_BINARY=/prisma-engines/query-engine \
>   PRISMA_MIGRATION_ENGINE_BINARY=/prisma-engines/migration-engine \
>   PRISMA_INTROSPECTION_ENGINE_BINARY=/prisma-engines/introspection-engine \
>   PRISMA_FMT_BINARY=/prisma-engines/prisma-fmt \
>   PRISMA_CLI_QUERY_ENGINE_TYPE=binary \
>   PRISMA_CLIENT_ENGINE_TYPE=binary
> COPY --from=prisma /prisma/target/release/query-engine /prisma/target/release/migration-engine /prisma/target/release/introspection-engine /prisma/target/release/prisma-fmt /prisma-engines/
> COPY . /src
> RUN cd src && yarn install
> ```

I'm completely new to Docker and just trying to make sure I understand.

This here will rebuild a new image that contains the necessary dependencies for Prisma to work in Docker on M1 chips?

The downside is that this image is much larger and slower to build than just getting the alpine image directly?

Also, I'm getting a `could not find Cargo.toml in / or any parent directory`
Is there anything I can read to understand a little better what is going on and how to make it work?

Thanks!

**Comment by priithaamer** [comment]
Hi @ggohierroy 

> Also, I'm getting a `could not find Cargo.toml in / or any parent directory` Is there anything I can read to understand a little better what is going on and how to make it work?

This should be fixed if you replace line 5:

```
RUN cargo build --release --jobs 1
```

With:

```
WORKDIR /prisma
RUN cargo build --release
```

(also removed `--jobs 1` as per comment above to make it run faster)

**Comment by ggohierroy** [comment]
This is my Dockerfile right now, but it still fails with the same error when `npx prisma generate` is run

`Error: Unknown binary target linux-arm64-openssl-undefined in generator client.`

`FROM rust:1.58.1-alpine3.14 as prisma
ENV RUSTFLAGS="-C target-feature=-crt-static"
RUN apk --no-cache add openssl direnv git musl-dev openssl-dev build-base perl protoc
RUN git clone --depth=1 --branch=3.9.0 https://github.com/prisma/prisma-engines.git /prisma
WORKDIR /prisma
RUN cargo build --release --jobs 1

FROM node:16.14.0-alpine3.14
WORKDIR /app
ENV PRISMA_QUERY_ENGINE_BINARY=/prisma-engines/query-engine \
  PRISMA_MIGRATION_ENGINE_BINARY=/prisma-engines/migration-engine \
  PRISMA_INTROSPECTION_ENGINE_BINARY=/prisma-engines/introspection-engine \
  PRISMA_FMT_BINARY=/prisma-engines/prisma-fmt \
  PRISMA_CLI_QUERY_ENGINE_TYPE=binary \
  PRISMA_CLIENT_ENGINE_TYPE=binary
COPY --from=prisma /prisma/target/release/query-engine /prisma/target/release/migration-engine /prisma/target/release/introspection-engine /prisma/target/release/prisma-fmt /prisma-engines/

# Install dependencies only when needed
#FROM amd64/node:16-alpine
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# COPY package.json yarn.lock ./
# RUN yarn install --frozen-lockfile

# If using npm with a `package-lock.json` comment out above and use below instead
COPY package.json package-lock.json ./ 
# Removes node_modules and install all dependencies at once
RUN npm ci

# Copy the rest of our Next.js folder into /app
COPY . /app

# Ensure port 3000 is accessible to our system
EXPOSE 3000

RUN npx prisma generate

# Run yarn dev, as we would via the command line 
CMD ["npm", "run", "dev"]`

**Comment by aqrln** [comment]
@ggohierroy the error sounds like you added `"linux-arm64-openssl-undefined"` to `binaryTargets` in your `schema.prisma`.

**Comment by mrmemes-eth** [comment]
I'm getting the same result as @ggohierroy with a _similar_ Dockerfile:

```
FROM rust:1.58.1-alpine3.14 as prisma
ENV RUSTFLAGS="-C target-feature=-crt-static"
RUN apk --no-cache add openssl direnv git musl-dev openssl-dev build-base perl protoc
RUN git clone --depth=1 --branch=3.9.0 https://github.com/prisma/prisma-engines.git /prisma && cd /prisma
WORKDIR /prisma
RUN cargo build --release

FROM node:16.14.0-alpine3.14

WORKDIR /usr/src/app

ENV PRISMA_QUERY_ENGINE_BINARY=/prisma-engines/query-engine \
  PRISMA_MIGRATION_ENGINE_BINARY=/prisma-engines/migration-engine \
  PRISMA_INTROSPECTION_ENGINE_BINARY=/prisma-engines/introspection-engine \
  PRISMA_FMT_BINARY=/prisma-engines/prisma-fmt \
  PRISMA_CLI_QUERY_ENGINE_TYPE=binary \
  PRISMA_CLIENT_ENGINE_TYPE=binary
COPY --from=prisma /prisma/target/release/query-engine /prisma/target/release/migration-engine /prisma/target/release/introspection-engine /prisma/target/release/prisma-fmt /prisma-engines/
COPY . /usr/src/app/

COPY ["package.json", "yarn.lock", "tsconfig.json", ".env", "next.config.js", "postcss.config.js", "tailwind.config.js", "./" ]

RUN apk add --no-cache git

RUN cd /usr/src/app && yarn install

COPY ./public ./public
COPY ./src ./src

RUN yarn prisma generate

EXPOSE 3000

CMD yarn dev
```
Error:
```
 => ERROR [stage-1 10/10] RUN yarn prisma generate                                                                                       0.7s
------
 > [stage-1 10/10] RUN yarn prisma generate:
#22 0.323 yarn run v1.22.17
#22 0.352 $ /usr/src/app/node_modules/.bin/prisma generate
#22 0.638 Environment variables loaded from .env
#22 0.641 Prisma schema loaded from prisma/schema.prisma
#22 0.705 Error: Unknown binary target linux-arm64-openssl-undefined in generator client.
#22 0.705 Possible binaryTargets: darwin, darwin-arm64, debian-openssl-1.0.x, debian-openssl-1.1.x, rhel-openssl-1.0.x, rhel-openssl-1.1.x, linux-arm64-openssl-1.1.x, linux-arm64-openssl-1.0.x, linux-arm-openssl-1.1.x, linux-arm-openssl-1.0.x, linux-musl, linux-nixos, windows, freebsd11, freebsd12, openbsd, netbsd, arm, native
#22 0.723 error Command failed with exit code 1.
#22 0.724 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
executor failed running [/bin/sh -c yarn prisma generate]: exit code: 1
```
and I definitely _do not_ have any `binaryTargets` specified in my `Prisma.schema`:
```
generator client {
  provider = "prisma-client-js"
}
```

**Comment by mrmemes-eth** [comment]
Minor addition to the Dockerfile to ensure that the lack of `openssl` wasn't the issue:

```
RUN apk add --no-cache git openssl-dev
```

And to ensure that specifying the `binaryTargets` in the `schema.prisma` file wouldn't help:

```
 generator client {
   provider = "prisma-client-js"
   binaryTargets   = ["native", "linux-arm-openssl-1.1.x"]
 }
```
And I still see the same error.

**Comment by prescindivel** [comment]
> 



> Hopefully this will help in the interim:
> 
> ```dockerfile
> FROM rust:1.58.1-alpine3.14 as prisma
> ENV RUSTFLAGS="-C target-feature=-crt-static"
> RUN apk --no-cache add openssl direnv git musl-dev openssl-dev build-base perl protoc
> RUN git clone --depth=1 --branch=3.9.0 https://github.com/prisma/prisma-engines.git /prisma && cd /prisma
> RUN cargo build --release --jobs 1
> 
> FROM node:16.14.0-alpine3.14
> WORKDIR /src
> ENV PRISMA_QUERY_ENGINE_BINARY=/prisma-engines/query-engine \
>   PRISMA_MIGRATION_ENGINE_BINARY=/prisma-engines/migration-engine \
>   PRISMA_INTROSPECTION_ENGINE_BINARY=/prisma-engines/introspection-engine \
>   PRISMA_FMT_BINARY=/prisma-engines/prisma-fmt \
>   PRISMA_CLI_QUERY_ENGINE_TYPE=binary \
>   PRISMA_CLIENT_ENGINE_TYPE=binary
> COPY --from=prisma /prisma/target/release/query-engine /prisma/target/release/migration-engine /prisma/target/release/introspection-engine /prisma/target/release/prisma-fmt /prisma-engines/
> COPY . /src
> RUN cd src && yarn install
> ```

this worked for me. but is there any way to need to compile?

**Comment by ggohierroy** [comment]
> @ggohierroy the error sounds like you added `"linux-arm64-openssl-undefined"` to `binaryTargets` in your `schema.prisma`.

@aqrln Hi, nothing like that in my schema file. It's just the one from the tutorial for NextJS + Prisma.

**Comment by tyrauber** [comment]
Hey folks, is compiling prisma engines still required to run `prisma@3.11.1` on `node:lts-alpine`?  

This seems *real* close:

```
FROM node:lts-alpine
WORKDIR /app
COPY package*.json ./ prisma ./prisma/
RUN apk add --no-cache libc6-compat git openssl
RUN npm install
RUN npm install @prisma/client
COPY . .
RUN npx prisma generate --schema ./prisma/schema.prisma
RUN npm run build
EXPOSE 3000
CMD npm run start
```
Errors:

```
ERROR [10/11] RUN npx prisma generate --schema ./prisma/schema.prisma                                                                                                         6.4s 
------                                                                                                                                                                                 
 > [10/11] RUN npx prisma generate --schema ./prisma/schema.prisma:                                                                                                                    
#14 5.953 Environment variables loaded from .env                                                                                                                                       
#14 5.954 Prisma schema loaded from prisma/schema.prisma                                                                                                                               
#14 6.218 Error: Unable to require(`/app/node_modules/prisma/libquery_engine-linux-arm64-openssl-1.1.x.so.node`)
#14 6.218  Error relocating /app/node_modules/prisma/libquery_engine-linux-arm64-openssl-1.1.x.so.node: __res_init: symbol not found
```

Would love to be able to switch back over to alpine. Thanks.

**Comment by aqrln** [comment]
@tyrauber that's interesting, it looks like it downloaded the binary for Debian on ARM64

**Comment by tyrauber** [comment]
Well, that's odd. [here's a test repo](https://github.com/tyrauber/prisma-lts-alpine).  It's just prisma's testing-express repo with an alpine-lts dockerfile. I am using buildx with the default builder, and no-cache, on an M1 macbookair. Works with `node:lts`, fails with `node:lts-alpine` with the above error.

Open to any all ideas. I've been trying to build prisma on alpine-lts for longer than I'd like to admit.  This is the closest I've gotten without compiling from source. Appreciate your insights, @aqrln, and stay safe.

**Comment by bbedward** [comment]
We published an image because of how long it takes to build the prisma binaries, will make the workaround faster:

```
FROM positivly/prisma-binaries:latest as prisma
FROM node:16.13.2-alpine

## Your normal build steps here

# Set prisma environment:
ENV PRISMA_QUERY_ENGINE_BINARY=/prisma-engines/query-engine \
  PRISMA_MIGRATION_ENGINE_BINARY=/prisma-engines/migration-engine \
  PRISMA_INTROSPECTION_ENGINE_BINARY=/prisma-engines/introspection-engine \
  PRISMA_FMT_BINARY=/prisma-engines/prisma-fmt \
  PRISMA_CLI_QUERY_ENGINE_TYPE=binary \
  PRISMA_CLIENT_ENGINE_TYPE=binary
COPY --from=prisma /prisma-engines/query-engine /prisma-engines/migration-engine /prisma-engines/introspection-engine /prisma-engines/prisma-fmt /prisma-engines/
```

**Comment by thgh** [comment]
Thanks @bbedward, is it correct that those libraries are for Prisma 3.9 specifically? And openssl still needs to be installed?

Here is an example for Next.js, resulting in a 170 Mb image (61Mb compressed).
```dockerfile
FROM positivly/prisma-binaries:latest as prisma

# Install migration engine to run prisma generate
FROM node:16.13.2-alpine as builder
RUN apk add --no-cache libc6-compat openssl openssl-dev
COPY --from=prisma /prisma-engines/query-engine /prisma-engines/migration-engine /prisma-engines/
ENV NEXT_TELEMETRY_DISABLED 1
ENV NO_UPDATE_NOTIFIER true
ENV PRISMA_QUERY_ENGINE_BINARY=/prisma-engines/query-engine \
  PRISMA_MIGRATION_ENGINE_BINARY=/prisma-engines/migration-engine \
  PRISMA_CLI_QUERY_ENGINE_TYPE=binary \
  PRISMA_CLIENT_ENGINE_TYPE=binary
WORKDIR /app
COPY package.json yarn.lock .npmrc .
RUN yarn --frozen-lockfile
COPY . .
RUN yarn prisma generate && yarn build
# Save some space if copying the complete node_modules
# RUN yarn prisma generate && yarn build && yarn --prod && rm -rf ./node_modules/@prisma/engines/*engine* 

# Only needs query engine
FROM node:16.13.2-alpine as release
RUN apk add --no-cache libc6-compat openssl openssl-dev
COPY --from=prisma /prisma-engines/query-engine /prisma-engines/
ENV CHECKPOINT_DISABLE 1
ENV NEXT_TELEMETRY_DISABLED 1
ENV NODE_ENV production
ENV NO_UPDATE_NOTIFIER true
ENV PORT 3000
ENV PRISMA_HIDE_UPDATE_MESSAGE 1
ENV PRISMA_QUERY_ENGINE_BINARY=/prisma-engines/query-engine \
  PRISMA_CLI_QUERY_ENGINE_TYPE=binary \
  PRISMA_CLIENT_ENGINE_TYPE=binary
WORKDIR /app

COPY --from=builder /app/next.config.js .
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000

CMD ["node", "server.js"]
```

**Comment by bbedward** [comment]
> Thanks @bbedward, is it correct that those binaries are for Prisma 3.9 specifically? And openssl still needs to be installed?
> 
> Here is an example for Next.js, resulting in a 170 Mb image (61Mb compressed).
> 
> ```dockerfile
> FROM positivly/prisma-binaries:latest as prisma
> 
> # Install migration engine to run prisma generate
> FROM node:16.13.2-alpine as builder
> RUN apk add --no-cache libc6-compat openssl openssl-dev
> COPY --from=prisma /prisma-engines/query-engine /prisma-engines/migration-engine /prisma-engines/
> ENV NEXT_TELEMETRY_DISABLED 1
> ENV NO_UPDATE_NOTIFIER true
> ENV PRISMA_QUERY_ENGINE_BINARY=/prisma-engines/query-engine \
>   PRISMA_MIGRATION_ENGINE_BINARY=/prisma-engines/migration-engine \
>   PRISMA_CLI_QUERY_ENGINE_TYPE=binary \
>   PRISMA_CLIENT_ENGINE_TYPE=binary
> WORKDIR /app
> COPY package.json yarn.lock .npmrc .
> RUN yarn --frozen-lockfile
> COPY . .
> RUN yarn prisma generate && yarn build
> # Save some space if copying the complete node_modules
> # RUN yarn prisma generate && yarn build && yarn --prod && rm -rf ./node_modules/@prisma/engines/*engine* 
> 
> # Only needs query engine
> FROM node:16.13.2-alpine as release
> RUN apk add --no-cache libc6-compat openssl openssl-dev
> COPY --from=prisma /prisma-engines/query-engine /prisma-engines/
> ENV CHECKPOINT_DISABLE 1
> ENV NEXT_TELEMETRY_DISABLED 1
> ENV NODE_ENV production
> ENV NO_UPDATE_NOTIFIER true
> ENV PORT 3000
> ENV PRISMA_HIDE_UPDATE_MESSAGE 1
> ENV PRISMA_QUERY_ENGINE_BINARY=/prisma-engines/query-engine \
>   PRISMA_CLI_QUERY_ENGINE_TYPE=binary \
>   PRISMA_CLIENT_ENGINE_TYPE=binary
> WORKDIR /app
> 
> COPY --from=builder /app/next.config.js .
> COPY --from=builder /app/package.json ./package.json
> COPY --from=builder /app/prisma ./prisma
> COPY --from=builder /app/public ./public
> COPY --from=builder /app/.next/standalone ./
> COPY --from=builder /app/.next/static ./.next/static
> 
> EXPOSE 3000
> 
> CMD ["node", "server.js"]
> ```

Yes they are built from prisma-engine 3.9, and openssl is required still (openssl-dev should not be needed, though)

**Comment by dukejones** [comment]
> amd64/node:16-alpine

Yeah, emulating amd64 is working. Luckily M1 is so fast it doesn't matter all that much. One can do this in the `docker-compose.yml` also/instead:
```
  myservice:
    build: .
    depends_on:
      - db
    platform: "linux/amd64"
```

**Comment by RomainBillot** [comment]
> 



> We published an image because of how long it takes to build the prisma binaries, will make the workaround faster:
> 
> ```
> FROM positivly/prisma-binaries:latest as prisma
> FROM node:16.13.2-alpine
> 
> ## Your normal build steps here
> 
> # Set prisma environment:
> ENV PRISMA_QUERY_ENGINE_BINARY=/prisma-engines/query-engine \
>   PRISMA_MIGRATION_ENGINE_BINARY=/prisma-engines/migration-engine \
>   PRISMA_INTROSPECTION_ENGINE_BINARY=/prisma-engines/introspection-engine \
>   PRISMA_FMT_BINARY=/prisma-engines/prisma-fmt \
>   PRISMA_CLI_QUERY_ENGINE_TYPE=binary \
>   PRISMA_CLIENT_ENGINE_TYPE=binary
> COPY --from=prisma /prisma-engines/query-engine /prisma-engines/migration-engine /prisma-engines/introspection-engine /prisma-engines/prisma-fmt /prisma-engines/
> ```

Could you share the Dockerfile source code, please?
The `latest` tag scares us a bit ahah!

Thanks for sharing this pre-built binaries!

**Comment by brizandrew** [comment]
Hello all, 

Thanks to everyone who's been trying to get this working on this thread, it's been super helpful to read. I'm curious if anyone has gotten this solution to work:
https://github.com/prisma/prisma/issues/8478#issuecomment-1095544159 

When I try to implement it I get the following error 
```
Command failed with exit code 1: /app/node_modules/@prisma/engines/prisma-fmt-linux-arm64-openssl-1.1.x format
```

Unfortunately, there's no real error message I can debug from (see full stack trace below). Has anyone run into that? And if you think this is more of a problem with Keystone than Prisma, I'm happy to take this issue over there.

Thanks again for helping me get even this far! 

---

## Some More Context

- I'm trying to get Keystone v6 (which uses Prisma) to work in a docker image
- I was able to successfully get everything working using amd64 emulation (but as discussed that leads to about 1GB image size and 15 minutes of build time)

Full Stack Trace:
```
 > [build 9/9] RUN npm run build:
#17 2.039
#17 2.039 > my-project@1.0.0 build
#17 2.039 > keystone build
#17 2.039
#17 4.543 Error: Command failed with exit code 1: /app/node_modules/@prisma/engines/prisma-fmt-linux-arm64-openssl-1.1.x format
#17 4.543 prisma-fmt 22b822189f46ef0dc5c5b503368d1bee01213980
#17 4.543 Prisma Datamodel v2 formatter
#17 4.543
#17 4.543 USAGE:
#17 4.543     prisma-fmt <SUBCOMMAND>
#17 4.543
#17 4.543 FLAGS:
#17 4.543     -h, --help       Prints help information
#17 4.543     -V, --version    Prints version information
#17 4.543
#17 4.543 SUBCOMMANDS:
#17 4.543     debug-panic            Artificially panic (for testing the CLI)
#17 4.543     format                 Specifies format mode
#17 4.543     help                   Prints this message or the help of the given subcommand(s)
#17 4.543     lint                   Specifies linter mode
#17 4.543     native-types           Specifies Native Types mode
#17 4.543     preview-features       Specifies preview features mode
#17 4.543     referential-actions    List of available referential actions
#17 4.543     at makeError (/app/node_modules/execa/lib/error.js:60:11)
#17 4.543     at handlePromise (/app/node_modules/execa/index.js:118:26)
#17 4.543     at processTicksAndRejections (node:internal/process/task_queues:96:5)
#17 4.543     at Object.formatSchema (/app/node_modules/@prisma/sdk/dist/engine-commands/formatSchema.js:60:14)
#17 4.543     at getCommittedArtifacts (/app/node_modules/@keystone-6/core/dist/artifacts-f7bed9de.cjs.dev.js:398:13)
#17 4.543     at Object.validateCommittedArtifacts (/app/node_modules/@keystone-6/core/dist/artifacts-f7bed9de.cjs.dev.js:417:21)
#17 4.543     at Object.build (/app/node_modules/@keystone-6/core/scripts/dist/keystone-6-core-scripts.cjs.dev.js:542:3) {
#17 4.543   shortMessage: 'Command failed with exit code 1: /app/node_modules/@prisma/engines/prisma-fmt-linux-arm64-openssl-1.1.x format',
#17 4.543   command: '/app/node_modules/@prisma/engines/prisma-fmt-linux-arm64-openssl-1.1.x format',
#17 4.543   escapedCommand: '"/app/node_modules/@prisma/engines/prisma-fmt-linux-arm64-openssl-1.1.x" format',
#17 4.543   exitCode: 1,
#17 4.543   signal: undefined,
#17 4.543   signalDescription: undefined,
#17 4.543   stdout: '',
#17 4.543   stderr: 'prisma-fmt 22b822189f46ef0dc5c5b503368d1bee01213980\n' +
#17 4.543     'Prisma Datamodel v2 formatter\n' +
#17 4.543     '\n' +
#17 4.543     'USAGE:\n' +
#17 4.543     '    prisma-fmt <SUBCOMMAND>\n' +
#17 4.543     '\n' +
#17 4.543     'FLAGS:\n' +
#17 4.543     '    -h, --help       Prints help information\n' +
#17 4.543     '    -V, --version    Prints version information\n' +
#17 4.543     '\n' +
#17 4.543     'SUBCOMMANDS:\n' +
#17 4.543     '    debug-panic            Artificially panic (for testing the CLI)\n' +
#17 4.543     '    format                 Specifies format mode\n' +
#17 4.543     '    help                   Prints this message or the help of the given subcommand(s)\n' +
#17 4.543     '    lint                   Specifies linter mode\n' +
#17 4.543     '    native-types           Specifies Native Types mode\n' +
#17 4.543     '    preview-features       Specifies preview features mode\n' +
#17 4.543     '    referential-actions    List of available referential actions',
#17 4.543   failed: true,
#17 4.543   timedOut: false,
#17 4.543   isCanceled: false,
#17 4.543   killed: false
#17 4.543 }
------
executor failed running [/bin/sh -c npm run build]: exit code: 1
```

```
# Dockerfile
FROM positivly/prisma-binaries:latest as prisma

FROM node:16.13.2-alpine AS build
RUN apk add --no-cache libc6-compat openssl openssl-dev

ENV PRISMA_QUERY_ENGINE_BINARY=/prisma-engines/query-engine \
  PRISMA_MIGRATION_ENGINE_BINARY=/prisma-engines/migration-engine \
  PRISMA_CLI_QUERY_ENGINE_TYPE=binary \
  PRISMA_CLIENT_ENGINE_TYPE=binary

COPY --from=prisma /prisma-engines/query-engine /prisma-engines/migration-engine /prisma-engines/introspection-engine /prisma-engines/prisma-fmt /prisma-engines/

WORKDIR /app

ADD ./package.json ./package.json
ADD ./package-lock.json ./package-lock.json

RUN npm install

ADD . .

RUN npm run build

# Runtime container
FROM node:16.13.2-alpine
RUN apk add --no-cache libc6-compat openssl openssl-dev

ENV PRISMA_QUERY_ENGINE_BINARY=/prisma-engines/query-engine \
  PRISMA_MIGRATION_ENGINE_BINARY=/prisma-engines/migration-engine \
  PRISMA_INTROSPECTION_ENGINE_BINARY=/prisma-engines/introspection-engine \
  PRISMA_FMT_BINARY=/prisma-engines/prisma-fmt \
  PRISMA_CLI_QUERY_ENGINE_TYPE=binary \
  PRISMA_CLIENT_ENGINE_TYPE=binary
COPY --from=prisma /prisma-engines/query-engine /prisma-engines/

WORKDIR /app

COPY --from=build /app .

EXPOSE 3000
CMD ["npm", "run", "start"]
```

And this is my `package.json`
```
{
  "name": "my-project",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "dev": "keystone dev",
    "reset": "keystone dev --reset-db",
    "start": "keystone start",
    "build": "keystone build",
    "build:image": "docker build -t my-project:v1.0 . "
  },
  "private": true,
  "license": "MIT",
  "dependencies": {
    "@keystone-6/auth": "^2.0.0",
    "@keystone-6/core": "^1.1.1",
    "dotenv": "^16.0.1"
  },
  "devDependencies": {
    "eslint": "^8.15.0",
    "typescript": "^4.6.4"
  }
}
```

**Comment by thgh** [comment]
@brizandrew Keystone depends on `"@prisma/client": "3.12.0"` while `positivly/prisma-binaries:latest` only works with 3.9.

**Comment by cprieto** [comment]
We have this in our radar and hope to work on a solution soon, sadly, thanks to the way our build process work and the complexities of cross compilation and MUSL we cannot give yet a release date for this feature, sorry. I will keep posted and update when this is done and available.

**Comment by MorganGeek** [comment]
My workaround is just to rely on `node:xx-slim` instead of `node:xx-alpine`.

**Comment by ensermuyigezu** [comment]
I set db provider to "postgresql" and build using this docker file, but I got this error **UnhandledPromiseRejectionWarning: Error: error: Datasource provider not known: "cockroachdb"**
Any help please?

`FROM rust:1.58.1-alpine3.14 as prisma
ENV RUSTFLAGS="-C target-feature=-crt-static"
RUN apk --no-cache add openssl direnv git musl-dev openssl-dev build-base perl protoc
RUN git clone --depth=1 --branch=3.9.0 https://github.com/prisma/prisma-engines.git /prisma && cd /prisma
WORKDIR /prisma
RUN cargo build --release

FROM node:12.19.0-alpine3.9
WORKDIR /usr/src/app
ENV PRISMA_QUERY_ENGINE_BINARY=/prisma-engines/query-engine \
  PRISMA_MIGRATION_ENGINE_BINARY=/prisma-engines/migration-engine \
  PRISMA_INTROSPECTION_ENGINE_BINARY=/prisma-engines/introspection-engine \
  PRISMA_FMT_BINARY=/prisma-engines/prisma-fmt \
  PRISMA_CLI_QUERY_ENGINE_TYPE=binary \
  PRISMA_CLIENT_ENGINE_TYPE=binary
COPY --from=prisma /prisma/target/release/query-engine /prisma/target/release/migration-engine /prisma/target/release/introspection-engine /prisma/target/release/prisma-fmt /prisma-engines/
COPY package*.json ./

RUN npm install glob rimraf

RUN npm install

COPY . .

RUN npm run build`

**Comment by exsesx** [comment]
> My workaround is just to rely on `node:xx-slim` instead of `node:xx-alpine`.

Can you send your Dockerfile? Because I couldn't make it work with the slim version. Only just `node-xx` works for me.

**Comment by ateethk** [comment]
`# syntax=docker/dockerfile:1

FROM node:18-slim AS builder

RUN apt-get update
RUN apt-get install -y openssl

ARG NODE_ENV=production
ENV NODE_ENV $NODE_ENV

WORKDIR /app

COPY ["package.json", "package-lock.json", "./"]

RUN npm install --production

COPY . .

# Generate Prisma client
RUN npx prisma generate

# Generate build
RUN npm run build

CMD ["node", "dist/main"]`

Here is what I have working on M1

**Comment by bmxpiku** [comment]
I'm using `node:18-alipine`, upgraded from prisma `3.14` to `4.3.1` and now I experience the same issue...

**Comment by adarnon** [comment]
Probably won't be applicable to many, but we switched from Alpine to Debian and everything works well. Alpine just has too many compat issues

**Comment by WilliamABradley** [comment]
I got this working on 4.4.0 with the following dockerfile:

```dockerfile
FROM rust:1.64.0-alpine3.16 as prisma
ARG PRISMA_VERSION=4.4.0
ENV RUSTFLAGS="-C target-feature=-crt-static"
RUN apk --no-cache add openssl direnv git musl-dev openssl-dev build-base perl protoc
RUN git clone --depth=1 --branch=${PRISMA_VERSION} https://github.com/prisma/prisma-engines.git /prisma && cd /prisma
WORKDIR /prisma
RUN cargo build --release

# Configure and Install Release Dependencies
FROM node:16-alpine AS deps
ARG NPM_TOKEN
WORKDIR /app

# Prisma Support
RUN apk --no-cache add openssl
COPY --from=prisma /prisma/target/release/query-engine /prisma/target/release/migration-engine /prisma/target/release/introspection-engine /prisma/target/release/prisma-fmt /prisma-engines/
ENV PRISMA_QUERY_ENGINE_BINARY=/prisma-engines/query-engine PRISMA_MIGRATION_ENGINE_BINARY=/prisma-engines/migration-engine PRISMA_INTROSPECTION_ENGINE_BINARY=/prisma-engines/introspection-engine PRISMA_FMT_BINARY=/prisma-engines/prisma-fmt PRISMA_CLI_QUERY_ENGINE_TYPE=binary PRISMA_CLIENT_ENGINE_TYPE=binary PRISMA_CLI_BINARY_TARGETS=linux-arm64-openssl-1.1.x

...
```

**Comment by NorkzYT** [comment]
I have had a similar issue on the `aarch64` architecture, and I have resolved it. The following closed issue provides the solution.
https://github.com/prisma/studio/issues/1063#issuecomment-1335440871

**Comment by bb-centrum** [comment]
> The latest version of Alpine includes only openssl 3.x, which appears to be incompatible with Prisma's usage - as pointed out [in this comment](https://github.com/prisma/prisma/issues/14043#issuecomment-1348210456).
> 
> I was able to fix this issue without downgrading alpine, adding the platform emulation flag, or abandoning alpine in favor of vanilla debian. In my case, adding `RUN apk add --update --no-cache openssl1.1-compat` to the start of my Dockerfile fixed the issue.

@zackdotcomputer This did not work for me. Do you have an example Dockerfile that is working?

**Comment by zackdotcomputer** [comment]
Hey @bb-centrum sorry - added an edit above to clarify that this is a specific additional issue for Alpine and needs to be done in addition to sorting out the arm64 vs amd64 issues.

**Comment by sathovsepyan** [comment]
I tried using `node:16-slim`, and got another error: `Installation error: Use with glibc 2.28 requires manual installation of libvips >= 8.11.3` because of the Sharp library. 

In the end, I was able to get it working with `node:16-bullseye`.

**Comment by lluchkaa** [comment]
You can check this solution: https://github.com/prisma/prisma/issues/16553#issuecomment-1353302617

**Comment by jkomyno** [comment]
Hi @sathovsepyan, could you please open another issue about this, providing details on what problems you're seeing and how exactly we can reproduce them?

**Comment by bb-centrum** [comment]
> Hey everyone, Alberto from Prisma here. Please notice that this issue is about providing compiled Prisma engines for Linux images using the `musl` C standard library on `aarch64` / `arm64` architectures. This could be particularly useful to users on macOS with M1/M2 CPUs running Docker images based on Linux Alpine.
> 
> While we're working on our end to support this natively, most of you can already overcome this problem by using Docker Buildx, which supports a custom `--platform` flag.
> 
> For example, given an example `Dockerfile` like
> 
> ```dockerfile
> # Dockerfile for running Prisma on Linux Alpine 3.17+
> 
> # change with the Node.js version of your choice
> ARG NODE_VERSION="18.12.1"
> 
> # change with the Linux Alpine version of your choice
> ARG ALPINE_VERSION="3.17"
> 
> FROM node:${NODE_VERSION}-alpine${ALPINE_VERSION} AS base
> 
> # install OpenSSL 1.1.x, needed for Linux Alpine 3.17+
> RUN apk update \
>   && apk add openssl1.1-compat
> 
> ENV DATABASE_URL ""
> WORKDIR /app
> 
> # install your project dependencies
> COPY package.json ./
> RUN npm i
> 
> # copy your project files and Prisma schema
> COPY . ./
> 
> RUN npx prisma version
> ```
> 
> you can build it with
> 
> `docker buildx build --load -f Dockerfile --platform=linux/amd64 . -t prisma-linux-node-alpine-3.17-x64`
> 
> which acts as if you're running Docker on an `x86_64` architecture.
> 
> @zackdotcomputer, @bb-centrum, please refer to [#16553 (comment)](https://github.com/prisma/prisma/issues/16553#issuecomment-1353302617) for a working solution to the problems you've mentioned.
> 
> TL/DR, you have two choices:
> 
>     * Use a Node.js Docker image based on Alpine 3.16, like `node:alpine3.16`, `node:lts-alpine3.16`, `node:18.12.1-alpine3.16` (encouraged)
> 
>     * Install OpenSSL 1.1.x via the `openssl1.1-compat` package, e.g., by adding
>       ```dockerfile
>       RUN apk add --update --no-cache openssl1.1-compat
>       ```
>       
>       
>           
>             
>           
>       
>             
>           
>       
>           
>         
>       to your Dockerfile before installing Prisma
> 
> 
> **Notes**:
> 
>     * we recommend you to **always** pin Docker images to a specific version, to ensure reproducible builds
> 
>     * we've noticed some comments in similar issues suggesting to install `libc` / `libc6-compat` on Linux Alpine to fix the problem. Please **DON'T** do this, as it could cause other unexpected errors.

Thanks for the detailed response but running `docker buildx build --load -f Dockerfile --platform=linux/amd64` won't help if you're trying to build an image to run on arm64 e.g. a M1 Mac or Raspberry Pi in my case.

It will help if you want to build an x86 image on arm64 hardware.

**Comment by jkomyno** [comment]
Hi @bb-centrum, please configure your Github Actions to run on `linux/amd64`. You only need to use `docker buildx ... --platform=linux/arm64` when your host machine (i.e., the system where Docker is installed and running on) is running on an architecture different than `arm64`. However, doing so prompts Prisma to look for the `arm64` Prisma engines for Linux Alpine, which we do not support at the moment.

**Comment by cheesemarathon** [comment]
> Hi @bb-centrum, please configure your Github Actions to run on `linux/amd64`. You only need to use `docker buildx ... --platform=linux/arm64` when your host machine (i.e., the system where Docker is installed and running on) is running on an architecture different than `arm64`. However, doing so prompts Prisma to look for the `arm64` Prisma engines for Linux Alpine, which we do not support at the moment.

Correct me if I am wrong but do you not need to build docker images for the platform you intend to run them on? I intend to run the image on a Raspberry Pi, hence building it for `arm64`

But from your message `arm64` is not supported? However, if I build using `node:slim` base images for `arm64` rather than `node:alpine`, it builds and runs fine. Just creates a rather large image.

**Comment by bb-centrum** [comment]
> Hi @bb-centrum, please configure your Github Actions to run on `linux/amd64`. You only need to use `docker buildx ... --platform=linux/arm64` when your host machine (i.e., the system where Docker is installed and running on) is running on an architecture different than `arm64`. However, doing so prompts Prisma to look for the `arm64` Prisma engines for Linux Alpine, which we do not support at the moment.

Correct me if I am wrong but do you not need to build docker images for the platform you intend to run them on? I intend to run the image on a Raspberry Pi, hence building it for `arm64`

But from your message `arm64` is not supported? However, if I build using `node:slim` base images for `arm64` rather than `node:alpine`, it builds and runs fine. Just creates a rather large image.

**Comment by rodrigocipriani** [comment]
I sent the answer bellow on the following StackOverflow: https://stackoverflow.com/a/75009630/5045914

----

For me what works was mixed with some answers below.

For the container that was installing and generating Prisma I made this change:

```
    # FROM node:fermium-alpine3.16 AS deps
    FROM node:16-slim AS deps
    RUN apt-get update
    RUN apt-get install -y openssl libssl-dev
```

And for the container that runs, I made it:

```
    # FROM node:fermium-alpine3.16 AS runner
    FROM --platform=linux/amd64 node:fermium-alpine3.16 AS runner
```

Thanks, everyone for the answers. I hope it helps someone else.

**Comment by jkomyno** [comment]
Hey @bb-centrum, re:

> But from your message arm64 is not supported?

Prisma natively supports `arm64` for most Linux distros, but not for Linux Alpine.
If you need to run Prisma on a Docker container running on e.g. Raspberry Pi, please use `node:18-slim` or `node:lts-slim` as a base image (which runs on Linux Debian Bullseye and uses `openssl-1.1.x`).

If you really want to keep Linux Alpine, please use Docker Buildx `--platform` as detailed in [this comment](https://github.com/prisma/prisma/issues/8478#issuecomment-1355209706). Thank you!

**Comment by aleccool213** [comment]
@jkomyno Small suggestion as it seems many people are running into this issue (alpine is popular). Maybe there is a way to detect alpine is being run and for Prisma to give a nice error message.

**Comment by jkomyno** [comment]
Thanks @aleccool213, we're tracking the idea of improving the error messages in https://github.com/prisma/prisma/issues/16970, which we'm working on. A first big step in that direction is preparing several different scenarios where Prisma can be installed and run. (You can take a sneak peek in [here](https://github.com/prisma/ecosystem-tests/tree/dev/docker) ☺️)

**Comment by kewei5zhang** [comment]
>

Is there a recent error message change? it is failing all docker Prisma builds with the pre-compiled prisma image workaround.  

One of the requirements in my case is to run a docker image build on arm self-hosted runners to reduce the docker image build time. I was able to work it around by pre-compile prisma as the docker base image to have the stack build on top ot arm node, but a recent error message change failed our entire build pipeline. 

```
Error: Prisma only supports Linux Alpine on the amd64 (x86_64) system architecture. If you're running Prisma on Docker, please use Docker Buildx to simulate the amd64 architecture on your device as explained by this comment: https://github.com/prisma/prisma/issues/8478#issuecomment-1355209706
```

**Comment by kewei5zhang** [comment]
> > 
> 
> Is there a recent error message change? it is failing all docker Prisma builds with the pre-compiled prisma image workaround.
> 
> One of the requirements in my case is to run a docker image build on arm self-hosted runners to reduce the docker image build time. I was able to work it around by pre-compile prisma as the docker base image to have the stack build running on arm node, but a recent error message change failed our entire build pipeline. ( The error message was changed prob around 4hours before this comment )
> 
> ```
> Error: Prisma only supports Linux Alpine on the amd64 (x86_64) system architecture. If you're running Prisma on Docker, please use Docker Buildx to simulate the amd64 architecture on your device as explained by this comment: https://github.com/prisma/prisma/issues/8478#issuecomment-1355209706
> ```
> 
> @jkomyno

@jkomyno  [This link](https://github.com/prisma/prisma/pull/17334/files#diff-9ad51dcd7849f6fbcc1297541f4aa1584a42192e5cab5e5c9a8bbed95f7fdba6R59) broken all pre-compiled work arounds on alpine 🥲.

**Comment by kewei5zhang** [comment]
> NVM - fixed the version on 4.8.0.
> 
> > > 
> > 
> > 
> > Is there a recent error message change? it is failing all docker Prisma builds with the pre-compiled prisma image workaround.
> > One of the requirements in my case is to run a docker image build on arm self-hosted runners to reduce the docker image build time. I was able to work it around by pre-compile prisma as the docker base image to have the stack build running on arm node, but a recent error message change failed our entire build pipeline. ( The error message was changed prob around 4hours before this comment )
> > ```
> > Error: Prisma only supports Linux Alpine on the amd64 (x86_64) system architecture. If you're running Prisma on Docker, please use Docker Buildx to simulate the amd64 architecture on your device as explained by this comment: https://github.com/prisma/prisma/issues/8478#issuecomment-1355209706
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @jkomyno
> 
> @jkomyno [This link](https://github.com/prisma/prisma/pull/17334/files#diff-9ad51dcd7849f6fbcc1297541f4aa1584a42192e5cab5e5c9a8bbed95f7fdba6R59) broken all pre-compiled workarounds on alpine 🥲.

Those who are facing the same issue as me using pre-compiled Prisma image to run Prisma on alpine arm64. 
1. Fix your prisma package to an older version other than 4.9.0. `"prisma": "^4.8.1",` -> `"prisma": "4.8.1",`
2. Update `pnpx prisma generate` command to `pnpx prisma@4.8.1 generate`

**Comment by csulit** [comment]
How to apply this with a docker-compose?

**Comment by MaxAst** [comment]
@csulit you can do it like this:
```
version: "3.9"
services:
  api:
    platform: linux/amd64
    ports:
      - 4000:4000
```

**Comment by aqrln** [comment]
Hi everyone! Native support for Alpine Linux on ARM64 CPUs is now merged and will be released in Prisma 4.10.0 on Tuesday. You shouldn't need any workarounds like running the image in emulation or building the engines yourselves starting with 4.10.0. Please let us know if you have any feedback!

**Comment by bmxpiku** [comment]
I tested this yesterday and works like a charm, error message is also clear finally :)
Updates I made to make it work: 
package.json
```
"@prisma/client": "^4.10.0-dev.81",
"prisma": "^4.10.0-dev.81",
```
Dockerfile
```
-FROM node:16-alpine3.16 AS build
+FROM node:18-alpine3.17 AS build
+
+RUN apk add --update --no-cache openssl1.1-compat
```
schema.prisma
```
+binaryTargets = ["native", "linux-musl-openssl-3.0.x"]
```

**Comment by aqrln** [comment]
@bmxpiku fyi you don't have to install `openssl1.1-compat` — Prisma supports OpenSSL 3 on Alpine since 4.8.0

**Comment by bmxpiku** [comment]
oh, right - thanks :+1: 
I'll test it out once 4.10 is released

**Comment by Romanchuk** [comment]
@aqrln @bmxpiku 

ARG ALPINE_VERSION=**alpine3.17**
ARG NODE_VERSION=**18.14.0**
prisma: **4.10.1** 

`binaryTargets   = ["native", "linux-musl-openssl-3.0.x"]`

It is not working even if i add 

`RUN apk add --update --no-cache openssl1.1-compat`

to my Dockerfile

```
2023-02-15 20:59:13 Error: Query engine library for current platform "linux-musl-openssl-3.0.x" could not be found.
2023-02-15 20:59:13 You incorrectly pinned it to linux-musl-openssl-3.0.x
2023-02-15 20:59:13 
2023-02-15 20:59:13 This probably happens, because you built Prisma Client on a different platform.
2023-02-15 20:59:13 (Prisma Client looked in "/app/node_modules/@prisma/client/runtime/libquery_engine-linux-musl-openssl-3.0.x.so.node")
2023-02-15 20:59:13 
2023-02-15 20:59:13 Searched Locations:
2023-02-15 20:59:13 
2023-02-15 20:59:13   /app/node_modules/.prisma/client
2023-02-15 20:59:13   /app/node_modules/@prisma/client
2023-02-15 20:59:13   /app/node_modules/@prisma/client
2023-02-15 20:59:13   /app/node_modules/.prisma/client
2023-02-15 20:59:13   /app/apps/plotform-server/prisma
2023-02-15 20:59:13   /tmp/prisma-engines
2023-02-15 20:59:13   /app/node_modules/.prisma/client
2023-02-15 20:59:13 
2023-02-15 20:59:13 
2023-02-15 20:59:13 To solve this problem, add the platform "linux-musl-openssl-3.0.x" to the "binaryTargets" attribute in the "generator" block in the "schema.prisma" file:
2023-02-15 20:59:13 generator client {
2023-02-15 20:59:13   provider      = "prisma-client-js"
2023-02-15 20:59:13   binaryTargets = ["native", "linux-musl", "linux-musl"]
2023-02-15 20:59:13 }
2023-02-15 20:59:13 
2023-02-15 20:59:13 Then run "prisma generate" for your changes to take effect.
2023-02-15 20:59:13 Read more about deploying Prisma Client: https://pris.ly/d/client-generator
2023-02-15 20:59:13     at DefaultLibraryLoader.getLibQueryEnginePath (/app/node_modules/@prisma/client/runtime/index.js:27476:13)
2023-02-15 20:59:13     at DefaultLibraryLoader.loadLibrary (/app/node_modules/@prisma/client/runtime/index.js:27394:33)
2023-02-15 20:59:13     at LibraryEngine.loadEngine (/app/node_modules/@prisma/client/runtime/index.js:27713:24)
2023-02-15 20:59:13     at LibraryEngine.instantiateLibrary (/app/node_modules/@prisma/client/runtime/index.js:27667:5)
2023-02-15 20:59:21 No errors found.
```

**Comment by bb-centrum** [comment]
Hi all 
I'm still having issues. I'm using GitHub actions to build a container to run on arm64/v8 raspberry pi. However when switch to alpine i get the following error back again.
```
Error: Unknown binaryTarget linux-arm64-openssl-undefined and no custom engine files were provided
```

package.json:
```
"dependencies": {
    "@prisma/client": "^4.10.1",
  },
  "devDependencies": {
    "prisma": "^4.10.0",
  }
```
dockerfile:
```
# Install dependencies only when needed
FROM node:lts-alpine AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat 
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json package-lock.json ./
RUN npm ci


# Rebuild the source code only when needed
FROM node:lts-alpine AS builder
ENV DEBIAN_FRONTEND noninteractive   
ENV DEBCONF_NOWARNINGS="yes"
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during the build.
ENV NEXT_TELEMETRY_DISABLED 1
#RUN apk add --update --no-cache openssl1.1-compat
RUN npx prisma generate && npm run build

# Production image, copy all the files and run next
FROM node:lts-alpine AS runner

#RUN apk add --update --no-cache openssl1.1-compat

WORKDIR /app

ENV NODE_ENV production
# Uncomment the following line in case you want to disable telemetry during runtime.
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.js ./next.config.js
COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --chown=nextjs:nodejs --chmod=744 --from=builder /app/prisma /app/prisma
RUN touch /app/prisma/dev.db && chown nextjs:nodejs /app/prisma/dev.db && chmod 744 /app/prisma/dev.db

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
#COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
#COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000

CMD ["node_modules/.bin/next", "start"]
```
buildx platform - linux/arm64/v8

Any ideas?

**Comment by Sakub** [comment]
Hi, I'm still facing the issues, none of the given fixes work for me.

Here's my Dockerfile:
```Dockerfile
FROM node:alpine

WORKDIR /app

COPY package.json /app/package.json

RUN apk add openssl3
RUN npm install

COPY . /app
RUN npx prisma generate

EXPOSE 3000
CMD ["npm", "run", "start"]
```

and my `schema.prisma`:
```prisma
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "linux-musl-openssl-3.0.x"]
}
```

test-1  | PrismaClientInitializationError: Prisma Client could not locate the Query Engine for runtime "linux-musl-arm64-openssl-3.0.x".
test-1  | 
test-1  | This happened because Prisma Client was generated for "darwin-arm64", but the actual deployment required "linux-musl-arm64-openssl-3.0.x".
test-1  | Add "linux-musl-arm64-openssl-3.0.x" to `binaryTargets` in the "schema.prisma" file and run `prisma generate` after saving it:
test-1  | 
test-1  | generator client {
test-1  |   provider      = "prisma-client-js"
test-1  |   binaryTargets = ["native", "linux-arm64-openssl-3.0.x", "linux-musl-arm64-openssl-3.0.x"]
test-1  | }


Even if I provide the suggested targets from the error message problem still occurs. I use the M2 processor. Right now I can manage to not display this error by using the `node-slim` image but I would really want to use the `node-alpine`. Could somebody help me up with this?

**Comment by aqrln** [comment]
@Sakub you added `linux-musl-openssl-3.0.x` and not `linux-musl-arm64-openssl-3.0.x` to your schema.

**Comment by Sakub** [comment]
@aqrln Even if I add `linux-musl-arm64-openssl-3.0.x` to my schema I'm still getting the `PrismaClientInitializationError: Prisma Client could not locate the Query Engine` error.

**Comment by aqrln** [comment]
@Sakub did you regenerate the client after that? If it doesn't help, please open a new issue with reproduction, or a new discussion if you don't think you're hitting a bug and just need help. This issue is already fixed and is unrelated to your problem, and posting here sends an email to more than 50 people that were subscribed to it.
