### ISSUE TITLE
Prisma interactive transactions API error: "Argument of type 'x' is not assignable to parameter of type 'PrismaPromise<any>[]'"

### ISSUE THREAD

**Issue by Slmii** [prisma/prisma#8739]
### Bug description

See discussion in the prisma chat: https://prisma.slack.com/archives/CA491RJH0/p1628865496360000

A simple update query inside the transaction gives me an error: `Argument of type '() => Promise<Integration>' is not assignable to parameter of type 'PrismaPromise<any>[]'`.

```js
const trans = await this.prisma.$transaction(async () => {
	return this.prisma.integration.update({
		data: {
			...
		},
		where: {
			id: integration.id
		}
	});
});
```
I do have the preview feature on: `previewFeatures = ["orderByRelation", "referentialActions", "interactiveTransactions"]`, also I did a generate.

### How to reproduce

Simple query like:
```js
const trans = await this.prisma.$transaction(async () => {
	return this.prisma.integration.update({
		data: {
			...
		},
		where: {
			id: integration.id
		}
	});
});

### Expected behavior

Not to show me the error

### Prisma information

```js
model Integration {
    id                        String   @id @db.VarChar(255)
    integrationMethodId       String   @db.VarChar(255)
    name                      String   @db.VarChar(255)
    username                  String   @db.VarChar(255)
    password                  String   @db.VarChar(255)
    descriptionCharacterLimit Int      @db.Integer
    createdAt                 DateTime @default(now()) @db.Timestamptz
    updatedAt                 DateTime @updatedAt @db.Timestamptz

    @@unique([integrationMethodId, username])
}
```

### Environment & setup

```
- OS: Windows
- Database: PostgreSQL
- Node.js version: v14.15.5
```

### Prisma Version

```
2.29.0
```

**Comment by janpio** [comment]
Will most probably not change anything, but for completeness: Can you try with 2.29.1 that we just released a bit ago? Thanks.

**Comment by millsp** [comment]
Have you tried to restart the typescript server? Or just re-open VSCode?

**Comment by Rykuno** [comment]
@janpio I'm running 2.29.1 and getting the same issue. 

@millsp Restarting VSCode and typescript server does not solve the issue. 

![Screen Shot 2021-08-14 at 7 34 45 PM](https://user-images.githubusercontent.com/10355852/129463778-51f7a37c-d06a-42a6-b0ef-252e1f2da516.png)

**Comment by Slmii** [comment]
@millsp working on this after the weekend and I stopped getting the error. So perhaps the VSC/Typescript restart worked, no idea. Also something I noticed is that when I use `prisma` parameter in the callback the rollback is working propertly, but when I use `prisma` from somewhere else the rollback doesnt happen. It this supposed to work like this?

**Comment by Slmii** [comment]
Something else I also noticed, when I use an interactive transaction in my application my whole VSC editor/typescript intellisense becomes incredibly slow. I switched back to non-transaction queries and it's back to normal now, its unworkable. Maybe its just me, idk...

**Comment by millsp** [comment]
> @millsp working on this after the weekend and I stopped getting the error. So perhaps the VSC/Typescript restart worked, no idea. Also something I noticed is that when I use `prisma` parameter in the callback the rollback is working propertly, but when I use `prisma` from somewhere else the rollback doesnt happen. It this supposed to work like this?

Yes, it works this way. The callback is given a proxied prisma client that is bound to that transaction only. A regular client (that is not bound to a transaction) cannot rollback.

Sometimes, VSCode/TypeScript Server does not pick up the freshly generated types immediately. Either restarting the server, changing the import, restarting VSCode helps.


> Something else I also noticed, when I use an interactive transaction in my application my whole VSC editor/typescript intellisense becomes incredibly slow. I switched back to non-transaction queries and it's back to normal now, its unworkable. Maybe its just me, idk...
> 
> Upgrading to 2.29.1 not fixing the slowness issue.

I don't know why that would happen, as we just added a function overload signature on top of the previous `$transaction` typings. Could you provide a repro (if possible, a minimal one) so that we look into this?

**Comment by isdelrey** [comment]
Hey @Rykuno, I looked into the latest release code. You probably just need to add `interactiveTransactions` to the  preview features in your `schema.prisma` file. This is not documented but is required.

```
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["interactiveTransactions"]
}
```

Cheers!

**Comment by Rykuno** [comment]
> Hey @Rykuno, I looked into the latest release code. You probably just need to add `interactiveTransactions` to the preview features in your `schema.prisma` file. This is not documented but is required.
> 
> ```
> generator client {
>   provider = "prisma-client-js"
>   previewFeatures = ["interactiveTransactions"]
> }
> ```
> 
> Cheers!

Hey! Yes I did add add the preview feature, `db push` and try a few things but I'm not sure exactly what fixed it as I threw a bunch of solutions at once at the issue. It might just be my vscode being weird. One of those solutions i mentioned sure worked lol!

**Comment by janpio** [comment]
@Rykuno Is this still a problem? If not, feel free to close this issue 👍

**Comment by Rykuno** [comment]
> @Rykuno Is this still a problem? If not, feel free to close this issue 👍. 

I'm not the author but I have not experienced this issue again so it can most likely be closed.

**Comment by janpio** [comment]
Oh, good point (but thanks for your update!). @Slmii?

**Comment by millsp** [comment]
Marking this issue as resolved. Feel free to re-open or ping me if you encounter this again. Please make sure that you have regenerated your Prisma Client after enabling the preview flag and restarted your TS server (or VSCode).
